/* Offline WebGL scene. No remote scripts, no network calls. */
class ConflictScene {
  constructor(canvas,report) {
    this.canvas=canvas;this.report=report;this.gl=canvas.getContext('webgl',{antialias:true,alpha:false,preserveDrawingBuffer:true});
    this.yaw=-1;this.pitch=.75;this.zoom=1;this.center=[0,0,0];this.span=100;this.selected=null;this.isolate=true;this.ghost=true;this.section=false;this.sectionDirection='Y';this.selectedReference=null;this.probes=[];this.hoverHit=null;
    if(!this.gl){canvas.style.display='none';canvas.after(Object.assign(document.createElement('p'),{textContent:'WebGL is unavailable. Open this report in a browser with hardware acceleration to inspect 3D geometry.'}));return;}
    const g=this.gl;
    const vertex=`attribute vec3 p;attribute vec3 n;uniform mat4 m;varying vec3 normal;varying vec3 pos;void main(){normal=n;pos=p;gl_Position=m*vec4(p,1.);gl_PointSize=7.;}`;
    const fragment=`precision highp float;varying vec3 normal;varying vec3 pos;uniform vec4 color;uniform vec3 eye;uniform float unlit;uniform float cut;uniform vec3 cutNormal;uniform float cutOffset;void main(){if(cut>0.5&&dot(pos,cutNormal)<cutOffset)discard;vec3 N=normalize(normal);if(!gl_FrontFacing)N=-N;vec3 L=normalize(vec3(.2,-.4,1.));vec3 V=normalize(eye-pos);float d=max(dot(N,L),0.);float f=max(dot(N,normalize(vec3(-.8,.3,.3))),0.);float s=pow(max(dot(N,normalize(L+V)),0.),40.)*.3;vec3 shaded=color.rgb*(.30+.64*d+.25*f)+vec3(s);gl_FragColor=vec4(mix(shaded,color.rgb,unlit),color.a);}`;
    const shader=(type,source)=>{const s=g.createShader(type);g.shaderSource(s,source);g.compileShader(s);if(!g.getShaderParameter(s,g.COMPILE_STATUS))throw Error(g.getShaderInfoLog(s));return s};
    this.program=g.createProgram();g.attachShader(this.program,shader(g.VERTEX_SHADER,vertex));g.attachShader(this.program,shader(g.FRAGMENT_SHADER,fragment));g.linkProgram(this.program);if(!g.getProgramParameter(this.program,g.LINK_STATUS))throw Error(g.getProgramInfoLog(this.program));g.useProgram(this.program);
    this.attributes=['p','n'].map(n=>g.getAttribLocation(this.program,n));this.uniforms={};for(const n of ['m','color','eye','unlit','cut','cutNormal','cutOffset'])this.uniforms[n]=g.getUniformLocation(this.program,n);
    this.cache=new Map();this.bodies=report.bodies.map(b=>({...b,buffer:this.buffer(b.mesh)}));
    this.readout=document.createElement('p');this.readout.textContent='Hover: reference and surface XYZ · Click: select · Ctrl-click: pin a surface probe · Drag: orbit · Shift-drag: pan. Viewing does not change physical geometry.';canvas.after(this.readout);
    const clear=document.createElement('button');clear.textContent='Clear surface probes';clear.onclick=()=>{this.probes=[];this.probeList.textContent='';this.draw()};this.readout.after(clear);this.probeList=document.createElement('p');clear.after(this.probeList);
    let drag=null,lastHover=0;
    canvas.onpointerdown=e=>{drag={x:e.clientX,y:e.clientY,start:[e.clientX,e.clientY],pan:e.button===2||e.shiftKey,moved:false};canvas.setPointerCapture(e.pointerId)};
    canvas.onpointerup=e=>{if(drag&&!drag.moved&&e.button===0){const hit=this.pick(e.clientX,e.clientY);if(hit){if(e.ctrlKey){if(this.probes.length<256)this.probes.push(hit);this.probeList.textContent=this.probes.map((p,i)=>'P'+(i+1)+' '+p.reference+': '+p.position.map(v=>v.toFixed(3)).join(', ')+' mm').join(' | ');}else{this.selectedReference=hit.reference;canvas.dispatchEvent(new CustomEvent('wayricad-select',{detail:hit}));}this.readout.textContent=hit.reference+' · '+hit.position.map(v=>v.toFixed(3)).join(', ')+' mm'+(e.ctrlKey?' · pinned P'+this.probes.length:' · selected');this.draw()}}drag=null};canvas.oncontextmenu=e=>e.preventDefault();
    canvas.onpointermove=e=>{if(!drag){if(performance.now()-lastHover>80){lastHover=performance.now();this.hoverHit=this.pick(e.clientX,e.clientY);canvas.style.cursor=this.hoverHit?'crosshair':'default';if(this.hoverHit)this.readout.textContent=this.hoverHit.reference+' · X/Y/Z '+this.hoverHit.position.map(v=>v.toFixed(3)).join(', ')+' mm · Ctrl-click to pin';else this.readout.textContent='No visible triangle under cursor.';this.draw()}return;}const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(e.clientX-drag.start[0],e.clientY-drag.start[1])>4)drag.moved=true;if(drag.pan){const a=this.span/canvas.clientHeight/this.zoom;this.center[0]+=(-Math.sin(this.yaw)*dx+Math.cos(this.yaw)*Math.sin(this.pitch)*dy)*a;this.center[1]+=(Math.cos(this.yaw)*dx+Math.sin(this.yaw)*Math.sin(this.pitch)*dy)*a;this.center[2]+=Math.cos(this.pitch)*dy*a;}else{this.yaw-=dx*.008;this.pitch=Math.max(-1.5,Math.min(1.5,this.pitch+dy*.008));}drag.x=e.clientX;drag.y=e.clientY;this.draw()};
    canvas.onwheel=e=>{e.preventDefault();this.zoom=Math.max(.1,Math.min(30,this.zoom*Math.exp(-e.deltaY*.001)));this.draw()};
    new ResizeObserver(()=>this.draw()).observe(canvas);this.fit();
  }
  sectionPlane(){const dir=this.sectionDirection,raw=dir==='Custom'?(this.report.rules.section_normal||[0,1,0]):dir==='X'?[1,0,0]:dir==='Z'?[0,0,1]:[0,1,0],len=Math.hypot(...raw)||1,normal=raw.map(v=>v/len),origin=this.selected?.section_origin||this.center;return {normal,offset:normal.reduce((v,n,i)=>v+n*origin[i],0)}}
  pick(clientX,clientY){if(!this.camera)return null;const r=this.canvas.getBoundingClientRect(),nx=2*(clientX-r.left)/r.width-1,ny=1-2*(clientY-r.top)/r.height,c=this.camera,t=Math.tan(18*Math.PI/180),direction=c.z.map((v,i)=>-v+c.x[i]*nx*t*r.width/r.height+c.y[i]*ny*t),len=Math.hypot(...direction);return this.pickRay(c.eye,direction.map(v=>v/len))}
  pickRay(origin,direction){const dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],sub=(a,b)=>a.map((v,i)=>v-b[i]),plane=this.sectionPlane();let nearest=null,distance=Infinity;
    for(const body of this.bodies){if(this.selected&&this.isolate&&!this.selected.refs.includes(body.ref)&&!['board','comparison_board'].includes(body.kind))continue;const mesh=body.mesh;if(!mesh)continue;if(body.bounds){let near=0,far=Infinity,intersects=true;for(let i=0;i<3;i++){if(Math.abs(direction[i])<1e-15){if(origin[i]<body.bounds[i]||origin[i]>body.bounds[i+3])intersects=false;}else{let a=(body.bounds[i]-origin[i])/direction[i],b=(body.bounds[i+3]-origin[i])/direction[i];near=Math.max(near,Math.min(a,b));far=Math.min(far,Math.max(a,b));if(near>far)intersects=false;}}if(!intersects)continue;}for(const face of mesh.faces){const [a,b,c]=face.map(i=>mesh.vertices[i]),u=sub(b,a),v=sub(c,a),p=cross(direction,v),det=dot(u,p);if(Math.abs(det)<1e-12)continue;const q=sub(origin,a),bu=dot(q,p)/det;if(bu<0||bu>1)continue;const t=cross(q,u),bv=dot(direction,t)/det;if(bv<0||bu+bv>1)continue;const d=dot(v,t)/det;if(d<0||d>=distance)continue;const point=origin.map((value,i)=>value+d*direction[i]);if(this.section&&dot(point,plane.normal)<plane.offset-1e-9)continue;distance=d;nearest={reference:body.ref,position:point,distance:d};}}
    return nearest;
  }
  buffer(mesh){
    if(!mesh||!mesh.faces.length)return null;
    const values=[];for(const face of mesh.faces){const [a,b,c]=face.map(i=>mesh.vertices[i]),u=b.map((x,i)=>x-a[i]),v=c.map((x,i)=>x-a[i]);let n=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]],len=Math.hypot(...n);if(len<1e-12)continue;n=n.map(x=>x/len);for(const p of [a,b,c])values.push(...p,...n);}
    const g=this.gl,buffer=g.createBuffer();g.bindBuffer(g.ARRAY_BUFFER,buffer);g.bufferData(g.ARRAY_BUFFER,new Float32Array(values),g.STATIC_DRAW);return {buffer,count:values.length/6};
  }
  fit(refs){
    if(!this.gl)return;const bodies=this.bodies.filter(b=>!refs||refs.includes(b.ref));if(!bodies.length)return;
    const low=[0,1,2].map(i=>Math.min(...bodies.map(b=>b.bounds[i]))),high=[0,1,2].map(i=>Math.max(...bodies.map(b=>b.bounds[i+3])));
    this.center=low.map((x,i)=>(x+high[i])/2);this.span=Math.max(4,Math.hypot(...high.map((x,i)=>x-low[i])));this.zoom=1;this.draw();
  }
  select(issue){this.selected=issue;if(!this.gl)return;if(issue&&!this.cache.has(issue.id))this.cache.set(issue.id,this.buffer(issue.conflict_mesh));if(issue?.points?.length&&!this.cache.has(issue.id+'points')){const g=this.gl,buffer=g.createBuffer(),data=[];for(const p of issue.points[0])data.push(...p,0,0,1);g.bindBuffer(g.ARRAY_BUFFER,buffer);g.bufferData(g.ARRAY_BUFFER,new Float32Array(data),g.STATIC_DRAW);this.cache.set(issue.id+'points',{buffer,count:2});}this.fit(issue?issue.refs:null);}
  focus(){const b=this.selected?.conflict_bounds;if(b){this.center=[0,1,2].map(i=>(b[i]+b[i+3])/2);this.span=Math.max(2,Math.hypot(...[0,1,2].map(i=>b[i+3]-b[i])));this.zoom=1.4;this.draw()}else if(this.selected?.points?.length){const ps=this.selected.points[0];this.center=[0,1,2].map(i=>(ps[0][i]+ps[1][i])/2);this.span=Math.max(3,Math.hypot(...ps[0].map((v,i)=>v-ps[1][i]))*4);this.zoom=1.4;this.draw();}}
  view(top){this.yaw=top?-Math.PI/2:-1;this.pitch=top?Math.PI/2-.0001:.75;this.draw()}
  draw(){
    if(!this.gl)return;const g=this.gl,c=this.canvas,dpr=window.devicePixelRatio||1;c.width=Math.max(1,c.clientWidth*dpr);c.height=Math.max(1,c.clientHeight*dpr);g.viewport(0,0,c.width,c.height);g.clearColor(.91,.94,.965,1);g.clear(g.COLOR_BUFFER_BIT|g.DEPTH_BUFFER_BIT);g.enable(g.DEPTH_TEST);g.depthFunc(g.LEQUAL);g.enable(g.BLEND);g.blendFunc(g.SRC_ALPHA,g.ONE_MINUS_SRC_ALPHA);g.useProgram(this.program);
    const distance=this.span*1.8/this.zoom,eye=this.center.map((v,i)=>v+distance*[Math.cos(this.yaw)*Math.cos(this.pitch),Math.sin(this.yaw)*Math.cos(this.pitch),Math.sin(this.pitch)][i]);
    const norm=a=>{const n=Math.hypot(...a);return a.map(v=>v/n)},cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0);
    const z=norm(eye.map((v,i)=>v-this.center[i])),x=norm(cross([0,0,1],z)),y=cross(z,x),view=[x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,eye),-dot(y,eye),-dot(z,eye),1];
    const n=Math.max(.001,distance/1000),far=Math.max(10000,distance*100),f=1/Math.tan(18*Math.PI/180),projection=[f/(c.width/c.height),0,0,0,0,f,0,0,0,0,(far+n)/(n-far),-1,0,0,2*far*n/(n-far),0],m=new Float32Array(16);
    for(let col=0;col<4;col++)for(let row=0;row<4;row++)for(let k=0;k<4;k++)m[col*4+row]+=projection[k*4+row]*view[col*4+k];
    this.camera={eye,x,y,z};
    g.uniformMatrix4fv(this.uniforms.m,false,m);g.uniform3fv(this.uniforms.eye,eye);g.uniform1f(this.uniforms.unlit,0);const dir=this.sectionDirection;const raw=dir==='Custom'?(this.report.rules.section_normal||[0,1,0]):dir==='X'?[1,0,0]:dir==='Z'?[0,0,1]:[0,1,0];const len=Math.hypot(...raw)||1;const normal=raw.map(v=>v/len);const origin=this.selected?.section_origin||this.center;g.uniform3fv(this.uniforms.cutNormal,normal);g.uniform1f(this.uniforms.cutOffset,normal.reduce((v,n,i)=>v+n*origin[i],0));g.uniform1f(this.uniforms.cut,this.section?1:0);
    const render=(buffer,color,mode=g.TRIANGLES)=>{if(!buffer)return;g.bindBuffer(g.ARRAY_BUFFER,buffer.buffer);for(let i=0;i<2;i++){g.enableVertexAttribArray(this.attributes[i]);g.vertexAttribPointer(this.attributes[i],3,g.FLOAT,false,24,i*12)}g.uniform4fv(this.uniforms.color,color);g.drawArrays(mode,0,buffer.count)};
    for(const b of this.bodies){if(b.kind==='board'||b.kind==='comparison_board')continue;if(this.selected&&this.isolate&&!this.selected.refs.includes(b.ref))continue;render(b.buffer,b.ref===this.selectedReference?[.05,.85,.72,1]:b.kind.includes('allowance')||b.kind.includes('envelope')?[.94,.65,.22,1]:b.kind==='comparison_component'?[.86,.56,.29,1]:[.64,.68,.74,1]);}
    g.depthMask(!this.ghost);for(const b of this.bodies)if(b.kind==='board'||b.kind==='comparison_board')render(b.buffer,b.kind==='board'?[.17,.48,.39,this.ghost ? 0.24 : 1]:[.23,.43,.73,this.ghost ? 0.24 : 1]);g.depthMask(true);g.uniform1f(this.uniforms.cut,0);
    const markers=this.probes.concat(this.hoverHit?[this.hoverHit]:[]);if(markers.length){const buffer=g.createBuffer(),data=markers.flatMap(hit=>[...hit.position,0,0,1]);g.bindBuffer(g.ARRAY_BUFFER,buffer);g.bufferData(g.ARRAY_BUFFER,new Float32Array(data),g.STREAM_DRAW);g.disable(g.DEPTH_TEST);g.uniform1f(this.uniforms.unlit,1);render({buffer,count:markers.length},[.03,.75,.62,1],g.POINTS);g.deleteBuffer(buffer);g.enable(g.DEPTH_TEST);}
    if(this.selected){g.disable(g.DEPTH_TEST);g.uniform1f(this.uniforms.unlit,1);render(this.cache.get(this.selected.id),[.96,.12,.1,.95]);const points=this.cache.get(this.selected.id+'points');render(points,[.96,.12,.1,1],g.LINES);render(points,[.96,.12,.1,1],g.POINTS);g.enable(g.DEPTH_TEST);}
  }
}
