"""Offline interactive saved-board geometry and thermal results."""
from __future__ import annotations
import json
from .thermal_playback import transient_temperature_limits


def interactive_board_html(view, network=None, limits=None):
    """Embed saved geometry, selectable parts and solved fields without web assets.

    The 3D representation extrudes saved board/footprint bounds; it does not
    load STEP models. Thin-sheet fields remain identical on both faces.
    """
    data = json.dumps({'view': view, 'network': network or {}, 'limits':limits or {},
                      'transient_scale_c':transient_temperature_limits((network or {}).get('transient') or {})}, allow_nan=False,
                      separators=(',', ':'))
    data = data.replace('<', '\\u003c').replace('>', '\\u003e').replace('&', '\\u0026')
    return _HTML.replace('__BOARD_DATA__', data)


_HTML = r'''<section id="thermal-context">
<style>
#thermal-context{margin:24px 0;background:#10212c;color:#d8eaf2;border-radius:12px;padding:16px}
#thermal-context button,#thermal-context select,#thermal-context input{font:inherit;padding:6px;margin:3px;border-radius:5px}
#thermal-context button.active{background:#5fe0c2;color:#10212c}
#thermal-board{display:block;width:100%;height:640px;background:#091720;touch-action:none}
#thermal-context .board-toolbar{display:flex;flex-wrap:wrap;gap:6px;align-items:center}
#thermal-part-table{max-height:270px;overflow:auto;margin-top:12px}
#thermal-part-table table{color:#d8eaf2}#thermal-part-table tr.selected{background:#275e67}
#thermal-part-table td,#thermal-part-table th{border-color:#304654;cursor:pointer}
#thermal-readout{min-height:44px;padding:10px;background:#19323e;margin-top:8px}
</style>
<h2>Interactive saved PCB and thermal overlay</h2>
<div class="board-toolbar"><button data-side="top" class="active">Top</button><button data-side="bottom">Bottom</button><button data-side="3d">3D overview</button><button id="thermal-fit">Fit board</button><label><input id="thermal-probe-mode" type="checkbox">Click to pin probe</label><button id="thermal-clear-probes">Clear probes</button>
<label><input id="thermal-overlay" type="checkbox" checked>Temperature overlay</label>
<label>Field <select id="thermal-field"><option value="auto">Board model / available result</option><option value="junction">Same-side junction interpolation</option></select></label><label>Time <select id="thermal-time"><option value="-1">Steady state</option></select></label></div>
<div class="board-toolbar" id="thermal-playback"><button id="thermal-play">▶ Play</button><input id="thermal-scrub" type="range" min="0" max="1" value="0" aria-label="Computed thermal frame"><output id="thermal-clock"></output><label>Speed <select id="thermal-speed"><option value="1">1×</option><option value="5" selected>5×</option><option value="20">20×</option></select></label></div><p id="thermal-field-meaning"></p><svg id="thermal-board" role="img" aria-label="Saved PCB with selectable footprints, outline, drilled holes and thermal overlay"></svg>
<div id="thermal-readout">Hover to probe a field cell or inspect a part. Click a part or table row to select it. Wheel to zoom; drag to orbit in 3D; Shift-drag to move the view. Enable Click to pin probe to retain readings. View transforms do not change the physical design.</div>
<p>Saved Edge.Cuts and drilled voids are shown. Component boxes are saved footprint bounds, not physical package solids. 3D height is illustrative; no STEP models are loaded.</p>
<div id="thermal-part-table"><table><thead><tr><th data-sort="reference">Reference ↕</th><th data-sort="side">Side ↕</th><th data-sort="junction_c">Estimated Tj °C ↕</th><th data-sort="power_w">Power W ↕</th><th>Limits</th><th>Coverage</th></tr></thead><tbody></tbody></table></div>
<script type="application/json" id="thermal-board-data">__BOARD_DATA__</script>
<script>
(()=>{'use strict';
const data=JSON.parse(document.getElementById('thermal-board-data').textContent),v=data.view,n=data.network,svg=document.getElementById('thermal-board'),readout=document.getElementById('thermal-readout');
const ns='http://www.w3.org/2000/svg',bbox=v.bbox_mm||[0,0,100,100],cx=(bbox[0]+bbox[2])/2,cy=(bbox[1]+bbox[3])/2,span=Math.max(bbox[2]-bbox[0],bbox[3]-bbox[1],1),fitScale=Math.min(900/Math.max(bbox[2]-bbox[0],1),580/Math.max(bbox[3]-bbox[1],1)),thick=v.board_thickness_mm||1.6;
let side='top',selected=null,zoom=1,pan=[0,0],angle=-.6,tilt=.65,sort='reference',ascending=true,drag=null,frame=0,probes=[],cursor=null;
let hoverLabel=null;
function clearHoverLabel(){if(hoverLabel){hoverLabel.remove();hoverLabel=null;}}
function componentLabel(g,p,z,hover=false){const pt=project(p.position_mm,z),t=el('text',{x:pt[0]+3,y:pt[1]-3,fill:p.reference===selected?'#64ffe0':'#ffffff','font-size':12,'pointer-events':'none','data-component-label':hover?'hover':'selected'},g);t.textContent=p.reference+(p.junction_c!=null?' '+num(p.junction_c)+'°C':' Tj unknown');return t;}
function scheduleDraw(){if(!frame)frame=requestAnimationFrame(()=>{frame=0;draw()});}
const modeled=new Map((n.components||[]).map(x=>[x.reference,x])),parts=v.components.map(x=>({...x,junction_c:modeled.has(x.reference)?modeled.get(x.reference).junction_c:x.junction_c}));
const el=(name,attrs={},parent=svg)=>{const node=document.createElementNS(ns,name);Object.entries(attrs).forEach(([k,val])=>node.setAttribute(k,val));parent.appendChild(node);return node};
const title=(node,text)=>{const t=el('title',{},node);t.textContent=text};const num=x=>x==null?'Unknown':Number(x).toFixed(2);
const frames=(n.transient||{}).frames||[],timeSelect=document.getElementById('thermal-time');frames.forEach((f,i)=>{const o=document.createElement('option');o.value=i;o.textContent=f.time_s+' s';timeSelect.appendChild(o)});
const limitMap=new Map((data.limits.rows||[]).map(row=>[row.reference,row]));
function updateParts(){const index=Number(timeSelect.value),steady=new Map((n.components||[]).map(row=>[row.reference,row]));for(const p of parts){const row=steady.get(p.reference);p.junction_c=row?row.junction_c:v.components.find(x=>x.reference===p.reference).junction_c;p.power_w=row?row.power_w:v.components.find(x=>x.reference===p.reference).power_w;if(index>=0){const frame=frames[index],def=(n.transient.components||[]).find(x=>x.reference===p.reference);if(!def){p.junction_c=null;continue}const contact=def.nodes.reduce((sum,[node,w])=>sum+frame.temperatures_c[node]*w,0),points=(n.transient.power_schedules||{})[p.reference];let scale=1;if(points){if(frame.time_s<=points[0][0])scale=points[0][1];else if(frame.time_s>=points.at(-1)[0])scale=points.at(-1)[1];else{let k=1;while(points[k][0]<frame.time_s)k++;const a=points[k-1],b=points[k];scale=n.transient.schedule_interpolation==='step'?a[1]:a[1]+(b[1]-a[1])*(frame.time_s-a[0])/(b[0]-a[0]);if(frame.time_s===b[0])scale=b[1];}}p.power_w=def.power_w*scale;p.junction_c=def.junction_resistance_k_per_w==null?null:contact+p.power_w*def.junction_resistance_k_per_w;}}
}
function limitStatus(p){const b=limitMap.get(p.reference);if(!b||p.junction_c==null||(b.status==='UNKNOWN'&&(b.issues||[]).length)||(b.minimum_c==null&&b.maximum_c==null))return 'UNKNOWN';return b.minimum_c!=null&&p.junction_c<b.minimum_c||b.maximum_c!=null&&p.junction_c>b.maximum_c?'FAIL':'PASS';}
function frameField(base,layerIndex){const index=Number(timeSelect.value);if(index<0)return base;const meta=n.transient.spatial_index,temps=frames[index].temperatures_c,values=meta.y_centers_mm.map(()=>meta.x_centers_mm.map(()=>null));meta.cells.forEach(([i,j],k)=>values[j][i]=temps[layerIndex*meta.active_cells_per_layer+k]);return {...base,values_c:values};}
function field(){if(document.getElementById('thermal-field').value==='junction'&&Number(timeSelect.value)<0)return (v.fields_by_side||{})[side==='bottom'?'bottom':'top']||v.field||{};if(n.layers&&n.layers.length)return frameField(n.layers[side==='bottom'?n.layers.length-1:0],side==='bottom'?n.layers.length-1:0);return n.board_field||(v.fields_by_side||{})[side==='bottom'?'bottom':'top']||v.field||{}}
function project(p,z=0){let x=p[0]-cx,y=p[1]-cy;if(side==='bottom')x=-x;if(side==='3d'){const a=x*Math.cos(angle)-y*Math.sin(angle),b=x*Math.sin(angle)+y*Math.cos(angle);x=a;y=b*Math.cos(tilt)-z*Math.sin(tilt)*5;}return [500+pan[0]+x*fitScale*zoom,340+pan[1]+y*fitScale*zoom]}
function unproject(pt){let x=(pt.x-500-pan[0])/(fitScale*zoom),y=(pt.y-340-pan[1])/(fitScale*zoom);if(side==='3d'){const c=Math.cos(tilt);if(Math.abs(c)<.12)return null;y=(y+thick*Math.sin(tilt)*5)/c;const a=x*Math.cos(angle)+y*Math.sin(angle),b=-x*Math.sin(angle)+y*Math.cos(angle);x=a;y=b;}if(side==='bottom')x=-x;return [cx+x,cy+y]}
function sample(p){if(!p||!onBoard(p))return null;const f=field(),xs=f.x_centers_mm||[],ys=f.y_centers_mm||[];if(!xs.length||!ys.length)return {p,t:null};const nearest=(arr,val)=>arr.reduce((best,t,i)=>Math.abs(t-val)<Math.abs(arr[best]-val)?i:best,0),i=nearest(xs,p[0]),j=nearest(ys,p[1]);return {p,t:(f.values_c[j]||[])[i]};}
function path(ring,z=0){return ring.map((p,i)=>(i?'L':'M')+project(p,z).join(',')).join(' ')+'Z'}
function color(value,lo,hi){const t=Math.max(0,Math.min(1,hi===lo?.5:(value-lo)/(hi-lo))),colors=[[27,21,57],[101,29,114],[193,56,89],[246,133,32],[252,244,137]],k=Math.min(3,Math.floor(t*4)),a=t*4-k;return 'rgb('+colors[k].map((x,i)=>Math.round(x+(colors[k+1][i]-x)*a)).join(',')+')'}
function contains(p,ring){let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const a=ring[i],b=ring[j];if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])inside=!inside;}return inside}
function onBoard(p){return (v.outline||[]).some(s=>contains(p,s.outer_mm)&&!(s.holes_mm||[]).some(h=>contains(p,h)))&&!(v.drills||[]).some(d=>contains(p,d.contour_mm))}
function draw(){clearHoverLabel();updateParts();document.querySelectorAll('#thermal-context [data-side]').forEach(b=>b.classList.toggle('active',b.dataset.side===side));svg.replaceChildren();svg.setAttribute('viewBox','0 0 1000 680');const f=field(),values=(f.values_c||[]).flat().filter(x=>x!=null),scale=Number(timeSelect.value)>=0?data.transient_scale_c:null,lo=scale?scale[0]:values.reduce((a,b)=>Math.min(a,b),Infinity),hi=scale?scale[1]:values.reduce((a,b)=>Math.max(a,b),-Infinity);
document.getElementById('thermal-field-meaning').textContent=(Number(timeSelect.value)>=0?'Transient board field at '+frames[Number(timeSelect.value)].time_s+' s; component junctions use massless package offsets; die thermal storage is not modeled. ':'')+(n.layers&&(document.getElementById('thermal-field').value!=='junction'||Number(timeSelect.value)>=0)?'Layer-resolved field: '+f.name:n.board_field&&document.getElementById('thermal-field').value!=='junction'?'Shared thin-sheet midplane field: top and bottom temperatures are identical.':'Same-side component junction interpolation; not a solved board-surface field.');
const defs=el('defs'),mask=el('mask',{id:'thermal-board-mask',maskUnits:'userSpaceOnUse',x:-10000,y:-10000,width:20000,height:20000},defs);
for(const s of v.outline||[]){el('path',{d:path(s.outer_mm,thick),fill:'white'},mask);for(const h of s.holes_mm||[])el('path',{d:path(h,thick),fill:'black'},mask)}for(const d of v.drills||[])el('path',{d:path(d.contour_mm,thick),fill:'black'},mask);
if(side==='3d')for(const s of v.outline||[]){el('path',{d:path(s.outer_mm,0),fill:'none',stroke:'#89b6a4','stroke-width':2});for(let i=0;i<s.outer_mm.length;i++){const a=s.outer_mm[i],b=s.outer_mm[(i+1)%s.outer_mm.length];el('polygon',{points:[project(a,0),project(b,0),project(b,thick),project(a,thick)].map(p=>p.join(',')).join(' '),fill:'#234942',stroke:'#8daa99','stroke-width':.5})}}
const boardGroup=el('g',{mask:'url(#thermal-board-mask)'});for(const s of v.outline||[])el('path',{d:path(s.outer_mm,thick),fill:'#214b48'},boardGroup);
if(document.getElementById('thermal-overlay').checked&&values.length){const xs=f.x_centers_mm,ys=f.y_centers_mm;const edges=(axis,c)=>f[axis+'_edges_mm']||[c[0]-(c.length>1?(c[1]-c[0])/2:.5),...c.slice(1).map((x,i)=>(x+c[i])/2),c.at(-1)+(c.length>1?(c.at(-1)-c.at(-2))/2:.5)];const xe=edges('x',xs),ye=edges('y',ys);f.values_c.forEach((row,j)=>row.forEach((t,i)=>{if(t==null)return;el('path',{d:path([[xe[i],ye[j]],[xe[i+1],ye[j]],[xe[i+1],ye[j+1]],[xe[i],ye[j+1]]],thick+.01),fill:color(t,lo,hi),opacity:.82},boardGroup)}));const text=el('text',{x:16,y:26,fill:'#fff','font-size':15});text.textContent='Field range '+num(lo)+'–'+num(hi)+' °C';}
for(const s of v.outline||[]){el('path',{d:path(s.outer_mm,thick),fill:'none',stroke:'#d4e9db','stroke-width':2});for(const h of s.holes_mm||[])el('path',{d:path(h,thick),fill:'#091720',stroke:'#a4c9d4','stroke-width':1})}for(const d of v.drills||[]){const node=el('path',{d:path(d.contour_mm,thick),fill:'#091720',stroke:d.kind==='via'?'#496976':'#b3d9e7','stroke-width':d.kind==='via'?.25:.8});title(node,(d.reference||'Via')+' drill '+d.size_mm.map(num).join(' × ')+' mm');}
for(const p of parts.filter(p=>side==='3d'||p.side===side)){const b=p.bbox_mm||[p.position_mm[0]-.5,p.position_mm[1]-.5,p.position_mm[0]+.5,p.position_mm[1]+.5],z=side==='3d'?(p.side==='bottom'?-.8:thick+.8):thick+.02,g=el('g',{'data-reference':p.reference,tabindex:0,role:'button','aria-label':p.reference}),shape=el('path',{d:path([[b[0],b[1]],[b[2],b[1]],[b[2],b[3]],[b[0],b[3]]],z),fill:p.junction_c==null?'#253d4a':'#efce92','fill-opacity':p.junction_c==null?.2:.35,stroke:p.reference===selected?'#64ffe0':p.junction_c==null?'#89b2c6':'#ffffff','stroke-width':p.reference===selected?2.5:.7},g),info=p.reference+' · '+p.side+' · Tj '+num(p.junction_c)+' °C · '+num(p.power_w)+' W';title(shape,info);g.onpointerenter=g.onfocus=()=>{readout.textContent=info;clearHoverLabel();if(p.reference!==selected)hoverLabel=componentLabel(g,p,z,true);};g.onpointerleave=g.onblur=clearHoverLabel;g.onclick=()=>{if(drag&&drag.moved)return;clearHoverLabel();selected=p.reference;table();draw();readout.textContent=info};g.onkeydown=e=>{if(e.key==='Enter')g.onclick()};
if(p.reference===selected)componentLabel(g,p,z);}
for(const saved of probes){const q={...saved,t:sample(saved.p)?.t??null};if(q.side!==side&&side!=='3d')continue;const pp=project(q.p,thick+.08),g=el('g',{'pointer-events':'none'});el('circle',{cx:pp[0],cy:pp[1],r:5,fill:'#5fe0c2',stroke:'#fff'},g);const t=el('text',{x:pp[0]+8,y:pp[1]-8,fill:'#fff','font-size':12},g);t.textContent=q.label+' '+num(q.t)+' °C';}
if(!(v.outline||[]).length){const t=el('text',{x:30,y:100,fill:'white'});t.textContent='Saved Edge.Cuts unavailable; no board envelope is invented.'}}
function table(){const body=document.querySelector('#thermal-part-table tbody');body.replaceChildren();const rows=parts.slice().sort((a,b)=>{const x=a[sort],y=b[sort];return (x==null?1:y==null?-1:typeof x==='number'?x-y:String(x).localeCompare(String(y),undefined,{numeric:true}))*(ascending?1:-1)});for(const p of rows){const tr=document.createElement('tr');if(p.reference===selected)tr.className='selected';for(const x of [p.reference,p.side,num(p.junction_c),num(p.power_w),limitStatus(p),p.junction_c!=null?'Estimated':p.in_scope?(p.issues||[]).join('; ')||'Unknown':'No thermal inputs']){const td=document.createElement('td');td.textContent=x;tr.appendChild(td)}tr.onclick=()=>{selected=p.reference;if(side!=='3d')side=p.side;draw();table();readout.textContent=p.reference+' selected · '+p.side+' · Tj '+num(p.junction_c)+' °C'};body.appendChild(tr)}}
document.querySelectorAll('#thermal-context [data-side]').forEach(b=>b.onclick=()=>{side=b.dataset.side;document.querySelectorAll('#thermal-context [data-side]').forEach(x=>x.classList.toggle('active',x===b));clearHoverLabel();draw()});document.querySelectorAll('#thermal-context [data-sort]').forEach(h=>h.onclick=()=>{ascending=h.dataset.sort===sort?!ascending:true;sort=h.dataset.sort;table()});['thermal-overlay','thermal-field'].forEach(id=>document.getElementById(id).onchange=()=>{clearHoverLabel();draw();table()});document.getElementById('thermal-fit').onclick=()=>{zoom=1;pan=[0,0];clearHoverLabel();draw()};

const play=document.getElementById('thermal-play'),scrub=document.getElementById('thermal-scrub'),clock=document.getElementById('thermal-clock'),speed=document.getElementById('thermal-speed');
let playing=false,playStart=0,playTime=0,playHandle=0;
scrub.max=Math.max(1,frames.length-1);document.getElementById('thermal-playback').hidden=!frames.length;
function stop(){playing=false;cancelAnimationFrame(playHandle);play.textContent='▶ Play';}
function showTime(index){timeSelect.value=index;scrub.value=Math.max(0,index);clock.textContent=index<0?'Steady state':frames[index].time_s.toFixed(2)+' / '+frames.at(-1).time_s+' s';clearHoverLabel();draw();table();}
function animate(now){if(!playing)return;const t=playTime+(now-playStart)*Number(speed.value)/1000;let i=0;while(i+1<frames.length&&frames[i+1].time_s<=t)i++;if(Number(timeSelect.value)!==i)showTime(i);if(t>=frames.at(-1).time_s){stop();return;}playHandle=requestAnimationFrame(animate);}
play.onclick=()=>{if(playing){stop();return;}let index=Number(timeSelect.value);if(index<0||index===frames.length-1){index=0;showTime(0);}playTime=frames[index].time_s;playStart=performance.now();playing=true;play.textContent='Ⅱ Pause';playHandle=requestAnimationFrame(animate);};
scrub.oninput=()=>{stop();showTime(Number(scrub.value));};timeSelect.onchange=()=>{stop();showTime(Number(timeSelect.value));};
speed.onchange=()=>{if(playing){stop();play.onclick();}};document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});
if(frames.length)showTime(0);

svg.onwheel=e=>{e.preventDefault();zoom=Math.max(.3,Math.min(20,zoom*Math.exp(-e.deltaY*.001)));scheduleDraw()};svg.onpointerdown=e=>{drag={x:e.clientX,y:e.clientY,moved:false}};svg.onpointerup=e=>{if(drag){if(!drag.moved&&document.getElementById('thermal-probe-mode').checked){const pt=new DOMPoint(e.clientX,e.clientY).matrixTransform(svg.getScreenCTM().inverse()),q=sample(unproject(pt));if(q&&probes.length<256){probes.push({...q,label:'P'+(probes.length+1),side});scheduleDraw()}}drag.done=true;}};document.getElementById('thermal-clear-probes').onclick=()=>{probes=[];draw()};
svg.onpointermove=e=>{if(drag&&!drag.done&&e.buttons){const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)>2)drag.moved=true;if(side==='3d'&&!e.shiftKey&&!(e.buttons&2)){angle+=dx*.008;tilt=Math.max(-1.4,Math.min(1.4,tilt+dy*.008))}else{const rect=svg.getBoundingClientRect();pan[0]+=dx*1000/rect.width;pan[1]+=dy*680/rect.height}drag.x=e.clientX;drag.y=e.clientY;scheduleDraw();return}const pt=new DOMPoint(e.clientX,e.clientY).matrixTransform(svg.getScreenCTM().inverse()),q=sample(unproject(pt));if(!q){readout.textContent='Outside saved board, inside a drilled void, or edge-on view: no field probe.';return}readout.textContent='X '+num(q.p[0])+' mm · Y '+num(q.p[1])+' mm · nearest cell '+num(q.t)+' °C · '+(n.board_field?'shared midplane':n.layers?'layer field':'junction interpolation');const old=document.getElementById('thermal-cursor');if(old)old.remove();const pp=project(q.p,thick+.09),g=el('g',{id:'thermal-cursor','pointer-events':'none'});el('path',{d:'M'+(pp[0]-8)+','+pp[1]+'h16 M'+pp[0]+','+(pp[1]-8)+'v16',stroke:'#5fe0c2','stroke-width':1.5},g);};draw();table();})();
</script></section>'''
