'use strict';
navItems.splice(2,0,['routing','≋','Layer routing profiles']);
let routingDraft=null, routingBoard='', routingMessage='', netSearch='';
function initRouting(){
  if(routingDraft && routingBoard===state.board)return;
  routingBoard=state.board;
  routingDraft={name:'New protocol instance',protocol:'Custom',scope:'nets',nets:[],netclass:state.classes[0]?.name||'',type:'differential',target_impedance:'',geometry_tolerance:5,restrict_layers:true,rows:[],stack_hash:state.routing.stack_hash};
}
function routeOptions(values,current,blank=false){return (blank?['',...values]:values).map(v=>`<option value="${esc(v)}" ${v===current?'selected':''}>${esc(v||'None — outer layer')}</option>`).join('');}
function routingPage(){
  initRouting(); const d=routingDraft, layers=state.routing.stackup, copper=layers.filter(l=>l.name.endsWith('.Cu')).map(l=>l.name);
  return head('PROTOCOL → STACKUP → NATIVE ROUTER','Layer routing profiles','Set geometry once. KiCad selects the saved width and pair gap as you change routing layers.', '<button data-routing-action="help">How it works</button><button data-routing-action="new">New profile</button><button class="primary" data-routing-action="stage">Review & stage profile</button>')+
  `<div class="notice">After applying the review and reopening the project, use KiCad’s netclass/rule sizing mode. No manual width or gap selection is needed at each layer change. Studio can be closed. Existing copper is not resized.</div>
  <div class="routing-layout"><div class="panel routing-stack"><div class="panel-head"><h2>Physical stackup</h2><span class="pill">Saved board</span></div><div class="routing-stack-body">${layers.map(l=>`<div class="stack-layer ${l.name.endsWith('.Cu')?'copper-layer':'dielectric-layer'}"><strong>${esc(l.name)}</strong><span>${esc(l.thickness||'?')} mm ${l.epsilon_r?'· εr '+esc(l.epsilon_r):''}</span><small>${esc(l.material||l.type)}</small></div>`).join('')||'<p>No explicit physical stackup. Configure it in KiCad Board Setup, save, then reopen the board in Studio.</p>'}</div><div class="notice">References must be continuous planes along the route. A named copper layer alone does not establish that continuity. Via transitions also need a return-path review.</div></div>
  <div class="stack"><div class="panel routing-form"><h2>Routing intent</h2><div class="form-grid">
  <label>Instance / group name<input data-routing="name" value="${esc(d.name)}" placeholder="CAN1, CAN2, DDR1 Data…"></label><label>Protocol family<select data-routing="protocol">${routeOptions(['CAN','DDR','Ethernet','USB','PCIe / SerDes','RS-485','RF','Custom'],d.protocol||'Custom')}</select></label>
  <label>Apply to<select data-routing="scope">${[['nets','Selected nets / group'],['netclass','Existing netclass']].map(([v,t])=>`<option value="${v}" ${(d.scope||'netclass')===v?'selected':''}>${t}</option>`).join('')}</select></label>${d.scope==='nets'?`<div class="notice">${(d.nets||[]).length} exact nets selected · no netclass reassignment</div>`:`<label>Assigned netclass<select data-routing="netclass">${routeOptions(state.classes.map(c=>c.name),d.netclass)}</select></label>`}
  <label>Signal type<select data-routing="type">${routeOptions(['single','differential'],d.type)}</select></label><label>Target impedance (Ω)<input type="number" min="1" data-routing="target_impedance" value="${esc(d.target_impedance)}"></label>
  <label>Width / gap DRC tolerance (%)<input type="number" min="0" max="25" data-routing="geometry_tolerance" value="${esc(d.geometry_tolerance)}"></label><label class="check"><input type="checkbox" data-routing="restrict_layers" ${d.restrict_layers?'checked':''}>Prohibit tracks on unconfigured layers</label></div>
  ${d.scope==='nets'?routingNetPicker():''}<p class="mini">Use separate instances for each CAN bus, Ethernet port, or DDR data/address/clock group. A group shares one signal type and layer geometry. For pair routing, KiCad must recognize the two nets as a differential pair. The percentage above is a geometry limit, not an impedance tolerance. Existing scoped custom rules retain higher priority; review their overrides in the worksheet.</p></div>
  <div class="panel"><div class="panel-head row spread"><h2>Per-layer geometry</h2><button data-routing-action="add" ${!copper.length?'disabled':''}>+ Signal layer</button></div><div class="routing-table-wrap"><table class="routing-table"><thead><tr><th>Signal layer</th><th>Reference 1</th><th>Upper reference<br>(stripline)</th><th>Width mm</th><th>Pair gap mm</th><th></th></tr></thead><tbody>${d.rows.map((r,i)=>`<tr>${['signal_layer','bottom_reference_layer','top_reference_layer'].map(k=>`<td><select aria-label="${k} row ${i+1}" data-routing-row="${i}" data-routing-field="${k}">${routeOptions(copper,r[k],k==='top_reference_layer')}</select></td>`).join('')}<td><input aria-label="Width row ${i+1}" type="number" step=".001" min=".001" data-routing-row="${i}" data-routing-field="width" value="${esc(r.width)}"></td><td><input aria-label="Gap row ${i+1}" type="number" step=".001" min=".001" data-routing-row="${i}" data-routing-field="gap" value="${esc(r.gap)}" ${d.type==='single'?'disabled':''}></td><td><button class="small" data-routing-calc="${i}">Estimate width</button><button class="small" aria-label="Remove layer ${i+1}" data-routing-remove="${i}">×</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">Add permitted routing layers and choose their reference planes.</td></tr>'}</tbody></table></div>
  <div class="notice">Enter fabricator/field-solver dimensions, or estimate width with a fixed pair gap. Estimates support homogeneous microstrip and symmetric stripline only; they omit soldermask and conductor roughness. Review every value before staging.</div>
  ${routingMessage?`<div class="notice warn" role="status">${esc(routingMessage)}</div>`:''}
  ${d.rows.map(r=>`<div class="routing-transition"><span class="pill good">${esc(r.signal_layer)}</span><span>→ ${esc(r.width||'—')} mm width ${d.type==='differential'?' / '+esc(r.gap||'—')+' mm gap':''}</span><small>Reference: ${esc([r.top_reference_layer,r.bottom_reference_layer].filter(Boolean).join(' + '))}</small></div>`).join('')}
  </div></div></div>
  <div class="panel routing-saved"><h2>Protocol instances & native profiles</h2><p class="muted">Managed profiles can be reopened here. Other native profiles are preserved.</p>${state.routing.profiles.map(p=>`<div class="row spread routing-transition"><strong>${esc(p.profile_name)}</strong><span class="pill">${esc(state.routing.managed[p.profile_name]?.protocol||'Custom')}</span><span>${state.routing.managed[p.profile_name]?.scope==='nets'?state.routing.managed[p.profile_name].nets.length+' nets · ':''}${p.layer_entries.length} layers · ${esc(p.target_impedance)} Ω</span>${state.routing.managed[p.profile_name]?`<button data-routing-load="${esc(p.profile_name)}">Edit instance</button><button data-routing-clone="${esc(p.profile_name)}">Duplicate</button><button data-routing-delete="${esc(p.profile_name)}">Remove</button>`:'<span class="pill">Native / externally managed</span>'}</div>`).join('')||'<p>No profiles saved yet.</p>'}${state.routing.issues.map(i=>`<div class="notice warn">${esc(i.rule)}: ${esc(i.message)}</div>`).join('')}</div>`;
}
function readRouting(){
  $$('[data-routing]').forEach(el=>routingDraft[el.dataset.routing]=el.type==='checkbox'?el.checked:el.value);
  $$('[data-routing-row]').forEach(el=>routingDraft.rows[Number(el.dataset.routingRow)][el.dataset.routingField]=el.value);
}
document.addEventListener('change',e=>{if(e.target.matches('[data-routing],[data-routing-row]')){readRouting();routingMessage='';if(['type','scope'].includes(e.target.dataset.routing))render();}});
document.addEventListener('click',async e=>{
 const b=e.target.closest('button');if(!b)return;
 try{
  if(b.dataset.routingDelete){const name=b.dataset.routingDelete;showDialog('Remove protocol instance',`<p>Remove <strong>${esc(name)}</strong> and its generated routing rules from the staged workspace? Other instances and board nets are preserved. Undo is available.</p>`,async()=>{await edit('routing_remove',{name});routingDraft=null;render();},'Remove instance');return;}
  if(b.dataset.routingClone){routingDraft=structuredClone(state.routing.managed[b.dataset.routingClone]);routingDraft.name+=' copy';routingDraft.scope='nets';routingDraft.nets=[];routingDraft.stack_hash=state.routing.stack_hash;routingMessage='Geometry copied. Choose a unique instance name and its nets.';render();return;}
  if(b.dataset.routingLoad){routingDraft=structuredClone(state.routing.managed[b.dataset.routingLoad]);routingDraft.stack_hash=state.routing.stack_hash;routingDraft.reviewed=false;routingMessage='Review references and all dimensions against the current stackup before restaging.';render();return;}
  if(b.dataset.routingCalc!==undefined){readRouting();const i=Number(b.dataset.routingCalc);b.disabled=true;const result=await call('routing_estimate',{revision:state.revision,type:routingDraft.type,target_impedance:routingDraft.target_impedance,row:routingDraft.rows[i]});routingDraft.rows[i].width=result.width;routingMessage=result.qualification;render();return;}
  if(b.dataset.routingRemove!==undefined){readRouting();routingDraft.rows.splice(Number(b.dataset.routingRemove),1);render();return;}
  const a=b.dataset.routingAction;if(!a)return;readRouting();
  if(a==='select-nets'||a==='clear-nets'){const visible=routingVisibleNets();const selected=new Set(routingDraft.nets||[]);for(const net of visible){if(a==='select-nets')selected.add(net);else selected.delete(net);}routingDraft.nets=[...selected];render();return;}
  if(a==='help'){showDialog('Automatic layer routing',`<p>1. Configure the physical stackup in KiCad and save the board. Create a named instance for each protocol bus or group and select its exact nets. Search and Select visible help build large groups. Netclass-wide scope is also available. DDR single-ended data and differential clock/strobes need separate instances. Pair routing requires KiCad-recognized pair names.</p><p>2. Add each permitted signal layer, its reference plane(s), width and pair gap. Enter verified fabrication dimensions or estimate a width at a fixed gap. The estimator is a screening approximation, not impedance sign-off.</p><p>3. Review and stage, then export. Close the source project before using the exported Apply Review utility. Reopen KiCad and select netclass/rule-driven sizing once. Explicit manual sizing overrides automatic defaults.</p><p>4. Route normally. On layer changes KiCad uses the saved per-layer settings even with Studio closed. Existing traces are not resized. Native DRC checks dimensional limits; scoped custom exceptions can override them.</p><p>After stackup changes, reopen Studio and review the stale profile. Plane continuity, reference changes, return vias and via impedance need engineering review. Time-domain tuning remains disabled because this workflow does not calculate qualified propagation delays.</p>`,async()=>{},'Close');return;}
  if(a==='new'){routingDraft=null;routingMessage='';initRouting();render();}
  if(a==='add'){const copper=state.routing.stackup.filter(l=>l.name.endsWith('.Cu')).map(l=>l.name);const signal=copper.find(l=>!routingDraft.rows.some(r=>r.signal_layer===l));if(!signal)throw Error('All copper layers already have rows');const i=copper.indexOf(signal);routingDraft.rows.push({signal_layer:signal,bottom_reference_layer:copper[i===copper.length-1?i-1:i+1]||'',top_reference_layer:i>0&&i<copper.length-1?copper[i-1]:'',width:'',gap:''});render();}
  if(a==='stage'){const captured=structuredClone(routingDraft),revision=state.revision;showDialog('Review automatic layer routing',`<p><strong>${esc(captured.name)}</strong> → ${esc(captured.scope==='nets'?(captured.nets||[]).length+' selected nets':captured.netclass)} · ${esc(captured.target_impedance)} Ω</p><p>${esc(captured.protocol||'Custom')} ${captured.scope==='nets'?': '+(captured.nets||[]).map(esc).join(', '):''}</p><p>${captured.rows.map(r=>`${esc(r.signal_layer)}: ${esc(r.width)} mm width${captured.type==='differential'?', '+esc(r.gap)+' mm pair gap':''}`).join('<br>')}</p><p>Stage persistent native settings and DRC limits. Apply the review with the source project closed, then reopen in KiCad and use netclass/rule sizing. Manually selected sizes can override routing defaults.</p><label class="check"><input type="checkbox" id="routing-reviewed" required>I reviewed these dimensions, reference-plane continuity and layer-transition return paths.</label>`,async()=>{if(revision!==state.revision)throw Error('Workspace changed; reopen the review');await edit('routing_profile',{...captured,reviewed:$('#routing-reviewed').checked});},'Stage profile');}
 }catch(error){routingMessage=error.message;toast(error.message);if(view==='routing')render();}
});

function routingVisibleNets(){return state.nets.filter(n=>n&&n.toLowerCase().includes(netSearch.toLowerCase()));}
function routingNetPicker(){const selected=new Set(routingDraft.nets||[]);return `<div class="routing-net-picker"><div class="row spread"><h3>Net membership · ${selected.size} selected</h3><input id="routing-net-search" placeholder="Filter nets, e.g. CAN1 or DDR_DQ" aria-label="Filter board nets" value="${esc(netSearch)}"><button data-routing-action="select-nets">Select visible</button><button data-routing-action="clear-nets">Clear visible</button></div><div class="routing-net-list">${routingVisibleNets().map(n=>{const owner=Object.values(state.routing.managed).find(p=>p.name!==routingDraft.name&&p.scope==='nets'&&p.nets.includes(n));return `<label class="check"><input type="checkbox" data-routing-net="${esc(n)}" ${selected.has(n)?'checked':''}>${esc(n)} ${owner?`<span class="pill warn">${esc(owner.name)}</span>`:''}</label>`;}).join('')||'<p>No matching nets in the saved board.</p>'}</div><p class="mini">Selected: ${[...selected].map(esc).join(', ')||'None'}</p><p class="mini">Exact names only: the filter selects existing nets, not a wildcard rule. New or renamed nets require membership review. Differential groups must include both pair members.</p></div>`;}
document.addEventListener('input',e=>{if(e.target.id==='routing-net-search'){readRouting();netSearch=e.target.value;const pos=e.target.selectionStart;render();const el=$('#routing-net-search');el.focus();el.setSelectionRange(pos,pos);}});
document.addEventListener('change',e=>{if(e.target.dataset.routingNet!==undefined){readRouting();const selected=new Set(routingDraft.nets||[]);e.target.checked?selected.add(e.target.dataset.routingNet):selected.delete(e.target.dataset.routingNet);routingDraft.nets=[...selected];render();}});
