'use strict';
navItems.splice(2,0,['routing','≋','Layer routing profiles']);
let routingDraft=null, routingBoard='', routingBoardRevision='', routingMessage='', netSearch='', routingTab=null, routingPreviewMode='both';
const routingDrafts=new Map();
function initRouting(){
  if(routingDraft && routingBoard===state.board && routingBoardRevision===state.board_revision)return;
  if(routingBoard!==state.board || routingBoardRevision!==state.board_revision){routingDrafts.clear();routingTab=null;netSearch='';}
  routingBoard=state.board;
  routingBoardRevision=state.board_revision;
  routingDraft={name:'New protocol instance',protocol:'Custom',scope:'nets',nets:[],netclass:state.classes[0]?.name||'',type:'differential',target_impedance:'',geometry_tolerance:5,restrict_layers:true,via_type:'',via_diameter:'',via_drill:'',via_start_layer:'',via_end_layer:'',rows:[],stack_hash:state.routing.stack_hash};
}
function routeOptions(values,current,blank=false){return (blank?['',...values]:values).map(v=>`<option value="${esc(v)}" ${v===current?'selected':''}>${esc(v||'None — outer layer')}</option>`).join('');}
function routingTabs(){
  const names=Object.keys(state.routing.managed);
  return `<div class="routing-tabs" role="tablist" aria-label="Protocol instances">${names.map(name=>`<button type="button" role="tab" class="routing-tab ${routingTab===name?'active':''}" aria-selected="${routingTab===name}" data-routing-tab="${esc(name)}">${esc(name)}<small>${esc(state.routing.managed[name].protocol||'Custom')}</small></button>`).join('')}<button type="button" role="tab" class="routing-tab ${routingTab===null?'active':''}" aria-selected="${routingTab===null}" data-routing-tab-new="1">+ New protocol</button></div>`;
}
function routingPreviewGeometry(row,type,mode,scale){
  const width=Number(row.width),gap=Number(row.gap);
  if(!(width>0))return '<div class="routing-preview-empty">Enter a width to see the route.</div>';
  const pair=type==='differential'&&mode!=='trace', trace=mode!=='pair';
  const copper=Math.max(6,Math.min(26,width*scale));
  const spacing=Math.max(5,Math.min(32,(gap>0?gap:0)*scale));
  const bar=(y,color)=>`<rect x="48" y="${y.toFixed(2)}" width="405" height="${copper.toFixed(2)}" rx="${Math.min(5,copper/2)}" fill="${color}"/>`;
  const traceDrawing=trace?bar(pair?20:65,'#40aab6'):'';
  const firstPairY=trace?82:49;
  const pairDrawing=pair?bar(firstPairY,'#dc8b37')+bar(firstPairY+copper+spacing,'#dc8b37'):'';
  return `<svg class="routing-preview-svg" viewBox="0 0 500 180" role="img" aria-label="${esc(row.signal_layer)} parallel ${pair?'differential-pair':'single-trace'} geometry">${traceDrawing}${pairDrawing}</svg>`;
}
function routingStackupPreview(row){
  const signal=row.signal_layer, references=new Set([row.top_reference_layer,row.bottom_reference_layer].filter(Boolean));
  return `<div class="routing-mini-stack" aria-label="${esc(signal)} stackup and references">${state.routing.stackup.map(layer=>`<div class="routing-mini-layer ${layer.name===signal?'signal':references.has(layer.name)?'reference':layer.name.endsWith('.Cu')?'other-copper':'dielectric'}"><span>${esc(layer.name)}</span>${layer.name===signal?'<strong>Route</strong>':references.has(layer.name)?'<strong>Reference</strong>':''}</div>`).join('')}</div>`;
}
function routingViaPreview(d){
  const outer=Number(d.via_diameter),drill=Number(d.via_drill);
  if(!d.via_type||!(outer>0&&drill>0&&outer>drill))return '';
  const radius=42, hole=Math.max(3,Math.min(37,radius*drill/outer));
  const copper=state.routing.stackup.filter(l=>l.name.endsWith('.Cu')).map(l=>l.name);
  const start=d.via_type==='through'?copper[0]:d.via_start_layer,end=d.via_type==='through'?copper.at(-1):d.via_end_layer;
  return `<div class="routing-via-preview"><svg viewBox="0 0 110 110" role="img" aria-label="Via copper diameter ${esc(d.via_diameter)} millimetres, drill ${esc(d.via_drill)} millimetres"><circle cx="55" cy="55" r="${radius}" fill="#dc8b37"/><circle cx="55" cy="55" r="${hole.toFixed(2)}" fill="var(--surface)" stroke="var(--line)" stroke-width="2"/></svg><div><strong>${esc(d.via_type)} via</strong><small>Ø ${esc(d.via_diameter)} mm · drill ${esc(d.via_drill)} mm</small><small>${esc(start||'Choose start')} → ${esc(end||'Choose end')}</small></div></div>`;
}
function routingViaForm(copper){
  const d=routingDraft, via=d.via_type||'', required=via&&via!=='through';
  const suggested=state.routing.via_defaults_by_netclass?.[d.netclass]||state.routing.suggested_via;
  const suggestion=Number(suggested?.via_diameter)>0&&Number(suggested?.via_drill)>0;
  return `<div class="panel routing-via-form"><div class="panel-head row spread"><div><h2>Via transition</h2><p class="mini">One reviewed via recipe for this protocol instance</p></div><button class="small" data-routing-action="via-defaults" ${suggestion?'':'disabled'}>Use saved ${esc(d.scope==='netclass'?d.netclass:'Default')} sizes</button></div><div class="routing-via-fields"><label>Via type<select data-routing="via_type"><option value="" ${!via?'selected':''}>No via recipe</option>${[['through','Through'],['micro','Microvia'],['blind','Blind via'],['buried','Buried via']].map(([value,label])=>`<option value="${value}" ${via===value?'selected':''}>${label}</option>`).join('')}</select></label><label>Copper diameter (mm)<input type="number" step=".001" min=".001" data-routing="via_diameter" value="${esc(d.via_diameter||'')}" ${via?'':'disabled'}></label><label>Drill diameter (mm)<input type="number" step=".001" min=".001" data-routing="via_drill" value="${esc(d.via_drill||'')}" ${via?'':'disabled'}></label>${required?`<label>From copper layer<select data-routing="via_start_layer">${routeOptions(copper,d.via_start_layer,true)}</select></label><label>To copper layer<select data-routing="via_end_layer">${routeOptions(copper,d.via_end_layer,true)}</select></label>`:'<div class="routing-via-span">Through vias span the outer copper layers. A microvia, blind via or buried via needs an explicit layer span enabled in Board Setup.</div>'}</div><div class="notice">Studio stores via dimensions and type restrictions for native DRC. KiCad does not automatically switch via type from this profile; choose the via type in the router. The selected diameter and drill must meet your board and fabricator limits.</div></div>`;
}
function routingHelp(){return `<div class="routing-help"><p>This page prepares routing rules from a <strong>saved KiCad board</strong>. It does not modify the board while you edit the profile.</p><h3>1 · Save and refresh</h3><p>Save the PCB and Board Setup in KiCad. Studio reloads a clean saved snapshot when its window regains focus; use <strong>Reload saved board</strong> if needed. Export or undo staged changes before reloading.</p><h3>2 · Choose the affected nets</h3><p>Create one instance for each bus or signal group. Select its exact nets, or use an existing netclass. The search filters names already present in the saved board; it does not create a wildcard assignment. A differential pair needs KiCad-recognized names such as CAN_P and CAN_N.</p><h3>3 · Define geometry for each layer</h3><p>Choose a signal layer and actual continuous reference plane, then enter reviewed trace width and pair gap. The side-by-side stackup and parallel-trace cards use one scale so you can compare layers. Check that the pair gap does not conflict with a larger clearance rule. The built-in width estimate is only a screening calculation.</p><h3>4 · Define the via transition</h3><p>Choose a via type, copper diameter and drill; for microvias, blind vias and buried vias, also choose the layer span. Board Setup must permit those via types and your dimensions must meet manufacturing floors. <strong>KiCad does not switch via type automatically from this profile:</strong> select the via type in the router. Studio stages scoped DRC rules for the reviewed choice.</p><h3>5 · Stage, apply and route</h3><p>Review and stage the profile, export the bundle, close the source project, apply the review, and reopen KiCad. Use netclass/rule track sizing with <strong>Auto track width off</strong>. KiCad 10 keeps one width during an active route: finish at the via and start a new route on the destination layer to pick up its width and pair gap. Studio may be closed. Existing copper is not resized.</p><p class="mini">The preview illustrates geometry, not impedance, a routed path, plane continuity, via impedance or native DRC acceptance. Recheck the profile after stackup or net changes.</p></div>`;}
function routingPreviews(){
  const d=routingDraft, values=d.rows.map(r=>Number(r.width)).filter(v=>v>0);
  const gaps=d.type==='differential'?d.rows.map(r=>Number(r.gap)).filter(v=>v>0):[];
  const scale=Math.min(26/Math.max(0.001,...values),32/Math.max(0.001,...gaps),120);
  return `<div class="panel routing-preview-panel"><div class="panel-head row spread"><div><h2>Compare layers</h2><p class="mini">Stackup and parallel traces shown side by side · one geometric scale for every layer</p></div><div class="routing-preview-modes" role="group" aria-label="Preview geometry">${['trace','pair','both'].map(mode=>`<button type="button" class="small ${routingPreviewMode===mode?'active':''}" data-routing-preview="${mode}" ${d.type==='single'&&mode==='pair'?'disabled':''}>${mode==='both'?'Trace + pair':mode==='trace'?'Trace':'Pair'}</button>`).join('')}</div></div><div class="routing-preview-grid">${d.rows.map(r=>`<div class="routing-preview-card"><div class="routing-preview-layer">${esc(r.signal_layer||'Signal layer')}<span>${esc([r.top_reference_layer,r.bottom_reference_layer].filter(Boolean).join(' + ')||'Select reference')}</span></div><div class="routing-preview-comparison"><div><small>Stackup context</small>${routingStackupPreview(r)}</div><div><small>Parallel copper geometry</small>${routingPreviewGeometry(r,d.type,routingPreviewMode,scale)}</div></div><div class="routing-preview-metrics"><span>Track width <strong>${esc(r.width||'—')} mm</strong></span>${d.type==='differential'?`<span>Pair gap <strong>${esc(r.gap||'—')} mm</strong></span>`:''}</div></div>`).join('')||'<div class="routing-preview-empty">Add a signal layer to preview its geometry.</div>'}</div>${routingViaPreview(d)}<p class="mini">Illustrative cross-section and copper geometry. The copper widths and gaps use one scale across these cards; reference-plane continuity, impedance and via transitions still need engineering review.</p></div>`;
}
function routingPage(){
  initRouting(); const d=routingDraft, layers=state.routing.stackup, copper=layers.filter(l=>l.name.endsWith('.Cu')).map(l=>l.name);
  return head('PROTOCOL → STACKUP → NATIVE ROUTER','Layer routing profiles','Set per-layer geometry once. KiCad selects the saved width and pair gap when a route starts on that layer.', '<button data-routing-action="help">How it works</button><button data-routing-action="new">New profile</button><button class="primary" data-routing-action="stage">Review & stage profile</button>')+
  `<div class="notice">After applying the review and reopening the project, use KiCad’s netclass/rule sizing mode. Turn off KiCad’s <strong>Auto track width</strong> button so a route started from existing copper uses the destination layer’s rule rather than inheriting the old width. KiCad 10 keeps one width during an active route: finish at a via, then start the next route on the new layer. Studio can be closed. Existing copper is not resized.</div>
  ${routingTabs()}
  <div class="routing-layout"><div class="panel routing-stack"><div class="panel-head"><h2>Physical stackup</h2><span class="pill">Saved board</span></div><div class="routing-stack-body">${layers.map(l=>`<div class="stack-layer ${l.name.endsWith('.Cu')?'copper-layer':'dielectric-layer'}"><strong>${esc(l.name)}</strong><span>${esc(l.thickness||'?')} mm ${l.epsilon_r?'· εr '+esc(l.epsilon_r):''}</span><small>${esc(l.material||l.type)}</small></div>`).join('')||'<p>No explicit physical stackup. Configure it in KiCad Board Setup, save, then reopen the board in Studio.</p>'}</div><div class="notice">References must be continuous planes along the route. A named copper layer alone does not establish that continuity. Via transitions also need a return-path review.</div></div>
  <div class="stack"><div class="panel routing-form"><h2>Routing intent</h2><div class="form-grid">
  <label>Instance / group name<input data-routing="name" value="${esc(d.name)}" placeholder="CAN1, CAN2, DDR1 Data…"></label><label>Protocol family<select data-routing="protocol">${routeOptions(['CAN','DDR','Ethernet','USB','PCIe / SerDes','RS-485','RF','Custom'],d.protocol||'Custom')}</select></label>
  <label>Apply to<select data-routing="scope">${[['nets','Selected nets / group'],['netclass','Existing netclass']].map(([v,t])=>`<option value="${v}" ${(d.scope||'netclass')===v?'selected':''}>${t}</option>`).join('')}</select></label>${d.scope==='nets'?`<div class="notice">${(d.nets||[]).length} exact nets selected · no netclass reassignment</div>`:`<label>Assigned netclass<select data-routing="netclass">${routeOptions(state.classes.map(c=>c.name),d.netclass)}</select></label>`}
  <label>Signal type<select data-routing="type">${routeOptions(['single','differential'],d.type)}</select></label><label>Target impedance (Ω)<input type="number" min="1" data-routing="target_impedance" value="${esc(d.target_impedance)}"></label>
  <label>Width / gap DRC tolerance (%)<input type="number" min="0" max="25" data-routing="geometry_tolerance" value="${esc(d.geometry_tolerance)}"></label><label class="check"><input type="checkbox" data-routing="restrict_layers" ${d.restrict_layers?'checked':''}>Prohibit tracks on unconfigured layers</label></div>
  ${d.scope==='nets'?routingNetPicker():''}<p class="mini">Use separate instances for each CAN bus, Ethernet port, or DDR data/address/clock group. A group shares one signal type and layer geometry. For pair routing, KiCad must recognize the two nets as a differential pair. The percentage above is a geometry limit, not an impedance tolerance. Existing scoped custom rules retain higher priority; review their overrides in the worksheet.</p></div>
  <div class="panel"><div class="panel-head row spread"><h2>Per-layer geometry</h2><button data-routing-action="add" ${!copper.length?'disabled':''}>+ Signal layer</button></div><div class="routing-table-wrap"><table class="routing-table"><thead><tr><th>Signal layer</th><th>Reference 1</th><th>Upper reference<br>(stripline)</th><th>Width mm</th><th>Pair gap mm</th><th></th></tr></thead><tbody>${d.rows.map((r,i)=>`<tr>${['signal_layer','bottom_reference_layer','top_reference_layer'].map(k=>`<td><select aria-label="${k} row ${i+1}" data-routing-row="${i}" data-routing-field="${k}">${routeOptions(copper,r[k],k==='top_reference_layer')}</select></td>`).join('')}<td><input aria-label="Width row ${i+1}" type="number" step=".001" min=".001" data-routing-row="${i}" data-routing-field="width" value="${esc(r.width)}"></td><td><input aria-label="Gap row ${i+1}" type="number" step=".001" min=".001" data-routing-row="${i}" data-routing-field="gap" value="${esc(r.gap)}" ${d.type==='single'?'disabled':''}></td><td><button class="small" data-routing-calc="${i}">Estimate width</button><button class="small" aria-label="Remove layer ${i+1}" data-routing-remove="${i}">×</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">Add permitted routing layers and choose their reference planes.</td></tr>'}</tbody></table></div>
  <div class="notice">Enter fabricator/field-solver dimensions, or estimate width with a fixed pair gap. Estimates support homogeneous microstrip and symmetric stripline only; they omit soldermask and conductor roughness. Review every value before staging.</div>
  ${routingMessage?`<div class="notice warn" role="status">${esc(routingMessage)}</div>`:''}
  </div>${routingViaForm(copper)}${routingPreviews()}</div></div>
  <div class="panel routing-saved"><h2>Protocol instances & native profiles</h2><p class="muted">Managed profiles can be reopened here. Other native profiles are preserved.</p>${state.routing.profiles.map(p=>`<div class="row spread routing-transition"><strong>${esc(p.profile_name)}</strong><span class="pill">${esc(state.routing.managed[p.profile_name]?.protocol||'Custom')}</span><span>${state.routing.managed[p.profile_name]?.scope==='nets'?state.routing.managed[p.profile_name].nets.length+' nets · ':''}${p.layer_entries.length} layers · ${esc(p.target_impedance)} Ω</span>${state.routing.managed[p.profile_name]?`<button data-routing-load="${esc(p.profile_name)}">Edit instance</button><button data-routing-clone="${esc(p.profile_name)}">Duplicate</button><button data-routing-delete="${esc(p.profile_name)}">Remove</button>`:'<span class="pill">Native / externally managed</span>'}</div>`).join('')||'<p>No profiles saved yet.</p>'}${state.routing.issues.map(i=>`<div class="notice warn">${esc(i.rule)}: ${esc(i.message)}</div>`).join('')}${(state.routing.advisories||[]).map(i=>`<div class="notice warn">${esc(i.message)}</div>`).join('')}</div>`;
}
function readRouting(){
  $$('[data-routing]').forEach(el=>routingDraft[el.dataset.routing]=el.type==='checkbox'?el.checked:el.value);
  $$('[data-routing-row]').forEach(el=>routingDraft.rows[Number(el.dataset.routingRow)][el.dataset.routingField]=el.value);
}
document.addEventListener('change',e=>{if(e.target.matches('[data-routing],[data-routing-row]')){readRouting();routingMessage='';if(['type','scope','via_type','netclass'].includes(e.target.dataset.routing))render();else refreshRoutingPreviews();}});
function refreshRoutingPreviews(){const panel=$('.routing-preview-panel');if(panel)panel.outerHTML=routingPreviews();}
document.addEventListener('input',e=>{if(e.target.matches('[data-routing-row][data-routing-field="width"],[data-routing-row][data-routing-field="gap"],[data-routing="via_diameter"],[data-routing="via_drill"]')){readRouting();refreshRoutingPreviews();}});
document.addEventListener('click',async e=>{
 const b=e.target.closest('button');if(!b)return;
 try{
  if(b.dataset.routingTab!==undefined||b.dataset.routingTabNew!==undefined){readRouting();routingDrafts.set(routingTab,routingDraft);routingTab=b.dataset.routingTabNew!==undefined?null:b.dataset.routingTab;routingDraft=routingDrafts.get(routingTab)||null;if(!routingDraft){if(routingTab===null){initRouting();}else{routingDraft=structuredClone(state.routing.managed[routingTab]);routingDraft.stack_hash=state.routing.stack_hash;routingDraft.reviewed=false;}}routingMessage='';render();return;}
  if(b.dataset.routingPreview!==undefined){readRouting();routingPreviewMode=b.dataset.routingPreview;refreshRoutingPreviews();return;}
  if(b.dataset.routingDelete){const name=b.dataset.routingDelete;showDialog('Remove protocol instance',`<p>Remove <strong>${esc(name)}</strong> and its generated routing rules from the staged workspace? Other instances and board nets are preserved. Undo is available.</p>`,async()=>{await edit('routing_remove',{name});routingDrafts.delete(name);routingTab=null;routingDraft=null;render();},'Remove instance');return;}
  if(b.dataset.routingClone){routingDraft=structuredClone(state.routing.managed[b.dataset.routingClone]);routingDraft.name+=' copy';routingDraft.scope='nets';routingDraft.nets=[];routingDraft.stack_hash=state.routing.stack_hash;routingTab=null;routingMessage='Geometry copied. Choose a unique instance name and its nets.';render();return;}
  if(b.dataset.routingLoad){routingTab=b.dataset.routingLoad;routingDraft=structuredClone(state.routing.managed[routingTab]);routingDraft.stack_hash=state.routing.stack_hash;routingDraft.reviewed=false;routingMessage='Review references and all dimensions against the current stackup before restaging.';render();return;}
  if(b.dataset.routingCalc!==undefined){readRouting();const i=Number(b.dataset.routingCalc);b.disabled=true;const result=await call('routing_estimate',{revision:state.revision,type:routingDraft.type,target_impedance:routingDraft.target_impedance,row:routingDraft.rows[i]});routingDraft.rows[i].width=result.width;routingMessage=result.qualification;render();return;}
  if(b.dataset.routingRemove!==undefined){readRouting();routingDraft.rows.splice(Number(b.dataset.routingRemove),1);render();return;}
  const a=b.dataset.routingAction;if(!a)return;readRouting();
  if(a==='via-defaults'){const selected=state.routing.via_defaults_by_netclass?.[routingDraft.netclass]||state.routing.suggested_via;if(!selected?.via_diameter||!selected?.via_drill)throw Error('No saved via dimensions are available for this netclass');Object.assign(routingDraft,{via_type:'through',via_diameter:selected.via_diameter,via_drill:selected.via_drill,via_start_layer:'',via_end_layer:''});routingMessage='Copied saved board dimensions. Review the fabricator limits before staging.';render();return;}
  if(a==='select-nets'||a==='clear-nets'){const visible=routingVisibleNets();const selected=new Set(routingDraft.nets||[]);for(const net of visible){if(a==='select-nets')selected.add(net);else selected.delete(net);}routingDraft.nets=[...selected];render();return;}
  if(a==='help'){showDialog('Layer routing profiles',routingHelp(),async()=>{},'Close');return;}
  if(a==='new'){routingTab=null;routingDraft=null;routingMessage='';initRouting();render();}
  if(a==='add'){const copper=state.routing.stackup.filter(l=>l.name.endsWith('.Cu')).map(l=>l.name);const signal=copper.find(l=>!routingDraft.rows.some(r=>r.signal_layer===l));if(!signal)throw Error('All copper layers already have rows');const i=copper.indexOf(signal);routingDraft.rows.push({signal_layer:signal,bottom_reference_layer:copper[i===copper.length-1?i-1:i+1]||'',top_reference_layer:i>0&&i<copper.length-1?copper[i-1]:'',width:'',gap:''});render();}
  if(a==='stage'){const captured=structuredClone(routingDraft),revision=state.revision;const via=captured.via_type?`${esc(captured.via_type)} via: Ø ${esc(captured.via_diameter)} mm, drill ${esc(captured.via_drill)} mm${captured.via_type==='through'?'':', '+esc(captured.via_start_layer)+' → '+esc(captured.via_end_layer)}`:'No via recipe';showDialog('Review layer routing profile',`<p><strong>${esc(captured.name)}</strong> → ${esc(captured.scope==='nets'?(captured.nets||[]).length+' selected nets':captured.netclass)} · ${esc(captured.target_impedance)} Ω</p><p>${esc(captured.protocol||'Custom')} ${captured.scope==='nets'?': '+(captured.nets||[]).map(esc).join(', '):''}</p><p>${captured.rows.map(r=>`${esc(r.signal_layer)}: ${esc(r.width)} mm width${captured.type==='differential'?', '+esc(r.gap)+' mm pair gap':''}`).join('<br>')}</p><p>${via}</p><p>Stage persistent native settings and DRC limits. Apply the review with the source project closed, then reopen in KiCad and use netclass/rule sizing. Turn off Auto track width and restart routing from the via on the destination layer to pick up its profile. KiCad does not automatically choose the via type from this recipe.</p><label class="check"><input type="checkbox" id="routing-reviewed" required>I reviewed track, pair and via dimensions, reference-plane continuity and layer-transition return paths.</label>`,async()=>{if(revision!==state.revision)throw Error('Workspace changed; reopen the review');await edit('routing_profile',{...captured,reviewed:$('#routing-reviewed').checked});},'Stage profile');}
 }catch(error){routingMessage=error.message;toast(error.message);if(view==='routing')render();}
});

function routingVisibleNets(){return state.nets.filter(n=>n&&n.toLowerCase().includes(netSearch.toLowerCase()));}
function routingNetPicker(){const selected=new Set(routingDraft.nets||[]);return `<div class="routing-net-picker"><div class="row spread"><h3>Net membership · ${selected.size} selected</h3><input id="routing-net-search" placeholder="Filter nets, e.g. CAN1 or DDR_DQ" aria-label="Filter board nets" value="${esc(netSearch)}"><button data-routing-action="select-nets">Select visible</button><button data-routing-action="clear-nets">Clear visible</button></div><div class="routing-net-list">${routingVisibleNets().map(n=>{const owner=Object.values(state.routing.managed).find(p=>p.name!==routingDraft.name&&p.scope==='nets'&&p.nets.includes(n));return `<label class="check"><input type="checkbox" data-routing-net="${esc(n)}" ${selected.has(n)?'checked':''}>${esc(n)} ${owner?`<span class="pill warn">${esc(owner.name)}</span>`:''}</label>`;}).join('')||'<p>No matching nets in the saved board.</p>'}</div><p class="mini">Selected: ${[...selected].map(esc).join(', ')||'None'}</p><p class="mini">Exact names only: the filter selects existing nets, not a wildcard rule. New or renamed nets require membership review. Differential groups must include both pair members.</p></div>`;}
document.addEventListener('input',e=>{if(e.target.id==='routing-net-search'){readRouting();netSearch=e.target.value;const pos=e.target.selectionStart;render();const el=$('#routing-net-search');el.focus();el.setSelectionRange(pos,pos);}});
document.addEventListener('change',e=>{if(e.target.dataset.routingNet!==undefined){readRouting();const selected=new Set(routingDraft.nets||[]);e.target.checked?selected.add(e.target.dataset.routingNet):selected.delete(e.target.dataset.routingNet);routingDraft.nets=[...selected];render();}});
