'use strict';
const $ = (q, root=document) => root.querySelector(q);
const $$ = (q, root=document) => [...root.querySelectorAll(q)];
const esc = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=null, view='workspace', selected=null, selectedClause=0, scope=['all',''], search='', includeDisabled=true;
let inspection=null, objectA=null, objectB=null, matchEpoch=0, nextId=0, pending=new Map(), modalSave=null, draft=null;
let matrixDraft=null, matrixPreview='', reviewData=null, reviewTab='findings', mapBox=null, mapStamp='', nativePoll=null;
const specs=()=>new Map(state.specs.map(x=>[x.key,x]));
const rule=()=>state?.rules.find(r=>r.index===selected);
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),4200);}
function call(method,args={}){
  return new Promise((resolve,reject)=>{
    if(!window.wayricad){reject(new Error('Native bridge unavailable. Open this page through WayriCAD.'));return;}
    const id=++nextId;pending.set(id,{resolve,reject});window.wayricad.postMessage(JSON.stringify({id,method,args}));
  });
}
window.studio={
  receive(id,result){const entry=pending.get(id);if(!entry)return;pending.delete(id);result.ok?entry.resolve(result.value):entry.reject(new Error(result.error));},
  async connect(){try{await refresh();}catch(error){$('#main').textContent=error.message;}},
  refresh:()=>refresh(),
};
async function refresh(){const fresh=await call('snapshot');const changed=state?.revision!==fresh.revision;state=fresh;if(selected===null||!rule())selected=state.rules.at(-1)?.index??null;if(changed){inspection=null;reviewData=null;objectA=null;objectB=null;}render();if(view==='workspace')await inspect();}
async function edit(method,args={}){document.body.classList.add('busy');try{state=await call(method,{...args,revision:state.revision});inspection=null;reviewData=null;if(!rule())selected=state.rules.at(-1)?.index??null;render();if(view==='workspace')await inspect();toast('Change staged · source files untouched');}finally{document.body.classList.remove('busy');}}
const navItems=[['workspace','▦','Constraint worksheet'],['matrix','▧','Clearance matrices'],['netclasses','◫','Netclasses & settings'],['sets','◇','Constraint sets'],['review','⇄','Review & export'],['tools','⌘','Engineering tools']];
function nav(){ $('#nav').innerHTML=navItems.map(([id,icon,title])=>`<button class="nav ${view===id?'active':''}" data-view="${id}"><span class="symbol">${icon}</span>${title}${id==='review'&&state.summary.errors?`<span class="badge-count">${state.summary.errors}</span>`:''}</button>`).join('')+'<div class="nav-divider"></div><button class="nav" data-action="help"><span class="symbol">?</span>Reference & help</button>'; }
function head(eyebrow,title,description,actions=''){return `<div class="page-head"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p>${description}</p></div><div class="row">${actions}</div></div>`;}
function metrics(){const s=state.summary;return `<div class="metrics">${[[s.enabled,'Enabled rules',`${s.rules} total · ordered by priority`,'good'],[s.errors,'Local errors','Review before export',s.errors?'error':''],[s.warnings,'Warnings','Intent & overlap checks',s.warnings?'warn':''],[s.changed.length,'Changed files',state.dirty?'Unexported workspace edits':'Compared with saved source','']].map(([n,title,note,c])=>`<div class="metric ${c}"><b>${n}</b><div><span>${title}</span><span class="mini">${note}</span></div></div>`).join('')}</div>`;}
function render(){
  if(!state)return;nav();$('#project-name').textContent=state.name;$('#project-path').textContent=state.board||'Open a saved KiCad board to inspect its constraints';
  $('#save-status').textContent=state.dirty?'Unexported changes':'Saved snapshot';$('#save-status').className='pill '+(state.dirty?'warn':'good');
  $('#main').innerHTML=({workspace:workspacePage,matrix:matrixPage,netclasses:netclassesPage,sets:setsPage,review:reviewPage,tools:toolsPage,routing:routingPage}[view])();
  if(view==='workspace'){drawMap();renderInspector();}
  if(view==='review'&&!reviewData)loadReview();
}
function scopeNav(){return `<div class="panel scope-nav"><h3>DESIGN SCOPE</h3><button data-scope="all" class="${scope[0]==='all'?'active':''}">All rules <span class="count">${state.rules.length}</span></button>${[['component','Components',state.components],['netclass','Netclasses',state.classes.map(c=>c.name)],['net','Nets',state.nets],['area','Rule areas',state.regions.map(a=>a.name)],['category','Domains',[...new Set(state.specs.map(s=>s.category))]]].map(([kind,label,names])=>`<details ${['component','netclass','area'].includes(kind)?'open':''}><summary>${label} <span class="count">${names.length}</span></summary><div class="scope-scroll">${names.map(name=>`<button data-scope="${kind}" data-name="${esc(name)}" class="${scope[0]===kind&&scope[1]===name?'active':''}">${esc(name)}</button>`).join('')||'<small>None in this snapshot</small>'}</div></details>`).join('')}<div class="notice">Scope filters show declared intent. Use the inspector for item matching.</div></div>`;}
function visibleRows(){const out=[];for(const r of [...state.rules].reverse()){
  if(!includeDisabled&&!r.enabled)continue;
  for(const [ci,c] of r.constraints.entries()){
    const spec=specs().get(c.kind);if(search&&!`${r.name} ${r.condition} ${c.kind} ${spec?.label}`.toLowerCase().includes(search.toLowerCase()))continue;
    if(scope[0]==='category'&&spec?.category!==scope[1])continue;
    if(!['all','category'].includes(scope[0])&&!`${r.name} ${r.condition}`.includes(scope[1]))continue;
    out.push([r,c,ci,spec]);
  }}return out;
}
function worksheet(){const rows=visibleRows();return `<div class="panel"><div class="toolbar"><input id="search" aria-label="Search rules and constraints" placeholder="Search rules, constraints or scope…" value="${esc(search)}"><label class="check"><input id="include-disabled" type="checkbox" ${includeDisabled?'checked':''}>Disabled</label><button data-action="undo" title="Undo staged edit">↶</button><button data-action="redo" title="Redo staged edit">↷</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th>ON</th><th>RULE / CONSTRAINT</th><th>MINIMUM</th><th>PREFERRED</th><th>MAXIMUM</th><th>LAYER</th></tr></thead><tbody>${rows.map(([r,c,ci,spec])=>`<tr data-rule="${r.index}" data-clause="${ci}" class="${selected===r.index&&selectedClause===ci?'selected':''} ${r.enabled?'':'disabled'}"><td><input aria-label="Enable ${esc(r.name)}" type="checkbox" data-toggle="${r.index}" ${r.enabled?'checked':''}></td><td><strong>${esc(r.name)}</strong><small>${esc(spec?.label||c.kind)} · #${state.rules.length-r.index}</small></td>${['min','opt','max'].map(field=>`<td>${spec?.fields.includes(field)?`<input class="cell-input" aria-label="${field} for ${esc(r.name)} ${esc(c.kind)}" data-value="${field}" data-rule="${r.index}" data-clause="${ci}" value="${esc(c.values[field]||'')}" placeholder="inherit">`:'<span class="muted">—</span>'}</td>`).join('')}<td><span class="pill">${esc(r.layer||'Any')}</span></td></tr>`).join('')||'<tr><td colspan="6" class="empty">No constraints in this scope. Create a rule or change the filter.</td></tr>'}</tbody></table></div><div class="table-foot"><span>${rows.length} constraint rows · blank = inherited</span><span class="spacer"></span><button class="small" data-action="move-up" ${rule()?'':'disabled'}>↑ Priority</button><button class="small" data-action="move-down" ${rule()?'':'disabled'}>↓</button><button class="small" data-action="duplicate" ${rule()?'':'disabled'}>Duplicate</button></div></div>`;}
function workspacePage(){return head('CONSTRAINT INTELLIGENCE','Constraint worksheet','Design intent, scope and native rules in one workspace.',`<button data-action="protocols">Protocol presets</button><button data-action="bga">BGA exception</button><button data-action="new-rule" class="primary">+ New rule</button>`)+metrics()+`<div class="workbench">${scopeNav()}<div>${worksheet()}<div class="panel map-panel"><div class="map-toolbar"><h3>Layout scope</h3><div class="legend"><span><i class="dot"></i>Match</span><span><i class="dot unknown"></i>Unknown</span><span><i class="dot unmatched"></i>No match</span></div><button data-action="fit" class="small">Fit</button><select id="map-layer" aria-label="Preview layer"><option value="">All layers</option>${state.layers.filter(l=>l.endsWith('.Cu')).map(l=>`<option>${esc(l)}</option>`).join('')}</select></div><div class="map-wrap"><svg id="board-map" aria-label="Interactive saved board scope map"></svg></div><div class="map-note" id="map-note">Wheel to zoom · drag to pan · click an item to inspect. Saved geometry; scope matches are not DRC results.</div></div></div><aside class="panel inspector"><div class="panel-head"><h3>CONTEXT & EXPLANATION</h3><span class="pill good">Staged</span></div><div class="panel-body" id="inspector"></div></aside></div>`;}
async function inspect(){if(selected===null)return;const epoch=++matchEpoch;try{const result=await call('inspect',{rule:selected,a:objectA,b:objectB,kind:rule()?.constraints[selectedClause]?.kind});if(epoch!==matchEpoch)return;inspection=result;if(view==='workspace'){drawMap();renderInspector();}}catch(error){toast(error.message);}}
function itemOptions(value){return '<option value="">Choose item…</option>'+state.items.map(i=>`<option value="${i.index}" ${i.index===value?'selected':''}>${esc(i.label)}</option>`).join('');}
function renderInspector(){const host=$('#inspector');if(!host)return;const r=rule();if(!r){host.innerHTML='<div class="empty">Select or create a rule to inspect its scope.</div>';return;}
 const match=inspection?.matches||[], yes=match.filter(m=>m.value===true).length,unknown=match.filter(m=>m.value===null).length;
 const issues=state.issues.filter(i=>i.rule===r.name),trace=inspection?.trace;
 host.innerHTML=`<section><div class="rule-title">${esc(r.name)}</div><div class="row"><span class="pill">Priority ${state.rules.length-r.index}</span><span class="pill ${r.severity==='warning'?'warn':''}">${esc(r.severity||'inherit')}</span></div><div class="code-block"><code>${esc(r.condition||'All objects')}</code></div><div class="row"><button data-action="edit-rule" class="small">Edit rule</button><button data-action="scope-builder" class="small">Build scope</button><button data-action="delete" class="small danger">Delete</button></div><div class="section-label">CONDITION MATCHING</div><div class="notice">${inspection?`<b>${yes}</b> matches · <b>${unknown}</b> need native evaluation`:'Evaluating saved items…'}<br><small>Geometry and pair applicability remain separate.</small></div>${objectA!==null?`<small>${esc(state.items[objectA]?.label)}</small><div class="notice warn">${esc(match.find(m=>m.index===objectA)?.reasons.join('; ')||'Condition evaluated on the saved object.')}</div>`:''}${issues.map(i=>`<div class="finding ${esc(i.severity)}"><strong>${esc(i.severity.toUpperCase())}</strong>${esc(i.message)}</div>`).join('')}</section><section><div class="section-label">RULE RESOLUTION · OFFLINE SUBSET</div><label>Object A<select id="object-a">${itemOptions(objectA)}</select></label><label>Object B · pair constraints<select id="object-b">${itemOptions(objectB)}</select></label><p class="muted" style="font-size:10px">Choose two objects to evaluate A/B spacing. Unknown rules never become a false pass.</p><div id="priority-trace">${trace?`<div class="notice ${trace.indeterminate?'warn':''}">${trace.indeterminate?'Higher-priority unknowns affect this result.':'Offline candidates only; verify native resolution.'}</div>${trace.rows.map(row=>`<div class="trace-row"><b>${esc(row.rule)}</b><span class="pill ${row.match===true?'good':row.match===null?'warn':''}">${esc(row.status)}</span><small>${esc(row.reasons.join('; '))}</small></div>`).join('')}`:'<small>Choose object A to trace matching rules in priority order.</small>'}</div><div class="section-label">PRESERVED CAPABILITIES</div><button data-native="workbench" class="small">Full worksheet & bulk tools ↗</button></section>`;
}
function drawMap(){const svg=$('#board-map');if(!svg)return;const layer=$('#map-layer')?.value||'';const items=state.items.filter(i=>!layer||i.layers.includes(layer));let points=items.flatMap(i=>i.points).concat(state.regions.flatMap(r=>r.points));if(!points.length){svg.innerHTML='<text x="25" y="40" fill="#abc5d0">Open a saved board to view geometry.</text>';return;}
 const bounds=points.reduce((b,p)=>[Math.min(b[0],p[0]),Math.max(b[1],p[0]),Math.min(b[2],p[1]),Math.max(b[3],p[1])],[Infinity,-Infinity,Infinity,-Infinity]);const [xmin,xmax,ymin,ymax]=bounds;let w=Math.max(2,xmax-xmin),h=Math.max(2,ymax-ymin),pad=Math.max(w,h)*.15;
 const stamp=state.board+layer+JSON.stringify([xmin,xmax,ymin,ymax]);if(!mapBox||mapStamp!==stamp){mapBox=[xmin-pad,ymin-pad,w+pad*2,h+pad*2];mapStamp=stamp;}
 const scale=Math.max(w,h)/100, color=new Map((inspection?.matches||[]).map(m=>[m.index,m.value===true?'#69d6ba':m.value===false?'#526e80':'#edbe79']));
 let shapes=state.regions.map(r=>`<g><polygon points="${r.points.map(p=>p.join(',')).join(' ')}" fill="#8c91de0c" stroke="#9e9fd5" stroke-width="${scale*.45}" stroke-dasharray="${scale*1.6} ${scale}"/><text x="${r.points[0]?.[0]}" y="${(r.points[0]?.[1]||0)-scale*2}" fill="#c0c1e9" font-size="${scale*2.2}">${esc(r.name)}</text></g>`).join('');
 for(const item of items){const p=item.points;if(!p.length)continue;const c=color.get(item.index)||'#78b8c3', picked=item.index===objectA||item.index===objectB;let shape='';const stroke=picked?'#fff':c,sw=picked?scale*1.4:scale*.5;
 if(item.kind==='Footprint')shape=`<circle cx="${p[0][0]}" cy="${p[0][1]}" r="${scale}" fill="none" stroke="${stroke}" stroke-width="${scale*.35}"/><text x="${p[0][0]+scale*1.4}" y="${p[0][1]-scale}" fill="#dae9ef" font-size="${scale*2.3}">${esc(item.reference)}</text>`;
 else if(item.geometry==='capsule')shape=`<line x1="${p[0][0]}" y1="${p[0][1]}" x2="${p[1][0]}" y2="${p[1][1]}" stroke="${stroke}" stroke-width="${Math.max(item.radius*2,sw)}" stroke-linecap="round"/>`;
 else if(item.geometry==='circle')shape=`<circle cx="${p[0][0]}" cy="${p[0][1]}" r="${Math.max(item.radius,scale*.7)}" fill="${c}" stroke="${stroke}" stroke-width="${sw}"/>`;
 else if(['polygon','envelope'].includes(item.geometry))shape=`<polygon points="${p.map(v=>v.join(',')).join(' ')}" fill="${c}" fill-opacity=".65" stroke="${stroke}" stroke-width="${sw}"/>`;
 else shape=p.map(v=>`<circle cx="${v[0]}" cy="${v[1]}" r="${scale}" fill="none" stroke="${stroke}" stroke-width="${sw}"/>`).join('');
 shapes+=`<g class="item" data-item="${item.index}"><title>${esc(item.label)}</title>${shape}</g>`;
 }svg.setAttribute('viewBox',mapBox.join(' '));svg.innerHTML=shapes;
 if(state.omitted_regions.length)$('#map-note').textContent=`${state.omitted_regions.length} complex region outlines omitted. Use native geometry inspection. Wheel zoom · drag pan · click object A.`;
 svg.onwheel=e=>{e.preventDefault();const f=e.deltaY>0?1.15:1/1.15;mapBox=[mapBox[0]+mapBox[2]*(1-f)/2,mapBox[1]+mapBox[3]*(1-f)/2,mapBox[2]*f,mapBox[3]*f];svg.setAttribute('viewBox',mapBox.join(' '));};
 let drag=null;svg.onpointerdown=e=>{drag={x:e.clientX,y:e.clientY,box:[...mapBox],target:e.target.closest('[data-item]')};svg.setPointerCapture(e.pointerId);};svg.onpointermove=e=>{if(!drag)return;const k=Math.max(mapBox[2]/svg.clientWidth,mapBox[3]/svg.clientHeight);mapBox=[drag.box[0]-(e.clientX-drag.x)*k,drag.box[1]-(e.clientY-drag.y)*k,...drag.box.slice(2)];svg.setAttribute('viewBox',mapBox.join(' '));};svg.onpointerup=e=>{if(drag&&Math.hypot(e.clientX-drag.x,e.clientY-drag.y)<4&&drag.target){objectA=Number(drag.target.dataset.item);inspect();}drag=null;if(svg.hasPointerCapture(e.pointerId))svg.releasePointerCapture(e.pointerId);};
}
function matrixPage(){if(!matrixDraft){const labels=state.classes.map(c=>c.name);matrixDraft={group:'Main',kind:'clearance',scope:'netclass',labels:labels.length?labels:['Default','HighSpeed'],cells:[],layer:'',region:''};}
 return head('PAIRWISE DESIGN INTENT','Clearance matrices','Edit symmetric spacing rules. Blank cells inherit; values never silently become zero.',`<button data-native="matrix_page">CSV & advanced matrix</button><button data-action="stage-matrix" class="primary">Stage matrix</button>`)+`<div class="panel"><div class="panel-body"><div class="form-grid"><label>Matrix group<input id="matrix-group" value="${esc(matrixDraft.group)}"></label><label>Constraint<select id="matrix-kind">${['clearance','physical_clearance','creepage','courtyard_clearance','hole_clearance','physical_hole_clearance','hole_to_hole','silk_clearance'].map(k=>`<option value="${k}" ${k===matrixDraft.kind?'selected':''}>${esc(specs().get(k)?.label||k)}</option>`).join('')}</select></label><label>Scope<select id="matrix-scope">${['netclass','net','component_class','type'].map(k=>`<option ${k===matrixDraft.scope?'selected':''}>${k}</option>`).join('')}</select></label><label>Labels · one per line<textarea id="matrix-labels">${esc(matrixDraft.labels.join('\n'))}</textarea></label><label>Layer<input id="matrix-layer" value="${esc(matrixDraft.layer)}" placeholder="Any layer"></label><label>Optional named region<input id="matrix-region" value="${esc(matrixDraft.region)}" placeholder="No region restriction"></label></div><div class="row" style="margin-top:14px"><button data-action="resize-matrix">Update labels</button><button data-action="preview-matrix">Preview generated rules</button><small>Use dimensions such as 0.2mm or 8mil. Mirrored cells stay synchronized.</small></div></div><div class="table-wrap tall"><table class="data-table matrix-table"><thead><tr><th>MINIMUM SPACING</th>${matrixDraft.labels.map(l=>`<th>${esc(l)}</th>`).join('')}</tr></thead><tbody>${matrixDraft.labels.map((l,i)=>`<tr><th>${esc(l)}</th>${matrixDraft.labels.map((_,j)=>{const value=matrixDraft.cells.find(c=>c.i===Math.min(i,j)&&c.j===Math.max(i,j))?.value||'';return `<td class="${value?'':'inherit'}"><input aria-label="${esc(l)} to ${esc(matrixDraft.labels[j])}" data-matrix-i="${i}" data-matrix-j="${j}" value="${esc(value)}" placeholder="inherit"></td>`;}).join('')}</tr>`).join('')}</tbody></table></div></div>${matrixPreview?`<div class="panel" style="margin-top:16px"><div class="panel-head"><h3>Generated rules · preview only</h3></div><pre class="diff">${esc(matrixPreview)}</pre></div>`:''}`;
}
function readMatrix(){matrixDraft.group=$('#matrix-group').value.trim();matrixDraft.kind=$('#matrix-kind').value;matrixDraft.scope=$('#matrix-scope').value;matrixDraft.layer=$('#matrix-layer').value;matrixDraft.region=$('#matrix-region').value;return matrixDraft;}
function netclassesPage(){const fields=['clearance','track_width','via_diameter','via_drill','diff_pair_width','diff_pair_gap'];return head('NATIVE PROJECT SETTINGS','Netclasses & settings','Edit native dimensions while preserving inherited values and unknown project fields.',`<button data-native="netclass_page">Classes & assignments editor</button><button data-native="settings_page">Full board settings</button>`)+`<div class="panel"><div class="panel-head"><h3>Netclass dimensions</h3><small>Millimetres · blank or null = inherited</small></div><div class="table-wrap tall"><table class="data-table"><thead><tr><th>NETCLASS</th>${fields.map(f=>`<th>${esc(f.replaceAll('_',' ').toUpperCase())}</th>`).join('')}</tr></thead><tbody>${state.classes.map((c,i)=>`<tr><td><strong>${esc(c.name)}</strong></td>${fields.map(f=>`<td><input class="cell-input" aria-label="${esc(c.name+' '+f)}" data-class="${i}" data-key="${f}" value="${esc(c[f]??'')}" placeholder="inherit"></td>`).join('')}</tr>`).join('')||'<tr><td colspan="7" class="empty">No netclass data in the saved project.</td></tr>'}</tbody></table></div></div><div class="two-col" style="margin-top:18px"><div class="panel"><div class="panel-head"><h3>Pattern assignments</h3><button class="small" data-native="netclass_page">Manage</button></div><div class="panel-body">${state.patterns.map(p=>`<p><span class="pill good">${esc(p.netclass)}</span> <code>${esc(p.pattern)}</code></p>`).join('')||'<small>No saved patterns.</small>'}</div></div><div class="panel"><div class="panel-head"><h3>Manufacturing floors</h3><small>Separate from working constraints</small></div><div class="panel-body stack">${state.settings.filter(s=>s.path.join('.').startsWith('board.design_settings.rules.')).map((s)=>`<label>${esc(s.path.at(-1).replaceAll('_',' '))}<input data-setting="${esc(JSON.stringify(s.path))}" value="${esc(s.value)}"></label>`).join('')||'<small>No board-floor settings in this saved project.</small>'}</div></div></div>`;}
function setsPage(){return head('REUSABLE ENGINEERING INTENT','Constraint sets','Parameterised rule sets bound to this project. Values come from your design requirements.',`<button data-native="profile_panel">Capture, import & timing tools</button>`)+`<div class="three-col">${state.profiles.map(p=>`<article class="panel tool-card"><div class="eyebrow">${esc(p.id)}</div><h2>${esc(p.name)}</h2><p>${esc(p.description)}</p><small>${p.rules.length} rule templates · ${Object.keys(p.parameters).length} parameters</small><button data-profile="${esc(p.id)}">Configure & stage →</button></article>`).join('')}</div>`;}
function toolsPage(){const tools=[['BGA / component exceptions','Native courtyard contours, scoped clearances, routing dimensions and managed regions.','bga'],['Signal paths & field solver','Declare pass-through connections, inspect timing budgets and run the 2-D line solver.','advanced_panel'],['Team catalogue & signed reviews','Digest-pinned shared sets, local trust policy and content-bound review decisions.','advanced_panel'],['DRC evidence','Import native reports, inspect violations and review their recorded geometry.','reports_panel'],['Bulk worksheet tools','Multi-row fill, clipboard data, CSV, A/B priority tracing and the complete original worksheet.','workbench'],['Detailed rule authoring','All 34 constraint forms, grouped conditions, preserved syntax and exact native rule text.','rule_page']];return head('FULL CONSTRAINT STUDIO','Engineering tools','The original specialist workflows share this workspace, staged state and undo history.')+`<div class="three-col">${tools.map(([title,desc,page])=>`<article class="panel tool-card"><div class="eyebrow">SPECIALIST WORKSPACE</div><h2>${title}</h2><p>${desc}</p><button ${page==='bga'?'data-action="bga"':`data-native="${page}"`}>Open workspace ↗</button></article>`).join('')}</div><div class="notice">Return from a specialist workspace with “Back to visual workspace”. Changes are retained and the worksheet refreshes.</div>`;}
function reviewPage(){return head('INSPECT BEFORE APPLY','Review & export','Compare staged files, resolve local findings, then validate a separate exported copy.',`<button data-action="native-drc" ${state.last_export?'':'disabled'}>Run native DRC</button><button data-action="export" class="primary">Export review ↗</button>`)+metrics()+`<div class="row"><span class="pill good">1 · Saved source</span><span>→</span><span class="pill good">2 · Staged workspace</span><span>→</span><span class="pill ${state.last_export?'good':''}">3 · Review export</span><span>→</span><span class="pill">4 · Native DRC</span><span>→</span><span class="pill">5 · Offline apply</span></div><div class="file-list">${state.summary.changed.map(ext=>`<span class="pill warn">${esc(ext)}</span>`).join('')||'<small>No file changes</small>'}</div><div class="tabs">${[['findings','Local findings'],['diff','File diff'],['rules','Native rules'],['native','DRC report']].map(([id,label])=>`<button class="${reviewTab===id?'active':''}" data-review-tab="${id}">${label}</button>`).join('')}</div>${reviewTab==='findings'?`<div class="findings">${state.issues.map(i=>`<div class="finding ${esc(i.severity)}" data-issue-rule="${esc(i.rule)}"><strong>${esc(i.severity.toUpperCase())} · ${esc(i.rule)}</strong><p>${esc(i.message)}</p></div>`).join('')||'<div class="notice">No local lint findings. Native syntax, geometry and fabrication review are still required.</div>'}</div>`:`<div class="panel"><div class="panel-head"><h3>${reviewTab==='diff'?'Changes against saved source':reviewTab==='rules'?'Exact generated native rules':'Native KiCad result'}</h3>${reviewTab==='rules'?'<button class="small" data-action="copy-rules">Copy rules</button>':''}</div><div class="diff">${renderDiff(reviewTab==='native'?(state.native_report||'Export a review and run native DRC.'):reviewData?.[reviewTab]||'Loading…')}</div></div>`}<div class="notice">Export uses a separate folder. Close source-project editors before using the exported Apply Review helper; it checks fingerprints and creates backups.</div>${state.worker_busy?'<p class="muted">Native DRC is running…</p>':''}`;}
function renderDiff(text){return String(text).split('\n').map(line=>`<span class="${line.startsWith('+')?'add':line.startsWith('-')?'remove':''}">${esc(line)}</span>`).join('\n');}
async function loadReview(){try{reviewData=await call('review');if(view==='review')render();}catch(error){toast(error.message);}}
function showDialog(title,body,save,label='Stage changes'){ $('#dialog-title').textContent=title;$('#dialog-body').innerHTML=body;$('#dialog-error').textContent='';$('#dialog-save').textContent=label;modalSave=save;$('#dialog').showModal(); }
function clauseHtml(c,ci){const s=specs().get(c.kind);return `<div class="clause" data-clause-editor="${ci}"><div class="clause-head"><select data-kind="${ci}">${state.specs.map(s=>`<option value="${s.key}" ${s.key===c.kind?'selected':''}>${esc(s.label)}</option>`).join('')}${s?'':`<option selected value="${esc(c.kind)}">${esc(c.kind)} · preserved</option>`}</select><button type="button" class="small danger" data-remove-clause="${ci}">Remove</button></div><div class="clause-values">${(s?.fields||Object.keys(c.values)).map(f=>`<label>${{min:'Minimum',opt:'Preferred',max:'Maximum'}[f]}<input data-clause-field="${f}" value="${esc(c.values[f]||'')}" placeholder="unspecified"></label>`).join('')}</div>${s?.choices.length?`<label>Argument<input data-argument value="${esc(c.argument||'')}" list="choices-${ci}"><datalist id="choices-${ci}">${s.choices.map(v=>`<option value="${esc(v)}">`).join('')}</datalist></label>`:c.kind==='assertion'||c.argument?`<label>Argument / assertion<textarea data-argument>${esc(c.argument||'')}</textarea></label>`:''}${c.kind==='skew'?`<label class="check"><input data-pair type="checkbox" ${c.within_diff_pairs?'checked':''}>Within each differential pair</label>`:''}<small>${esc(s?.help||'Preserved native syntax is retained on edits.')} ${esc(s?.unit||'')}</small></div>`;}
function readRuleDraft(){const form=$('#dialog-body');for(const field of ['name','condition','layer','severity','notes'])draft[field]=$(`[name="${field}"]`,form).value;draft.enabled=$('[name="enabled"]',form).checked;$$('[data-clause-editor]',form).forEach(el=>{const c=draft.constraints[Number(el.dataset.clauseEditor)];c.values={};$$('[data-clause-field]',el).forEach(input=>{c.values[input.dataset.clauseField]=input.value;});c.argument=$('[data-argument]',el)?.value||'';c.within_diff_pairs=$('[data-pair]',el)?.checked||false;});}
function ruleForm(){return `<div class="form-grid"><label class="full">Rule name<input name="name" required value="${esc(draft.name)}"></label><label>Layer<input name="layer" value="${esc(draft.layer)}" placeholder="Any" list="layers"><datalist id="layers">${state.layers.map(l=>`<option>${esc(l)}</option>`).join('')}</datalist></label><label>Severity<select name="severity">${['',...state.severities].map(v=>`<option value="${v}" ${v===draft.severity?'selected':''}>${v||'Inherit'}</option>`).join('')}</select></label><label class="full">Condition · A/B scope<textarea name="condition" class="mono">${esc(draft.condition)}</textarea></label><div class="row full"><button type="button" data-action="modal-scope" class="small">Build condition visually…</button><label class="check"><input name="enabled" type="checkbox" ${draft.enabled?'checked':''}>Enabled</label></div></div><div class="section-label">CONSTRAINT CLAUSES</div><div id="clauses">${draft.constraints.map(clauseHtml).join('')}</div><button type="button" data-action="add-clause" class="small">+ Add constraint</button><label style="margin-top:14px">Notes / rationale<textarea name="notes">${esc(draft.notes)}</textarea></label>`;}
function openRule(isNew=false){const r=isNew?null:rule();if(!isNew&&!r)return;draft=r?structuredClone(r):{name:'New scoped rule',condition:'',layer:'',severity:'error',enabled:true,notes:'',constraints:[{kind:'track_width',values:{},argument:''}]};draft.constraints.forEach((c,i)=>{if(r)c.index=i;});const currentRevision=state.revision;showDialog(isNew?'New scoped rule':'Edit rule',ruleForm(),async()=>{readRuleDraft();if(currentRevision!==state.revision)throw new Error('Workspace changed while editing. Reopen the rule to merge your changes.');await edit('save_rule',{index:r?.index??null,rule:draft});});}
function openProfile(id){const p=state.profiles.find(p=>p.id===id);showDialog(p.name,`<p class="muted">${esc(p.description)}</p><div class="param-grid"><label>Instance name<input id="profile-instance" required value="${esc(p.name)}"></label>${Object.entries(p.parameters).map(([key,value])=>`<label>${esc(value.label)} <small>${esc(value.type)}</small><input data-param="${esc(key)}" required></label>`).join('')}</div>${Object.keys(p.floors||{}).length?'<div class="notice warn"><label class="check"><input id="apply-floors" type="checkbox">Also stage the explicitly entered manufacturing floors</label></div>':''}`,async()=>{const bindings={};$$('[data-param]').forEach(input=>bindings[input.dataset.param]=input.value);await edit('profile',{id,bindings,instance:$('#profile-instance').value,apply_floors:$('#apply-floors')?.checked||false});});}
async function action(name){
 if(name==='theme'){document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';return;}
 if(name==='new-rule'||name==='edit-rule'){openRule(name==='new-rule');return;}
 if(name==='fit'){mapBox=null;drawMap();return;}
 if(name==='duplicate'||name==='delete'){if(!rule())return;if(name==='delete'){showDialog('Remove staged rule',`<p>Remove <strong>${esc(rule().name)}</strong> from the staged workspace? You can undo this action.</p>`,()=>edit('delete',{index:selected}),'Remove rule');return;}await edit(name,{index:selected});return;}
 if(name.startsWith('move-')){if(rule()){const delta=name==='move-up'?1:-1;const target=Math.max(0,Math.min(state.rules.length-1,selected+delta));await edit('move',{index:selected,delta});selected=target;render();await inspect();}return;}
 if(name==='add-clause'){readRuleDraft();draft.constraints.push({kind:'clearance',values:{},argument:''});$('#dialog-body').innerHTML=ruleForm();return;}
 if(name==='modal-scope'){readRuleDraft();const result=await call('condition',{expression:draft.condition});if(result!==null){draft.condition=result;$('#dialog-body').innerHTML=ruleForm();}return;}
 if(name==='scope-builder'){if(!rule())return;openRule();await action('modal-scope');return;}
 if(['resize-matrix','preview-matrix','stage-matrix'].includes(name)){readMatrix();if(name==='resize-matrix'){const labels=$('#matrix-labels').value.split('\n').map(s=>s.trim()).filter(Boolean);if(labels.length>40)throw new Error('Use at most 40 matrix labels.');const old=matrixDraft;matrixDraft={...old,labels,cells:[]};for(const c of old.cells){const i=labels.indexOf(old.labels[c.i]),j=labels.indexOf(old.labels[c.j]);if(i>=0&&j>=0)matrixDraft.cells.push({i:Math.min(i,j),j:Math.max(i,j),value:c.value});}matrixPreview='';render();return;}matrixPreview=await call('matrix_preview',matrixDraft);if(name==='stage-matrix')await edit('matrix',matrixDraft);else render();return;}
 if(name==='native-drc'){await call('native_drc');await refresh();reviewTab='native';view='review';render();clearInterval(nativePoll);nativePoll=setInterval(async()=>{await refresh();if(!state.worker_busy)clearInterval(nativePoll);},1200);return;}
 if(name==='export'){await call('export');await refresh();return;}
 if(['open','undo','redo','help','bga','protocols','copy-rules'].includes(name)){await call(name);await refresh();return;}
}
document.addEventListener('click',async e=>{const button=e.target.closest('button');try{
 if(button?.dataset.view){view=button.dataset.view;render();if(view==='workspace')await inspect();return;}
 if(button?.dataset.action){await action(button.dataset.action);return;}
 if(button?.dataset.native){await call('native',{page:button.dataset.native});return;}
 if(button?.dataset.profile){openProfile(button.dataset.profile);return;}
 if(button?.dataset.scope){scope=[button.dataset.scope,button.dataset.name||''];render();return;}
 if(button?.dataset.reviewTab){reviewTab=button.dataset.reviewTab;render();return;}
 if(button?.dataset.removeClause!==undefined){readRuleDraft();draft.constraints.splice(Number(button.dataset.removeClause),1);$('#dialog-body').innerHTML=ruleForm();return;}
 const issue=e.target.closest('[data-issue-rule]');if(issue){const r=state.rules.find(r=>r.name===issue.dataset.issueRule);if(r){selected=r.index;view='workspace';render();await inspect();}return;}
 const row=e.target.closest('tr[data-rule]');if(row&&!e.target.matches('input,button,select')){selected=Number(row.dataset.rule);selectedClause=Number(row.dataset.clause);inspection=null;render();await inspect();}
 }catch(error){toast(error.message);}});
document.addEventListener('dblclick',e=>{if(e.target.matches('input'))return;const row=e.target.closest('tr[data-rule]');if(row){selected=Number(row.dataset.rule);openRule();}});
document.addEventListener('input',e=>{if(e.target.id==='search'){search=e.target.value;const position=e.target.selectionStart;render();const input=$('#search');input.focus();input.setSelectionRange(position,position);}});
document.addEventListener('change',async e=>{const el=e.target;try{
 if(el.dataset.value){await edit('set_value',{rule:Number(el.dataset.rule),constraint:Number(el.dataset.clause),field:el.dataset.value,value:el.value});}
 else if(el.dataset.toggle!==undefined){await edit('toggle',{index:Number(el.dataset.toggle)});}
 else if(el.id==='include-disabled'){includeDisabled=el.checked;render();}
 else if(el.id==='object-a'||el.id==='object-b'){const value=el.value===''?null:Number(el.value);if(el.id==='object-a')objectA=value;else objectB=value;await inspect();}
 else if(el.id==='map-layer'){drawMap();}
 else if(el.dataset.kind!==undefined){readRuleDraft();const i=Number(el.dataset.kind);draft.constraints[i]={index:draft.constraints[i].index,kind:el.value,values:{},argument:''};$('#dialog-body').innerHTML=ruleForm();}
 else if(el.dataset.matrixI!==undefined){readMatrix();const i=Math.min(Number(el.dataset.matrixI),Number(el.dataset.matrixJ)),j=Math.max(Number(el.dataset.matrixI),Number(el.dataset.matrixJ));matrixDraft.cells=matrixDraft.cells.filter(c=>c.i!==i||c.j!==j);matrixDraft.cells.push({i,j,value:el.value});matrixPreview='';render();}
 else if(el.dataset.class!==undefined){await edit('netclass',{index:Number(el.dataset.class),key:el.dataset.key,value:el.value});}
 else if(el.dataset.setting){await edit('setting',{path:JSON.parse(el.dataset.setting),value:el.value});}
 }catch(error){toast(error.message);render();}});
$('#dialog-form').onsubmit=async e=>{e.preventDefault();$('#dialog-save').disabled=true;try{await modalSave();$('#dialog').close();}catch(error){$('#dialog-error').textContent=error.message;}finally{$('#dialog-save').disabled=false;}};
$('#close-dialog').onclick=$('#cancel-dialog').onclick=()=>$('#dialog').close();
document.addEventListener('keydown',async e=>{if(e.key==='F1'){e.preventDefault();await action('help');return;}if(e.target.matches('input,textarea,select')||$('#dialog').open)return;if(e.key==='/'){e.preventDefault();$('#search')?.focus();}if(e.ctrlKey&&['z','y'].includes(e.key.toLowerCase())){e.preventDefault();await action(e.key.toLowerCase()==='z'?'undo':'redo');}});
