'use strict';
// Read-only, unit-aware analytics. Highlight state never becomes an edit selection.
titles.analytics=['Cost, mass & power','Traceable arithmetic, explicit assumptions, and unknowns that stay unknown.'];
S.analytics5={project:null,config:null,dirty:false,report:null,inputKey:'',savedKey:'',tab:'groups'};
S.threshold5=null; S.drill5=null;
const units5=['number','g','mg','ug','kg','W','mW','uW','kW','C','F','K','%','ratio','V','mV','kV','A','mA','uA','mm','cm','m'];
function projectKey5(){return S.data?.project?.path||'';}
function config5(){const a=S.analytics5;if(a.project!==projectKey5()){a.project=projectKey5();a.config=structuredClone(S.data.analytics_settings);a.dirty=false;a.report=null;a.inputKey='';a.savedKey=JSON.stringify(S.data.analytics_settings);S.threshold5=null;S.drill5=null;}else if(!a.dirty&&a.savedKey!==JSON.stringify(S.data.analytics_settings)){a.config=structuredClone(S.data.analytics_settings);a.savedKey=JSON.stringify(S.data.analytics_settings);}return a.config;}
function pretty5(v,digits=6){if(v===null||v===undefined)return 'Unknown';const n=Number(v);if(!Number.isFinite(n))return String(v);if(n!==0&&Math.abs(n)<1e-5)return n.toExponential(4);return n.toLocaleString(undefined,{maximumFractionDigits:digits});}
function select5(key,options,c=config5()){return `<select data-ana="${esc(key)}">${options.map(o=>`<option value="${esc(Array.isArray(o)?o[0]:o)}" ${c[key]===(Array.isArray(o)?o[0]:o)?'selected':''}>${esc(Array.isArray(o)?o[1]:o)}</option>`).join('')}</select>`;}
function input5(key,label,help='',type='text'){const c=config5();return `<label class="ana-field"><span>${esc(label)}</span><input data-ana="${esc(key)}" value="${esc(c[key]??'')}" type="${type}" ${key.endsWith('_field')?'list="analyticsFieldNames"':''}><small>${esc(help)}</small></label>`;}
function option5(key,label,options,help=''){return `<label class="ana-field"><span>${esc(label)}</span>${select5(key,options)}<small>${esc(help)}</small></label>`;}
function metricCard5(label,value,foot){return `<article class="metric"><div class="metric-label">${label}</div><div class="metric-value">${value}</div><div class="metric-foot">${foot}</div></article>`;}
function table5(headers,rows){return `<div class="table-wrap"><table class="data-table ana-table"><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(c=>`<tr>${c.map(v=>`<td>${v}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}">No records in this section.</td></tr>`}</tbody></table></div>`;}
function inspect5(ids,label='Inspect'){return `<button class="small quiet" data-act="analyticsInspect" data-ids="${esc(JSON.stringify(ids))}">${esc(label)}</button>`;}
function pcbInputs5(){
 const p=config5().pcb||{};
 const fields=[['mass_g','Bare PCB mass (g)','Measured/declared override, or leave blank for the estimate below'],['area_mm2','Net laminate area (mm²)','Subtract outline cutouts; no automatic board inference'],['dielectric_mm','Total dielectric thickness (mm)','Exclude copper thickness'],['dielectric_density_g_cm3','Dielectric density (g/cm³)','Enter the actual material density'],['copper_total_mm','Sum of all copper layer thicknesses (mm)','All layers combined'],['copper_coverage_percent','Thickness-weighted copper coverage (%)','0–100; actual coverage is a declared assumption'],['copper_density_g_cm3','Copper density (g/cm³)','Enter the material density'],['unit_cost','PCB quote per board','Enter quote, not a predicted market price'],['setup_cost','One-time PCB setup cost','Explicit 0 when none'],['quote_quantity','PCB quote quantity','Blank uses build quantity'],['currency','PCB quote currency','Three-letter code, e.g. USD'],['source','Quote / material source','Supplier/date or measurement provenance']];
 return `<details><summary>Bare PCB mass and quoted cost</summary><p class="fine">Optional declared inputs. Blank means unknown. Do not count a PCB component twice. Solder, coatings and unrepresented hardware are excluded.</p><div class="ana-grid">${fields.map(([key,title,note])=>`<label class="ana-field"><span>${esc(title)}</span><input data-pcb="${key}" value="${esc(p[key]??'')}"><small>${esc(note)}</small></label>`).join('')}</div></details>`;
}
function renderAnalytics(){
 const c=config5(),r=S.analytics5.report,stale=r&&(r.revision!==S.data.revision||r.variant!==S.variant||S.analytics5.inputKey!==JSON.stringify(c));
 const fields=[...new Set(S.data.rows.flatMap(r=>[...Object.keys(r.fields),...Object.keys(r.raw)]))].sort();
 return `${pcbInputs5()}<div class="notice">Analytics never edits component fields. Pricing uses fitted, BOM-included parts; mass and power use fitted on-board parts. Missing data is not zero. ${S.gridDrafts?.size?'<b>Pending grid edits are not included.</b>':''}</div>
 <section class="panel"><div class="toolbar"><h2 class="grow">Mappings & scenario</h2><button data-act="analyticsRun" class="primary">Run analytics</button><button data-act="analyticsSave">Save settings to workspace</button><button data-act="analyticsAdvanced">Budgets, FX & statistics…</button></div>
 <datalist id="analyticsFieldNames">${fields.map(f=>`<option value="${esc(f)}"></option>`).join('')}</datalist>
 <details class="ana-mapping" ${r?'':'open'}><summary>Input fields, units, population scope and assumptions</summary><div class="ana-form">
 <div class="ana-grid">${input5('scenario_name','Scenario name')}${input5('type_field','Component type field','Blank/missing type falls back to a labelled reference-prefix heuristic.')}${input5('boards','Build quantity','Blank uses project build settings.','number')}${input5('attrition_percent','Purchasing attrition (%)','Blank uses project settings. Never added to installed mass/power.','number')}</div>
 <fieldset><legend>Price mapping <label class="inline"><input type="checkbox" data-ana-metric="pricing" ${c.metrics.includes('pricing')?'checked':''}> Enabled</label></legend><div class="ana-grid">
 ${input5('price_field','Rate / price field','Any component property, including resolved variables.')}${input5('currency_field','Currency field','Blank observations use the chosen default.')}${input5('currency_default','Default currency','Blank uses project currency; enter an explicit code, e.g. INR.')}${input5('price_per','Rate is per N pieces','1 = per component; 100 = price per 100 pieces.','number')}
 ${input5('price_per_field','Optional per-row divisor field','When selected, every priced row needs a positive integer.')}${input5('moq_field','MOQ field')}${input5('multiple_field','Order multiple field')}${input5('quote_date_field','Price observation date field','Old/undated values are arithmetic inputs, not live quotes.')}
 </div></fieldset>
 <fieldset><legend>Installed mass <label class="inline"><input type="checkbox" data-ana-metric="mass" ${c.metrics.includes('mass')?'checked':''}> Enabled</label></legend><div class="ana-grid">
 ${input5('mass_field','Mass per component field')}${option5('mass_unit','Unit for bare numbers',['g','mg','ug','kg'],'Explicit units in cells override this default.')}
 <label class="ana-field ana-span2"><span>Physical scope</span><span><input type="checkbox" data-ana="physical_include_bom_excluded" ${c.physical_include_bom_excluded?'checked':''}> Include fitted on-board items excluded from purchasing BOM</span><small>Unrepresented PCB, solder, enclosure and harness mass are not inferred.</small></label>
 </div></fieldset>
 <fieldset><legend>Operating dissipation <label class="inline"><input type="checkbox" data-ana-metric="thermal" ${c.metrics.includes('thermal')?'checked':''}> Enabled</label></legend><div class="ana-grid">
 ${input5('power_field','Actual dissipation field','Do not map a maximum/rated-power field here.')}${option5('power_unit','Power unit',['W','mW','uW','kW'])}${option5('power_basis','Meaning of entered power',[['average','Already average — no duty multiplier'],['active','Active-state power × duty cycle']])}${input5('duty_percent','Default duty (%)','Used only with active-state power and no duty field.','number')}
 ${input5('duty_field','Optional duty-percent field','A blank mapped duty is unknown, not 100%.')}${input5('rating_field','Optional rated-power field','Independent comparison only; not thermal qualification.')}${input5('temperature_field','Maximum-temperature field')}${option5('temperature_unit','Temperature unit',['C','F','K'])}
 ${input5('temperature_requirement_c','Required operating temperature (°C)','Optional comparison with the supplied maximum rating.','number')}
 </div></fieldset>
 <div class="ana-grid"><label class="ana-field ana-span2"><span>Break down by (one field per line)</span><textarea id="analyticsGroupBy" rows="2">${esc(c.group_by.join('\n'))}</textarea><small>@type, @population, or any exact property name. Multiple fields form a composite breakdown.</small></label><label class="ana-field ana-span2"><span>Analytics query scope</span><input data-ana="query" value="${esc(c.query)}" placeholder='is:fit AND Temp_Max<80'><small>Independent of quick-search/view filters. Typed comparison uses these unit mappings.</small></label></div>
 <div class="row"><span id="analyticsSettingsStatus" class="fine">${S.analytics5.dirty?'Settings changed locally. Run uses these settings; save and Save workspace to persist.':'Saved workspace settings loaded.'}</span><span class="grow"></span><button data-act="analyticsShare">Share settings JSON</button><label class="filebutton small">Import settings JSON<input type="file" id="analyticsConfigImport" accept=".json"></label></div>
 </div></details></section>
 ${r?`${stale?'<div class="notice error"><b>Stale report.</b> Settings, variant or workspace changed. Run again. Exports are recomputed from the current settings.</div>':''}
 <div class="metrics ana-metrics">
 ${metricCard5('Known installed cost / board',Object.entries(r.pricing.currencies).map(([k,v])=>`${esc(k||'Unknown currency')} ${esc(pretty5(v.known_cost_per_board))}`).join('<br>')||'Not priced',`${r.pricing.priced_components} / ${r.pricing.eligible_components} priced components · currencies separate`)}
 ${metricCard5('Known component mass / board',esc(pretty5(r.mass.known_per_board))+' g',`${r.mass.known_components} / ${r.mass.eligible_components} known · excludes unrepresented items`)}
 ${metricCard5('Known dissipation / board',esc(pretty5(r.thermal.known_per_board))+' W',`${r.thermal.known_components} / ${r.thermal.eligible_components} known · not a thermal simulation`)}
 ${metricCard5('Bare PCB mass / quoted cost',esc(pretty5(r.pcb?.mass_g))+' g · '+esc(r.pcb?.currency||'')+' '+esc(pretty5(r.pcb?.expected_unit_cost)),esc(r.pcb?.mass_basis||'Unknown')+' · '+esc(r.pcb?.cost_status||'unknown'))}
 ${metricCard5('Complete component + PCB totals',esc(pretty5(r.pcb?.assembly_mass_g))+' g · '+esc(r.pcb?.currency||'')+' '+esc(pretty5(r.pcb?.assembly_cost_per_board)),esc(r.pcb?.warnings?.join(' ')||'Unknown if component coverage is incomplete or currencies differ'))}
 ${metricCard5('Coverage & scope',String(r.scope.matched_components)+' parts',`${r.issues.length} findings · ${r.scope.type_heuristic_components} heuristic type labels`)}
 </div>
 <section class="panel"><div class="toolbar"><h2 class="grow">${esc(r.config.scenario_name)} · ${esc(r.variant===BASE?'Default assembly':r.variant)}</h2><label>Format <select id="analyticsFormat">${['xlsx','csv','tsv','json','html','txt','ascii','md','zip'].map(x=>`<option>${x}</option>`).join('')}</select></label><label>Table <select id="analyticsTable">${['groups','components','summary','procurement','scenarios','statistics','issues'].map(x=>`<option>${x}</option>`).join('')}</select></label><button data-act="analyticsExport">Download analytics</button><button data-act="analyticsProject">Save reports in project</button></div>
 <p class="ana-caption">Generated ${esc(r.generated_at)} · ${r.scope.pricing_components} pricing eligible / ${r.scope.physical_components} physical eligible. Known subtotals only. Excel/HTML/ZIP include all report sections.</p>
 <div class="ana-tabs" role="group" aria-label="Analytics sections">${[['groups','Type / field breakdown'],['pricing','Cost & Pareto'],['procurement','Procurement'],['scenarios','Build scenarios'],['components','Mass & power table'],['statistics','Statistics'],['issues','Coverage & findings']].map(([key,title])=>`<button class="${S.analytics5.tab===key?'primary':''}" data-act="analyticsTab" data-tab="${key}" aria-pressed="${S.analytics5.tab===key}">${title}</button>`).join('')}</div>
 ${analyticsResult5(r)}
 </section>`:'<section class="panel empty"><h2>Choose your input fields, then run analytics.</h2><p>The same settings and calculations are available through the CLI and job-set pipelines. No API key or online lookup is used.</p></section>'}`;
}
function analyticsResult5(r){
 const t=S.analytics5.tab, cap=300, currencies=Object.keys(r.pricing.currencies);
 let body='';
 if(t==='groups')body=table5(['Group','Refs','Physical qty',...currencies.map(c=>'Cost / board '+c),'Mass (g)','Power (W)','Missing mass / power','Min Temp_Max (°C)',''],r.groups.slice(0,cap).map(g=>[esc(g.label),esc(g.references.join(', ')),g.physical_components,...currencies.map(c=>esc(pretty5(g.cost_per_board[c]))),esc(pretty5(g.mass_per_board)),esc(pretty5(g.power_per_board)),`${g.mass_missing_or_invalid} / ${g.power_missing_or_invalid}`,esc(pretty5(g.min_temp_max_c)),inspect5(g.ids)]));
 if(t==='pricing'){
  body=table5(['Currency','Installed / board','Installed build','Required incl. attrition','Order cost','Overbuy cost','Priced / eligible'],Object.entries(r.pricing.currencies).map(([c,p])=>[esc(c),...['known_cost_per_board','known_build_cost','known_required_cost','known_order_cost','known_overbuy_cost'].map(k=>esc(pretty5(p[k]))),`${p.priced_components} / ${p.eligible_components}`]));
  if(r.pricing.fx.enabled)body+=`<div class="notice">Manual FX: ${esc(r.pricing.fx.base_currency)} ${esc(pretty5(r.pricing.fx.known_cost_per_board))} per board — <b>${esc(r.pricing.fx.status)}</b>. Source: ${esc(r.pricing.fx.source||'Not supplied')}; date: ${esc(r.pricing.fx.as_of||'Not supplied')}. Missing rates: ${esc(r.pricing.fx.missing_rates.join(', ')||'none')}.</div>`;
  for(const [currency,items] of Object.entries(r.pricing.pareto)){body+=`<h3 class="ana-caption">Known-cost Pareto · ${esc(currency)} · ${items.length} groups</h3><div class="ana-bars">${items.slice(0,20).map(g=>`<div class="ana-bar-row"><span>${esc(g.label)}</span><meter min="0" max="100" value="${g.share_percent===null?0:Number(g.share_percent)}" aria-label="Share of known cost ${esc(g.label)}"></meter><span>${esc(pretty5(g.known_amount))} · ${esc(pretty5(g.share_percent,2))}% · ${esc(g.abc)}</span>${inspect5(g.ids)}</div>`).join('')}</div>`;}
 }
 if(t==='procurement')body=table5(['Manufacturer / MPN','Refs','Currency','Unit price','Installed qty','Required qty','Order qty','MOQ / multiple','Known order cost','Excess qty',''],r.procurement.slice(0,cap).map(p=>[esc(p.manufacturer+' / '+p.mpn),esc(p.references.join(', ')),esc(p.currency),esc(pretty5(p.unit_price)),p.installed_qty,p.required_qty,esc(pretty5(p.order_qty)),`${p.moq} / ${p.order_multiple}`,esc(pretty5(p.order_cost)),esc(pretty5(p.overbuy_qty)),inspect5(p.ids)]));
 if(t==='scenarios')body='<p class="ana-caption">All scenarios reuse entered rates. No inferred quantity discounts, taxes, shipping, NRE or labor. Power stays per board, not an assumed simultaneously powered batch.</p>'+table5(['Boards','Currency','Known installed cost','Known order cost','Known overbuy cost','Incomplete order lines','Installed build mass (g)','Dissipation / board (W)'],r.scenarios.map(s=>[s.boards,esc(s.currency||'—'),esc(pretty5(s.known_installed_cost)),esc(pretty5(s.known_order_cost)),esc(pretty5(s.known_overbuy_cost)),esc(pretty5(s.incomplete_order_lines)),esc(pretty5(s.known_installed_mass_g)),esc(pretty5(s.power_w_per_board))]));
 if(t==='components')body=table5(['Reference','Type','Population','Physical','Currency','Unit price','Mass (g)','Average loss (W)','Active/input loss (W)','Duty (%)','Temp_Max (°C)','Rating headroom (°C)',''],r.components.slice(0,cap).map(p=>[esc(p.reference),esc(p.type),pill(p.assembly),p.physical_eligible?'Yes':'No',esc(p.cost?.currency||'—'),esc(pretty5(p.cost?.unit_price)),esc(pretty5(p.mass?.value)),esc(pretty5(p.power?.value)),esc(pretty5(p.power?.input_power_w)),esc(pretty5(p.power?.duty_percent)),esc(pretty5(p.temperature?.value)),esc(pretty5(p.temperature?.headroom_c)),inspect5([p.id])]));
 if(t==='statistics')body='<p class="ana-caption">Statistics cover all query-matched records, including not-fitted rows. Add FIELD → unit mappings in Budgets, FX & statistics.</p>'+table5(['Field','Canonical unit','Known','Missing','Invalid','Min','Mean','Median','P95 (nearest rank)','Max'],Object.values(r.statistics).map(s=>[esc(s.field),esc(s.canonical_unit),s.known,s.missing,s.invalid,...['minimum','mean','median','p95_nearest_rank','maximum'].map(k=>esc(pretty5(s[k])))]));
 if(t==='issues')body=table5(['Severity','Code','Reference','Field','Finding'],r.issues.slice(0,cap).map(i=>[pill(i.severity),esc(i.code),esc(i.reference),esc(i.field),esc(i.message)]));
 if(r.budgets.length)body+=`<h3 class="ana-caption">Budget assessment</h3>`+table5(['Metric','Unit','Limit','Known subtotal','Unknown parts','Status'],r.budgets.map(b=>[esc(b.metric),esc(b.unit),esc(pretty5(b.limit)),esc(pretty5(b.known_subtotal)),b.unknown_components,pill(b.status)]));
 return body+`<p class="ana-caption">Tables show up to ${cap} rows; Pareto shows the top 20 groups. Exports contain the complete report. <b>Inspect filters the view; it does not select edit targets.</b></p>`;
}
function advancedAnalytics5(){const c=config5();showDialog('Budgets, FX & statistics',`<div class="notice">Decimal amounts use a dot. FX rates mean base-currency units per 1 source-currency unit, and need a source/date. Values are not fetched online.</div><div class="ana-grid">
 <label class="ana-field"><span>Mass budget / board (g)</span><input id="anaMassBudget" value="${esc(c.budgets.mass_g??'')}"></label><label class="ana-field"><span>Dissipation budget / board (W)</span><input id="anaPowerBudget" value="${esc(c.budgets.power_w??'')}"></label>
 <label class="ana-field ana-span2"><span>Cost budgets / board — currency-to-amount JSON</span><textarea id="anaCostBudgets">${esc(JSON.stringify(c.budgets.cost_per_board,null,2))}</textarea></label>
 <label class="ana-field ana-span2"><span>Statistics — field-to-unit JSON</span><textarea id="anaStatistics" rows="4">${esc(JSON.stringify(c.statistics,null,2))}</textarea><small>Example: {"Temp_Max":"C","Mass":"g","LeadTime":"number"}</small></label>
 <label class="ana-field ana-span2"><span>Additional unit mappings for searches — JSON</span><textarea id="anaFieldUnits" rows="3">${esc(JSON.stringify(c.field_units,null,2))}</textarea><small>Do not contradict defaults already declared for a mapped field.</small></label>
 <label class="ana-field ana-span2"><span>Quantity scenarios (comma-separated)</span><input id="anaScenarios" value="${esc(c.scenario_boards.join(', '))}"></label>
 <label class="ana-field ana-span2"><span>Manual FX — JSON</span><textarea id="anaFX" rows="5">${esc(JSON.stringify(c.fx,null,2))}</textarea></label>
 <label class="ana-field"><span>Supplier field</span><input id="anaSupplier" value="${esc(c.supplier_field)}"></label><label class="ana-field"><span>Supplier SKU field</span><input id="anaSKU" value="${esc(c.sku_field)}"></label><label class="ana-field"><span>Price-age warning after days</span><input id="anaAge" type="number" value="${c.quote_max_age_days}"></label><label class="ana-field"><span>Query values</span><span><input id="anaCase" type="checkbox" ${c.case_sensitive?'checked':''}> Case sensitive</span></label>
 </div><div class="row"><button type="submit" class="primary">Use these settings</button><span class="fine">No workspace or native files are written.</span></div>`,async()=>{
 const next=structuredClone(c);next.budgets={cost_per_board:JSON.parse($('#anaCostBudgets').value),mass_g:$('#anaMassBudget').value.trim()||null,power_w:$('#anaPowerBudget').value.trim()||null};next.statistics=JSON.parse($('#anaStatistics').value);next.field_units=JSON.parse($('#anaFieldUnits').value);next.fx=JSON.parse($('#anaFX').value);next.scenario_boards=$('#anaScenarios').value.trim()?$('#anaScenarios').value.split(',').map(x=>{if(!/^\s*\d+\s*$/.test(x))throw Error('Scenario quantities must be whole numbers.');return Number(x);}):[];next.supplier_field=$('#anaSupplier').value;next.sku_field=$('#anaSKU').value;next.quote_max_age_days=Number($('#anaAge').value);next.case_sensitive=$('#anaCase').checked;
 const validation=await api('analytics/validate',{config:next});S.analytics5.config=validation.config;S.analytics5.dirty=true;render();
 });}
async function runAnalytics5(){const button=$('[data-act=analyticsRun]');if(button)button.disabled=true;try{const c=structuredClone(config5());const report=await api('analytics/run',{variant:S.variant,config:c});S.analytics5.report=report;S.analytics5.inputKey=JSON.stringify(c);render();toast('Analytics computed. Unknowns remain explicit; no component fields changed.');}finally{if(button)button.disabled=false;}}
function thresholdDialog5(field){const old=S.threshold5;const fields=[...new Set(S.data.rows.flatMap(r=>Object.keys(r.fields)))].sort();field=field||old?.field||((fields.includes('Temp_Max')&&'Temp_Max')||fields[0]);showDialog('Column threshold — filter or highlight',`<div class="notice">For example, select Temp_Max and enter <b>&lt;80</b>. Unknown or invalid values never match. Highlighting does not change the checkboxes used by bulk actions.</div><div class="ana-grid"><label class="ana-field ana-span2"><span>Column</span><select id="thresholdField">${fields.map(f=>`<option ${f===field?'selected':''}>${esc(f)}</option>`).join('')}</select></label><label class="ana-field"><span>Condition</span><input id="thresholdCondition" value="${esc(old?.condition||'<80')}" placeholder="<80"></label><label class="ana-field"><span>Unit for bare numbers</span><select id="thresholdUnit"><option value="">Use saved analytics mapping</option>${units5.map(u=>`<option value="${u}" ${old?.unit===u?'selected':''}>${u}</option>`).join('')}</select></label></div><div class="row"><button data-act="thresholdTest" class="primary">Test threshold</button><button data-act="thresholdFilter">Filter to matches</button><button data-act="thresholdHighlight">Highlight matches</button></div><div id="thresholdResult" aria-live="polite"></div>`);}
async function evaluateThreshold5(mode){const field=$('#thresholdField').value,condition=$('#thresholdCondition').value,unit=$('#thresholdUnit').value||null;const report=await api('threshold',{variant:S.variant,field,condition,unit});$('#thresholdResult').innerHTML=`<div class="notice"><b>${report.matched} / ${report.tested} match</b> · ${report.numeric_components} numeric · ${report.unknown_or_invalid.length} unknown/invalid.<br>${esc(report.references.join(', ')||'No matches')}<br>Canonical threshold: ${esc(report.threshold_value)} ${esc(report.canonical_unit)}</div>`;
 if(mode){S.threshold5={field,condition,unit,mode,report,context:context4(),error:''};S.page=0;$('#dialog').close();render();toast(mode==='filter'?'Threshold filter applied before grouping.':'Only matching rows are highlighted; edit selection unchanged.');}}
async function recheckThreshold5(){if(!S.threshold5)return;const t=S.threshold5;try{const report=await api('threshold',{variant:S.variant,field:t.field,condition:t.condition,unit:t.unit});if(t!==S.threshold5)return;t.report=report;t.context=context4();t.error='';}catch(e){t.error=e.message;t.context='';}}
function thresholdBanner5(){const t=S.threshold5,d=S.drill5;let html=`<div class="row ana-view-tools"><button class="small" data-act="columnThreshold">Column threshold…</button><button class="small" data-view="analytics">Cost, mass & power →</button>`;
 if(t)html+=`<span class="pill">${esc(t.field)} ${esc(t.condition)} · ${t.mode==='filter'?'Filter':'Highlight'} · ${t.report.matched} matches / ${t.report.unknown_or_invalid.length} unknown</span><button class="quiet small" data-act="clearThreshold">Clear threshold</button>${t.error?`<span role="alert">${esc(t.error)}</span>`:''}`;
 if(d)html+=`<span class="pill">Analytics drill-down · ${d.ids.length} components</span><button class="quiet small" data-act="clearAnalyticsDrill">Clear drill-down</button>`;
 return html+'</div>';}
const filteredBefore5=filteredRows;
filteredRows=function(){let rows=filteredBefore5();if(S.filterBypass)return rows;const t=S.threshold5;if(t?.mode==='filter'){if(t.context!==context4()||t.error)return [];const ids=new Set(t.report.ids);rows=rows.filter(r=>ids.has(r.id));}if(S.drill5){if(S.drill5.context!==context4())return [];const ids=new Set(S.drill5.ids);rows=rows.filter(r=>ids.has(r.id));}return rows;};
const bomBefore5=renderBOM;
renderBOM=function(){return thresholdBanner5()+bomBefore5();};
function paintThreshold5(){if(S.view!=='bom')return;const t=S.threshold5,ids=new Set(t&&t.context===context4()&&!t.error?t.report.ids:[]);$$('tr[data-row]').forEach(el=>{const hit=ids.has(el.dataset.row);el.classList.toggle('threshold-match',hit);if(hit)el.setAttribute('aria-description','Matches numeric threshold');else el.removeAttribute('aria-description');});$$('tr[data-link-group]').forEach(el=>{const g=groupById(el.dataset.linkGroup);const count=g?g.ids.filter(id=>ids.has(id)).length:0;el.classList.toggle('threshold-match',count>0);if(count)el.setAttribute('aria-description',`${count} group members match threshold`);});$$('th[data-grid-column]').forEach(th=>{if(!th.querySelector('.threshold-column-button')){const b=document.createElement('button');b.className='quiet threshold-column-button';b.dataset.act='columnThreshold';b.dataset.thresholdField=th.dataset.gridColumn;b.textContent='⋮';b.title='Numeric threshold for '+th.dataset.gridColumn;b.setAttribute('aria-label',b.title);th.append(b);}});}
const renderBefore5=render;
render=function(){if(S.data?.project)config5();renderBefore5();paintThreshold5();if(S.view==='analytics')S.formDirty=S.analytics5.dirty;};
const refreshBefore5=refresh;
refresh=async function(){await refreshBefore5();if(S.threshold5&&S.threshold5.context!==context4()){await recheckThreshold5();render();}if(S.drill5&&S.drill5.context!==context4()){S.drill5=null;render();}};
const saveBefore5=save;
save=async function(){if(S.analytics5.dirty&&S.analytics5.project===projectKey5()){await api('analytics/settings',{settings:config5()});S.analytics5.dirty=false;S.formDirty=false;}return saveBefore5();};
handlers.save=save;
const automationBefore5=renderAutomation;
renderAutomation=function(){return `<div class="notice">Cost/mass/power analytics can use the same report engine and policy gates in CLI and generated job sets. <button data-act="analyticsPipeline">Include current analytics settings in this pipeline</button></div>`+automationBefore5();};
Object.assign(handlers,{
 analyticsRun:runAnalytics5,analyticsAdvanced:advancedAnalytics5,
 analyticsSave:async()=>{const r=await api('analytics/settings',{settings:config5()});S.analytics5.config=r.settings;S.analytics5.dirty=false;await refresh();toast('Analytics settings staged. Save workspace to persist; component properties unchanged.');},
 analyticsShare:()=>saveJSON(config5(),'WayriCAD_analytics_settings.json'),
 analyticsProject:async()=>{const result=await api('analytics/save-project',{config:config5()});showDialog('Reports saved in project',`<p>${esc(result.folder)}</p><ul>${result.files.map(f=>`<li>${esc(f)}</li>`).join('')}</ul>${formActions('Close')}`,async()=>{});},
 analyticsExport:()=>download('analytics/export',{config:config5(),format:$('#analyticsFormat').value,table:$('#analyticsTable').value}),
 analyticsTab:el=>{S.analytics5.tab=el.dataset.tab;render();},
 analyticsInspect:el=>{if(S.gridDrafts?.size)throw Error('Review pending grid edits before changing the view scope.');if(S.analytics5.report?.revision!==S.data.revision||S.analytics5.report?.variant!==S.variant)throw Error('Run analytics again before inspecting a stale report.');S.drill5={ids:JSON.parse(el.dataset.ids),context:context4()};S.threshold5=null;S.search='';S.filter='all';S.advanced={query:'',case_sensitive:false,ids:null,context:'',error:''};S.filterBypass=false;S.view='bom';S.page=0;render();},
 clearAnalyticsDrill:()=>{S.drill5=null;S.page=0;render();},
 columnThreshold:el=>thresholdDialog5(el?.dataset.thresholdField),thresholdTest:()=>evaluateThreshold5(),thresholdFilter:()=>evaluateThreshold5('filter'),thresholdHighlight:()=>evaluateThreshold5('highlight'),
 clearThreshold:()=>{S.threshold5=null;S.page=0;render();},
 analyticsPipeline:()=>{const p=readPipeline4();p.reports=[...new Set([...(p.reports||[]),'analytics'])];p.analytics=structuredClone(config5());p.analytics_formats=['json','xlsx','html'];p.policy={...p.policy,analytics:p.policy?.analytics||'none'};S.pipeline=p;render();toast('Analytics added as advisory reports. Set policy.analytics deliberately to error, warning or unknown for a release gate.');}
});
function touchAnalytics5(){S.analytics5.dirty=true;S.formDirty=true;const status=$('#analyticsSettingsStatus');if(status)status.textContent='Local settings changed. Run uses these settings; Save settings and Save workspace to persist.';}
document.addEventListener('input',e=>{if(e.target.dataset.pcb!==undefined){const c=config5();c.pcb=c.pcb||{};c.pcb[e.target.dataset.pcb]=e.target.value;touchAnalytics5();}if(e.target.dataset.ana!==undefined){const key=e.target.dataset.ana,c=config5();c[key]=e.target.type==='checkbox'?e.target.checked:(['boards','quote_max_age_days'].includes(key)?(e.target.value===''?null:Number(e.target.value)):(['temperature_requirement_c','attrition_percent'].includes(key)&&e.target.value===''?null:e.target.value));touchAnalytics5();}if(e.target.id==='analyticsGroupBy'){config5().group_by=e.target.value.split('\n').map(x=>x.trim()).filter(Boolean);touchAnalytics5();}});
document.addEventListener('change',async e=>{try{if(e.target.dataset.anaMetric){const metric=e.target.dataset.anaMetric,c=config5();c.metrics=e.target.checked?[...new Set([...c.metrics,metric])]:c.metrics.filter(x=>x!==metric);touchAnalytics5();}if(e.target.id==='analyticsConfigImport'&&e.target.files[0]){const file=e.target.files[0];if(file.size>2*1024*1024)throw Error('Analytics settings exceed 2 MiB.');const result=await api('analytics/validate',{config:JSON.parse(await file.text())});S.analytics5.config=result.config;S.analytics5.dirty=true;render();toast('Settings loaded locally. No component data or native files changed.');}}catch(error){toast(error.message,true);}});
// Draft mapping settings survive view navigation; top-level Save commits them.
document.addEventListener('click',e=>{const target=e.target.closest('[data-view]');if(S.view==='analytics'&&S.analytics5.dirty&&target&&target.dataset.view!=='analytics'){S.formDirty=false;toast('Analytics mapping draft kept for this session. Save workspace to persist it.');}},true);
window.addEventListener('beforeunload',e=>{if(S.analytics5.dirty){e.preventDefault();e.returnValue='';}});
