'use strict';
/* Engineering extensions use the existing authenticated local API and reviewed edits. */
const E6={tab:'catalog',info:null,page:null,query:'',offset:0,picked:new Set(),task:null,report:null,policy:{roles:['engineering'],check_level:'error',catalog_required:false,stock_required:false,qualification_required:false,market:'IN',freshness_hours:24},build:null,virtual:false,vstart:0,vfocus:0,req:0};
titles.engineering=['Library & engineering control','Reuse with provenance. Approve a specific context. Plan before purchasing.'];
const eng6=(op,body={})=>api('engineering/'+op,{variant:S.variant,...body});
const pretty6=x=>JSON.stringify(x,null,2);
const field6=(label,name,value='',type='text',extra='')=>`<label class="field"><span>${esc(label)}</span><input name="${esc(name)}" type="${esc(type)}" value="${esc(value)}" ${extra}></label>`;
const area6=(label,name,value,rows=8)=>`<label class="field"><span>${esc(label)}</span><textarea name="${esc(name)}" rows="${rows}" spellcheck="false">${esc(typeof value==='string'?value:pretty6(value))}</textarea></label>`;
const button6=(act,label,extra='')=>`<button type="button" class="small" data-act="${act}" ${extra}>${label}</button>`;
const json6=x=>`<details class="eng-json"><summary>Complete structured report / provenance</summary><pre>${esc(pretty6(x))}</pre></details>`;
const state6=(state,tip='')=>`<span class="eng-state ${/blocked|error|mismatch|shortfall|at risk|not_approved|invalid|revoked/i.test(state)?'risk':/warn|nrnd|estimate|stale|expired|deprecated|review/i.test(state)?'warn':/observed|matched|approved|current|preferred|passed/i.test(state)?'good':'unknown'}" title="${esc(tip)}">${esc(state)}</span>`;
function report6(report,title='Report ready'){E6.report={data:report,title,variant:S.variant,revision:S.data?.revision};render();toast(title);}
function table6(headers,rows){return `<div class="table-wrap"><table class="data-table"><thead><tr>${headers.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${headers.length}">No entries.</td></tr>`}</tbody></table></div>`;}
function componentSelect6(name='component'){return `<label class="field"><span>Component in ${esc(S.variant)}</span><select name="${name}">${(S.data?.rows||[]).map(r=>`<option value="${esc(r.id)}">${esc(r.ref+' · '+(r.fields.Value||'')+' · '+(r.fields.Footprint||'No footprint'))}</option>`).join('')}</select></label>`;}
function reportPanel6(){const r=E6.report;if(!r)return '';return `<section class="panel"><div class="panel-title"><h2>${esc(r.title)}</h2>${button6('engDownloadReport','Save report JSON')}${button6('engClearReport','Dismiss')}</div><div class="panel-body">${r.revision!==S.data?.revision||r.variant!==S.variant?'<div class="notice warning">Workspace/variant changed after this report. Rerun before relying on it.</div>':''}${r.data.status?state6(r.data.status):''}${r.data.notice?`<p class="fine">${esc(r.data.notice)}</p>`:''}${renderReport6(r.data)}${json6(r.data)}</div></section>`;}
function renderReport6(r){
 if(r.schema==='wayricad-build-result-1')return `<p><b>${r.demands.length} demand lines · ${r.orders.length} planned orders</b> · Known cost: ${esc(pretty6(r.known_cost_by_currency))}</p>`+table6(['Build','MPN','Required','Inventory','Purchases','Shortfall','State'],r.demands.map(x=>`<tr><td>${esc(x.build)}</td><td>${esc(x.mpn)}</td><td>${x.required}</td><td>${x.inventory_used||0}</td><td>${x.purchased_allocated||0}</td><td>${x.shortfall||0}</td><td>${state6(x.status)}</td></tr>`))+`<h3>Issues requiring review</h3>`+table6(['Severity','Scope','Finding'],r.issues.map(x=>`<tr><td>${state6(x.severity)}</td><td>${esc(x.scope)}</td><td class="wrap">${esc(x.message)}</td></tr>`));
 if(r.schema==='wayricad-review-context-1')return `<p class="fine">Input fingerprint: <code>${esc(r.input_hash)}</code><br>Required roles still missing: ${esc(r.missing_roles?.join(', ')||'None')}</p><div class="row">${button6('engDecision','Record decision…')}${button6('engAccounts','Manage local reviewers')}</div>`+table6(['Severity','Finding','Scope','Action'],(r.issues||[]).map(x=>`<tr><td>${state6(x.severity)}</td><td class="wrap">${esc(x.message)}</td><td>${esc(x.reference)}</td><td>${x.severity==='error'?'Not waivable':button6('engWaiver','Review waiver…',`data-target="${esc(x.id)}"`)}</td></tr>`))+table6(['Reviewer','Role','Kind','Status','Reason'],(r.decisions||[]).map(x=>`<tr><td>${esc(x.reviewer)}</td><td>${esc(x.role)}</td><td>${esc(x.kind)}</td><td>${state6(x.status)}</td><td class="wrap">${esc(x.reason)}</td></tr>`));
 if(r.schema==='wayricad-catalog-health-1')return `<p>${r.assessed} / ${r.total} catalog identities assessed · ${r.all_matches?'all matches':'this page'} · ${esc(pretty6(r.counts))}. Dated observations, not a live query.</p>`+table6(['Internal PN','MPN','Lifecycle','Stock','State'],r.items.slice(0,200).map(x=>`<tr><td>${esc(x.internal_pn)}</td><td>${esc(x.mpn)}</td><td>${state6(x.health.lifecycle,x.health.lifecycle_labels.join(', '))}</td><td>${state6(x.health.low_stock?'LOW STOCK < '+x.health.low_stock_threshold:x.health.stock.status)}</td><td>${state6(x.health.state,x.health.tooltip)}</td></tr>`));
 if(r.issues)return table6(['Severity','Finding'],r.issues.map(x=>`<tr><td>${state6(x.severity||'unknown')}</td><td class="wrap">${esc(x.message||x)}</td></tr>`));
 return '';
}
function renderEngineering(){
 const tabs=[['catalog','Local catalog'],['reuse','Recommend & reuse'],['mass','Mass suggestions'],['variants','BOM-only variants'],['qualify','Land patterns & pins'],['reviews','Controlled reviews'],['purchasing','Multi-build planning'],['validation','Host & performance']];
 let content=`<div class="eng-tabs" role="tablist" aria-label="Engineering tools">${tabs.map(([id,label])=>`<button role="tab" aria-selected="${E6.tab===id}" data-act="engTab" data-tab="${id}" class="${E6.tab===id?'active':''}">${label}</button>`).join('')}</div><div class="eng-librarybar"><span>${E6.info?.attached?`<b>${esc(E6.info.path||E6.info.directory||'Local library attached')}</b> · ${E6.info.parts??'?'} parts`: 'Attach a reusable library once; other projects can use it too.'}</span><span class="grow"></span>${button6('engAttach','Attach library')}${button6('engCreate','New library')}</div>`;
 if(E6.tab==='catalog')content+=renderCatalog6();
 if(E6.tab==='reuse')content+=`<section class="panel"><div class="panel-title"><h2>Find candidates for this project</h2>${state6('Screening only','No automatic substitution or qualification.')}</div><div class="panel-body"><p>Recommendations match the resolved value pattern and exact selected footprint, then show rating conflicts, unknowns, catalog preference and dated health. Raw variables remain untouched until a reviewed edit.</p><div class="row">${button6('engSuggest','Choose component…')}${button6('engSuggestSelected','Recommend for selected BOM part')}</div><p class="fine">BOM row actions also expose recommendations. FTS metadata search remains available for exploratory choices outside this compatibility screen.</p><div id="engAutoRecommend" aria-live="polite"></div></div></section>`;
 if(E6.tab==='mass')content+=`<section class="panel"><div class="panel-title"><h2>Fill missing mass—without inventing precision</h2>${state6('Estimated ≠ measured')}</div><div class="panel-body"><p>Exact-MPN catalog observations appear first. Published typical package examples can be offered for supported resistors, MLCCs and a few semiconductor packages. Inspect package height, dielectric and construction assumptions.</p><div class="notice warning">A footprint alone does not establish mass. These are source-linked proposals, not universally correct package constants. Existing nonblank mass fields are never overwritten.</div>${button6('engMass','Find missing-mass suggestions…')}<p class="fine">Acceptance adds Mass_Basis, Mass_Source, Mass_Assumptions and Mass_Uncertainty. Analytics keeps the estimate warning.</p></div></section>`;
 if(E6.tab==='variants')content+=renderVariants6();
 if(E6.tab==='qualify')content+=`<section class="panel"><div class="panel-title"><h2>Declared manufacturer land-pattern checks</h2>${button6('engQualify','Compare geometry & pins…')}</div><div class="panel-body"><p>Compare each numbered pad: position, dimensions, rotation, shape, mounting, layer set, drill and explicitly specified mask/paste details. Pin functions use exact, explicitly accepted names.</p><div class="notice warning">Supply a human-verified transcription of the <b>recommended land pattern</b>, not the component body drawing. Missing checks remain incomplete. No OCR, pin-swap inference, electrical-equivalence claim or manufacturer certification.</div><p class="fine">The same source-linked specification can be stored on a catalog revision. Controlled review binds its report hash, geometry hash, exact MPN and project context.</p></div></section>`;
 if(E6.tab==='reviews')content+=`<section class="panel"><div class="panel-title"><h2>Local authenticated review</h2>${button6('engAccounts','Reviewers & roles')}</div><div class="panel-body"><p>Approvals and waivers name a reviewer, role, reason, evidence reference and expiry. They bind source/workspace state, catalog revisions, geometry and policy. A changed input makes the previous decision stale.</p><div class="notice">Passphrases are local; the first reviewer is an administrator. An administrator creates separate engineering/supply accounts. This is not enterprise identity, PKI or a regulated electronic signature.</div><div class="row">${button6('engReviewPolicy','Review policy…')}${button6('engReviewContext','Assess current approval state')}${button6('engPipelineReview','Export controlled pipeline config')}</div><p class="fine">Errors cannot be waived. Unknown/warning waivers are scoped to one exact finding and require the appropriate role. Locks are editing safeguards, not security boundaries.</p></div></section>`;
 if(E6.tab==='purchasing')content+=`<section class="panel"><div class="panel-title"><h2>Several builds, one inventory ledger</h2>${button6('engBuild','Configure builds & offers…')}</div><div class="panel-body"><p>Pool exact identities across saved projects and variants. Allocate inventory by priority and expiry, account for attrition, MOQ, pack multiples, quantity tiers and typed lead times. Inventory pools are consumed once.</p><div class="row">${button6('engInventory','Inventory lots…')}${button6('engInventoryList','Inspect current inventory')}${button6('engOffers','Prepare offers from catalog evidence')}${button6('engRunBuild','Run saved session scenario')}</div><div class="notice warning">A plan places no orders and reserves no stock. Split orders require explicit permission and review that pools are independent. Different currencies are not silently converted; the priority heuristic is not a global optimum.</div></div></section>`;
 if(E6.tab==='validation')content+=`<section class="panel"><div class="panel-title"><h2>Evidence for the software itself</h2></div><div class="panel-body"><p>Use <code>python cli.py hosttest --directory NEW_DIRECTORY</code> on each actual supported host. It invokes the installed KiCad CLI on a disposable project copy and records the native version, reload and job-set results.</p><div class="notice warning">KiCad-host operation, native libraries, real cross-selection, Windows/macOS installation and assistive screen-reader acceptance are not certified by this package's simulated tests. Absent capabilities stay SKIPPED.</div><p>Use <code>python cli.py benchmark --parts 10000 --queries 100</code> for a reproducible temporary catalog benchmark. Read the included test report for measured results and scope.</p><div class="row">${button6('engVerify','Verify catalog integrity')}${button6('engVirtual','Toggle bounded virtual BOM view')}</div><p class="fine">Catalog search is paginated in SQLite. The optional ungrouped BOM viewport renders a bounded window; the underlying workspace is still loaded in memory. Grouped mode keeps pagination; expanded groups are not virtualized.</p></div></section>`;
 return content+`<div class="spacer"></div>`+reportPanel6();
}
function renderCatalog6(){const page=E6.page;return `<section class="panel"><div class="toolbar"><input id="engQuery" type="search" class="searchbox" value="${esc(E6.query)}" placeholder="Search MPN, value, type, project metadata…" aria-label="Search local catalog"><button class="primary small" data-act="engSearch">Search</button><span class="grow"></span>${button6('engHarvest','Harvest projects…')}${button6('engNewPart','New part')}${button6('engHealth','Catalog health')}${button6('engSnapshot','Export metadata JSON')}${button6('engNative','Export selected native library')}</div><p class="fine eng-pad">Preferences, lifecycle, stock and qualification are separate. Colors always carry text and tooltips. ${page?`${page.total} identities · ${E6.picked.size} selected`: 'Search after attaching a local catalog.'}</p>${page?table6(['Select','Internal PN / revision','Manufacturer / MPN','Value / footprint','Lifecycle','Stock','State','Actions'],page.items.map(p=>`<tr><td><input type="checkbox" data-eng-select="${esc(p.id)}" ${E6.picked.has(p.id)?'checked':''} aria-label="Select ${esc(p.internal_pn||p.id)}"></td><td><b>${esc(p.internal_pn)}</b><br><span class="fine">Revision ${p.revision}</span></td><td>${esc(p.fields.Manufacturer||'Unresolved')}<br><b>${esc(p.fields.MPN||'Generic observation')}</b></td><td>${esc(p.fields.Value)}<br><span class="fine">${esc(p.fields.Footprint)}</span></td><td>${state6(p.health?.lifecycle||'UNKNOWN',p.health?.lifecycle_labels?.join(', '))}</td><td>${state6(p.health?.low_stock?'LOW STOCK < '+p.health.low_stock_threshold:p.health?.stock?.status||'unknown',p.health?.tooltip)}</td><td>${state6(p.status)} ${state6(p.health?.state||'unknown',p.health?.tooltip)}</td><td><div class="row">${button6('engPart','Inspect',`data-id="${esc(p.id)}"`)}${button6('engEditPart','Edit',`data-id="${esc(p.id)}"`)}${button6('engEvidence','Evidence',`data-id="${esc(p.id)}"`)}</div></td></tr>`))+`<div class="table-footer"><span>Rows ${page.offset+1}–${Math.min(page.total,page.offset+page.items.length)} of ${page.total}</span><div class="row">${button6('engPrevious','Previous',!page.offset?'disabled':'')}${button6('engNext','Next',page.next_offset==null?'disabled':'')}</div></div>`:'<div class="empty">Your reusable parts catalog appears here.</div>'}</section>`;}
function renderVariants6(){const all=Object.entries(S.data.variants).filter(([_,v])=>v.bom_only);return `<section class="panel"><div class="panel-title"><h2>Independent BOM variants</h2>${button6('engNewVariant','New BOM-only variant…')}</div><div class="panel-body"><p>Derived variants inherit by design. Pinned variants copy current raw fields, flags and effective variables. They remain independent of native KiCad variant definitions and are excluded from native synchronization.</p><div class="notice">Pinned is not a complete immutable archive: source geometry, hierarchy and supported built-in context can still change. Use a release snapshot and controlled approval for that boundary.</div></div>${table6(['Variant','Parent','Mode','State','Tags','Actions'],all.map(([name,v])=>`<tr><td><b>${esc(name)}</b><br>${esc(v.description)}</td><td>${esc(v.parent)}</td><td>${v.pinned?'Pinned fields':'Derived'}</td><td>${state6(v.locked?'LOCKED':'EDITABLE')}</td><td>${esc((v.tags||[]).join(', '))}</td><td>${button6('engUseVariant','Use',`data-name="${esc(name)}"`)} ${button6('engVariantAction',v.locked?'Unlock / manage…':'Manage…',`data-name="${esc(name)}"`)}</td></tr>`))}</section>`;}
function downloadJSON6(value,name){const url=URL.createObjectURL(new Blob([pretty6(value)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function review6(title,plan,token,apply,extra=''){
 showDialog(title,`<div class="notice warning">Review the full proposed change. This step does not write native KiCad files.</div>${json6(plan)}${button6('engPlanDownload','Download complete plan')}${extra}${field6('Type '+token+' to confirm','confirmation')}${formActions('Stage reviewed change')}`,async f=>{if(f.get('confirmation')!==token)throw Error('Type '+token+' after reviewing.');await apply(f);await refresh();toast('Reviewed operation completed. Native synchronization remains separate.');});E6.pending=plan;
}
async function connect6(create){showDialog(create?'Create a local parts library':'Attach a local parts library',`<p class="fine">Choose an absolute directory on a local disk. A catalog is separate from projects and from KiCad .kicad_sym/.pretty files.</p>${field6('Absolute library directory','path',S.data?.engineering?.library||'')}${create?field6('Type CREATE','confirmation'):''}<label class="check-label"><input type="checkbox" name="remember" checked>Remember as the default for other projects on this computer</label>${formActions(create?'Create library':'Attach library')}`,async f=>{await eng6(create?'create':'attach',{path:f.get('path'),confirmation:f.get('confirmation'),remember:f.has('remember')});E6.info=await eng6('info');E6.page=await eng6('search',{query:'',limit:50});E6.query='';E6.offset=0;await refresh();});}
async function searchCatalog6(){E6.query=$('#engQuery')?.value??E6.query;E6.info=await eng6('info');if(!E6.info.attached)throw Error('Create or attach a local library first.');E6.page=await eng6('search',{query:E6.query,offset:E6.offset,limit:50});render();}
async function editPart6(pid){const part=pid?(await eng6('get',{id:pid})).part:null;showDialog(part?'Edit catalog revision':'New orderable catalog part',`<div class="notice">An existing exact manufacturer/MPN identity cannot be renamed. A preferred part is not automatically qualified.</div><div class="columns2">${field6('Internal part number','ipn',part?.internal_pn||'')}${field6('Manufacturer','manufacturer',part?.fields.Manufacturer||'','text',part?'readonly':'')}${field6('Full orderable MPN','mpn',part?.fields.MPN||'','text',part?'readonly':'')}${field6('Value','value',part?.fields.Value||'')}${field6('Footprint identifier','footprint',part?.fields.Footprint||'')}${field6('Reference/type hint (R1, C1, U1…)','ref',part?.reference_hint||'')}</div><label class="field"><span>Catalog preference</span><select name="status">${['candidate','preferred','deprecated','blocked'].map(x=>`<option ${x===part?.status?'selected':''}>${x}</option>`).join('')}</select></label>${field6('Searchable tags, comma-separated','tags',(part?.tags||[]).join(', '))}${area6('Additional fields JSON (ordinary string properties)','fields',Object.fromEntries(Object.entries(part?.fields||{}).filter(([k])=>!['Manufacturer','MPN','Value','Footprint'].includes(k))),5)}<details><summary>Declared land pattern / candidate alternate links / conflict resolution</summary>${area6('Source-linked wayricad-land-pattern-1 specification, or null','spec',part?.land_pattern||null,5)}${area6('Candidate alternate links JSON (never an approval flag)','alts',part?.alternates||[],4)}${area6('Conflict indexes deliberately resolved in this revision','resolved',[],2)}${part?.conflicts?.length?json6(part.conflicts):''}</details>${field6('Catalog notes','notes',part?.notes||'')}${field6('Editor / actor name','actor')}${field6('Revision reason','reason')}<div class="form-actions"><button type="button" class="primary" id="engPartPreview">Preview revision</button></div>`,()=>{});
 $('#engPartPreview').onclick=async()=>{try{const f=new FormData($('#dialogBody form')),fields={...JSON.parse(f.get('fields')),Manufacturer:f.get('manufacturer'),MPN:f.get('mpn'),Value:f.get('value'),Footprint:f.get('footprint')};const request={...(part?{id:part.id,expected_revision:part.revision}:{new:true}),fields,notes:f.get('notes'),status:f.get('status'),reference_hint:f.get('ref'),tags:String(f.get('tags')).split(',').map(s=>s.trim()).filter(Boolean),land_pattern:JSON.parse(f.get('spec')),alternates:JSON.parse(f.get('alts')),resolve_conflicts:JSON.parse(f.get('resolved'))};if(f.get('ipn'))request.internal_pn=f.get('ipn');const plan=await eng6('part-preview',{request}),actor=f.get('actor'),reason=f.get('reason');review6('Review catalog revision',plan,'CATALOG',async g=>{await eng6('part-apply',{plan,confirmation:g.get('confirmation'),actor,reason});E6.page=await eng6('search',{query:E6.query,offset:E6.offset,limit:50});E6.info=await eng6('info');});}catch(e){toast(e.message,true);}};
}
async function harvest6(){showDialog('Harvest selected local projects',`${area6('Absolute project paths or directories, one per line','paths','',5)}<label class="check-label"><input type="checkbox" name="recursive">Scan subdirectories of the explicitly selected folders</label><label class="check-label"><input type="checkbox" name="assets" checked>Capture resolved embedded symbols and local footprints</label><label class="check-label"><input type="checkbox" name="variants" checked>Include every variant</label><div class="notice">No full-disk scan or network scraping. A completed scan is only a review plan. Existing curated fields win conflicts.</div>${formActions('Scan for review')}`,async f=>{E6.task=await eng6('harvest-start',{paths:String(f.get('paths')).split('\n').map(x=>x.trim()).filter(Boolean),recursive:f.has('recursive'),capture_assets:f.has('assets'),include_variants:f.has('variants')});setTimeout(pollHarvest6,100);});}
async function pollHarvest6(){if(!E6.task)return;try{const t=await eng6('task-status',{id:E6.task.id});E6.task=t;const html=`<div role="status" aria-live="polite"><p>${esc(t.message)}</p><progress max="${t.total||1}" value="${t.current||0}" aria-label="Project scan progress"></progress><p>${t.current||0} / ${t.total||'?'}</p></div>`;if(t.state==='running'){showDialog('Scanning explicit projects',html+`<button type="button" id="engCancelHarvest">Cancel scan</button>`,()=>{});$('#engCancelHarvest').onclick=async()=>{await eng6('task-cancel',{id:t.id});$('#dialog').close();};setTimeout(pollHarvest6,350);}else if(t.state==='ready'){showDialog('Review harvested parts',html+json6(t.summary)+field6('Import actor','actor')+field6('Type IMPORT','confirmation')+`<label class="check-label"><input name="partial" type="checkbox">Import successful projects despite listed failures</label><div class="row">${button6('engHarvestFull','Download complete scan plan')}</div>${formActions('Import into catalog')}`,async f=>{await eng6('harvest-import',{task_id:t.id,confirmation:f.get('confirmation'),actor:f.get('actor'),allow_partial:f.has('partial')});E6.info=await eng6('info');E6.page=await eng6('search',{query:E6.query,limit:50});render();});}else{toast(t.message,t.state==='failed');if($('#dialogTitle').textContent==='Scanning explicit projects')$('#dialog').close();}}catch(e){toast(e.message,true);}}
async function health6(){showDialog('Assess entire matching catalog',`${field6('Search (blank = entire catalog)','query',E6.query)}${field6('Market','market','IN')}${field6('Freshness, hours','freshness_hours','24','number')}${field6('Low-stock warning below quantity','low_stock_threshold','100','number')}<p class="fine">The scan is local, read-only and cancelable. It uses dated observations already recorded in the catalog.</p>${formActions('Run catalog health')}`,async f=>{const t=await eng6('health-start',{query:f.get('query'),market:f.get('market'),freshness_hours:Number(f.get('freshness_hours')),low_stock_threshold:Number(f.get('low_stock_threshold'))});setTimeout(()=>pollHealth6(t.id),100);});}
async function pollHealth6(id){try{const t=await eng6('task-status',{id,include_result:true});if(t.state==='running'){showDialog('Assessing catalog health',`<p role="status">${esc(t.message)} · ${t.current} / ${t.total||'?'}</p><progress max="${t.total||1}" value="${t.current||0}" aria-label="Catalog health progress"></progress><button type="button" id="engCancelHealth">Cancel scan</button>`,()=>{});$('#engCancelHealth').onclick=()=>eng6('task-cancel',{id});setTimeout(()=>pollHealth6(id),300);}else{if($('#dialogTitle').textContent==='Assessing catalog health')$('#dialog').close();if(t.state==='ready')report6(t.result,'Full catalog health · dated observations');else toast(t.message,t.state==='failed');}}catch(e){toast(e.message,true);}}
async function suggestions6(cid){const report=await eng6('recommend',{component:cid,limit:40});E6.lastRecommendations=report;showDialog('Catalog candidates · '+report.component,`<p class="fine">Value pattern and exact footprint are a starting screen. Conflicts block use. Missing ratings, electrical suitability and manufacturer evidence still require engineering review.</p>${table6(['MPN / IPN','Rank','State','Reasons / missing data','Action'],report.items.map(c=>`<tr><td><b>${esc(c.part.fields.MPN)}</b><br>${esc(c.part.internal_pn)}</td><td>${esc(c.score)}</td><td>${state6(c.state,c.health?.tooltip)}</td><td class="wrap">${esc(pretty6({conflicts:c.conflicts,missing:c.missing_evidence,health:c.health?.lifecycle}))}</td><td>${button6('engChooseCandidate','Review use…',`data-component="${esc(cid)}" data-id="${esc(c.part.id)}" ${c.state==='blocked'?'disabled':''}`)}</td></tr>`))}${report.reason?`<p>${esc(report.reason)}</p>`:''}${json6(report)}`,()=>{});}
async function chooseCandidate6(el){const plan=await eng6('recommend-preview',{component:el.dataset.component,part_id:el.dataset.id});review6('Review candidate property edits',plan,'EDIT',async f=>eng6('recommend-apply',{plan,confirmation:f.get('confirmation'),engineering_ack:f.has('engineering'),acknowledge_loss:f.has('loss')}),`<label class="check-label"><input type="checkbox" name="engineering" required>I reviewed compatibility; this only edits metadata, not the library symbol or geometry.</label><label class="check-label"><input type="checkbox" name="loss">Acknowledge any raw-expression loss shown in the plan</label>`);}
async function masses6(){const report=await eng6('mass-suggest');E6.mass=report;showDialog('Missing mass · choose an explicit source',`<div class="notice warning">${esc(report.notice)}</div><p>${report.items.length} components with suggestions · ${report.unknown.length} without evidence · ${report.existing_untouched} existing values untouched</p>${table6(['Accept','Component','Mass source / construction','Source notes'],report.items.map(x=>`<tr><td><input type="checkbox" data-mass-pick="${esc(x.id)}" aria-label="Select mass suggestion for ${esc(x.reference)}"></td><td>${esc(x.reference)}<br>${esc(x.footprint)}</td><td><select data-mass-source="${esc(x.id)}" aria-label="Mass source for ${esc(x.reference)}">${x.options.map(o=>`<option value="${esc(o.id)}">${esc(o.mass+' · '+o.basis+' · '+o.id)}</option>`).join('')}</select></td><td class="wrap">${x.options.map(o=>`<details><summary>${esc(o.id)}</summary><p>${esc(o.assumptions)}</p><p>${esc(o.source)}</p><p>Uncertainty: ${esc(o.range)}</p></details>`).join('')}</td></tr>`))}<div class="form-actions"><button type="button" id="engMassPreview" class="primary">Preview selected masses</button></div>`,()=>{});$('#engMassPreview').onclick=async()=>{try{const choices=$$('[data-mass-pick]:checked').map(x=>({id:x.dataset.massPick,option:$$('[data-mass-source]').find(s=>s.dataset.massSource===x.dataset.massPick).value}));const plan=await eng6('mass-preview',{choices});review6('Review mass estimates',plan,'EDIT',f=>eng6('mass-apply',{plan,confirmation:f.get('confirmation'),acknowledge:f.has('estimate')}),`<label class="check-label"><input name="estimate" type="checkbox" required>I accept the documented assumptions. These are not independently measured masses.</label>`);}catch(e){toast(e.message,true);}};}
async function variant6(name){const rec=S.data.variants[name];showDialog(name?'Manage independent variant':'Create BOM-only variant',`${name?`<p><b>${esc(name)}</b> · ${rec.locked?'Locked':'Editable'}</p><label class="field"><span>Operation</span><select name="op">${(rec.locked?['unlock']:['lock','metadata','rename','reparent','remove']).map(x=>`<option>${x}</option>`).join('')}</select></label>${field6('New name (rename only)','new')}`:field6('Unique BOM-only variant name','name')}<label class="field"><span>Parent</span><select name="parent">${variantOptions(rec?.parent||S.variant)}</select></label>${name?'':`<label class="field"><span>Mode</span><select name="mode"><option value="derived">Derived · inherit future parent changes</option><option value="pinned">Pinned · copy current fields, flags and variables</option></select></label>`}${field6('Description','description',rec?.description||'')}${field6('Tags, comma-separated','tags',(rec?.tags||[]).join(', '))}<div class="form-actions"><button type="button" id="engVariantPreview" class="primary">Preview variant operation</button></div>`,()=>{});$('#engVariantPreview').onclick=async()=>{try{const f=new FormData($('#dialogBody form')),request={op:name?f.get('op'):'create',name:name||f.get('name'),parent:f.get('parent'),description:f.get('description'),tags:String(f.get('tags')).split(',').map(x=>x.trim()).filter(Boolean)};if(!name)request.mode=f.get('mode');if(request.op==='rename')request.new=f.get('new');const plan=await eng6('variant-preview',{request});review6('Review BOM-only variant',plan,'VARIANT',async g=>{await eng6('variant-apply',{plan,confirmation:g.get('confirmation')});if(request.op==='remove'&&S.variant===name)S.variant=BASE;if(request.op==='rename'&&S.variant===name)S.variant=request.new;});}catch(e){toast(e.message,true);}};}
async function qualification6(){showDialog('Compare a declared land pattern',componentSelect6()+area6('Manufacturer specification JSON (wayricad-land-pattern-1)','spec',{},13)+`<label class="field"><span>Or load a specification file</span><input type="file" id="engSpecFile" accept=".json"></label><div class="notice">Use the included specification example as a schema guide, not as manufacturer data for your part. Coordinates must use the same top-view millimeter origin.</div>${formActions('Run read-only comparison')}`,async f=>{const r=await eng6('qualification',{component:f.get('component'),spec:JSON.parse(f.get('spec'))});report6(r,'Land-pattern and pin-function comparison');});$('#engSpecFile').onchange=async e=>{if(e.target.files[0])$('#dialogBody textarea[name="spec"]').value=await e.target.files[0].text();};}
async function accounts6(){const info=await eng6('info');showDialog('Local reviewers and roles',table6(['Name','Role','Active'],info.reviewers.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.role)}</td><td>${x.active?'Yes':'No'}</td></tr>`))+`<h3>Create a reviewer</h3>${field6('New reviewer name','name')}<label class="field"><span>Role</span><select name="role">${['admin','engineering','supply'].map(x=>`<option>${x}</option>`).join('')}</select></label>${field6('New passphrase (12+ characters)','password','','password','autocomplete="new-password"')}${info.reviewers.length?field6('Existing administrator','admin')+field6('Administrator passphrase','admin_password','','password','autocomplete="current-password"'): '<p class="fine">The first account must have the admin role. Then create separate engineering/supply reviewers.</p>'}${field6('Type REGISTER','confirmation')}${formActions('Register local reviewer')}`,async f=>{await eng6('reviewer-register',Object.fromEntries(f));toast('Reviewer registered locally.');});}
async function policy6(){const p=E6.policy;showDialog('Controlled review policy',`<div class="row">${['engineering','supply'].map(r=>`<label class="check-label"><input name="${r}" type="checkbox" ${p.roles.includes(r)?'checked':''}>Require ${r} approval</label>`).join('')}</div><label class="field"><span>BOM findings that require resolution</span><select name="check_level"><option value="error" ${p.check_level==='error'?'selected':''}>Errors</option><option value="warning" ${p.check_level==='warning'?'selected':''}>Errors and warnings</option></select></label>${[['catalog_required','Require exact catalog membership'],['stock_required','Require a dated stock observation (not full build coverage)'],['qualification_required','Require matched and approved declared land-pattern checks']].map(([k,label])=>`<label class="check-label"><input name="${k}" type="checkbox" ${p[k]?'checked':''}>${label}</label>`).join('')}${field6('Market','market',p.market)}${field6('Observation freshness in hours','freshness_hours',p.freshness_hours,'number')}${formActions('Use this review policy')}`,async f=>{E6.policy={roles:['engineering','supply'].filter(r=>f.has(r)),check_level:f.get('check_level'),catalog_required:f.has('catalog_required'),stock_required:f.has('stock_required'),qualification_required:f.has('qualification_required'),market:f.get('market'),freshness_hours:Number(f.get('freshness_hours'))};E6.report=null;render();});}
async function decision6(target=''){const ctx=E6.report?.data;if(ctx?.schema!=='wayricad-review-context-1')throw Error('Assess the current review context first.');const finding=ctx.issues.find(x=>x.id===target),role=finding&&['LIFECYCLE_RISK','STOCK_NOT_OBSERVED','NO_STOCK'].includes(finding.code)?'supply':'engineering';showDialog('Record a context-bound decision',`<p class="fine">Fingerprint: ${esc(ctx.input_hash)}</p>${finding?`<div class="notice warning">${esc(finding.message)}</div>`:''}<label class="field"><span>Decision kind</span><select name="kind">${(target?['waiver']:['release','qualification','alternate','revoke']).map(x=>`<option>${x}</option>`).join('')}</select></label>${field6('Target finding / qualification / alternate / decision ID','target',target)}${ctx.qualification_targets.length?json6(ctx.qualification_targets):''}${ctx.alternate_targets?.length?json6(ctx.alternate_targets):''}${field6('Reviewer name','reviewer')}<label class="field"><span>Required role</span><select name="role"><option ${role==='engineering'?'selected':''}>engineering</option><option ${role==='supply'?'selected':''}>supply</option></select></label>${field6('Passphrase (never retained by this form)','password','','password','autocomplete="current-password"')}${field6('Reason (10+ characters)','reason')}${field6('Evidence / change-control reference','evidence')}${field6('Expires at (ISO timestamp with time zone)','expires_at',new Date(Date.now()+7*86400000).toISOString())}${field6('Type REVIEW','confirmation')}${formActions('Record signed local decision')}`,async f=>{const d=Object.fromEntries(f);d.input_hash=ctx.input_hash;await eng6('review-decision',{decision:d,policy:E6.policy});const r=await eng6('review-context',{policy:E6.policy});report6(r,'Controlled review assessment');});}
async function evidence6(pid){const p=(await eng6('get',{id:pid})).part;showDialog('Dated evidence · '+p.fields.MPN,`<p class="fine">Exact identity: ${esc(p.fields.Manufacturer)} · ${esc(p.fields.MPN)}. Evidence is a reviewed observation, not a live feed.</p><div class="columns2">${field6('Supplier / manufacturer source','supplier')}${field6('Orderable supplier SKU','sku')}${field6('Numeric observed stock (blank = unknown)','stock','','number')}${field6('Market / region','region','IN')}${field6('Observed timestamp, ISO with offset (do not guess)','observed_at')}${field6('Source URL','source_url','','url')}</div><label class="field"><span>Lifecycle observation</span><select name="lifecycle"><option value="">Unknown / not supplied</option>Active</option>NRND</option>Obsolete</option>End of Life</option></select></label>${field6('Import actor','actor')}<label class="check-label"><input type="checkbox" name="reviewed" required>I reviewed the source and exact orderable part match.</label><div class="form-actions"><button type="button" id="engEvidencePreview" class="primary">Preview evidence</button></div>`,()=>{});$('#engEvidencePreview').onclick=async()=>{try{const f=new FormData($('#dialogBody form')),record={manufacturer:p.fields.Manufacturer,mpn:p.fields.MPN,supplier:f.get('supplier'),sku:f.get('sku'),stock:f.get('stock')===''?null:Number(f.get('stock')),region:f.get('region'),observed_at:f.get('observed_at'),source_url:f.get('source_url'),lifecycle:f.get('lifecycle'),reviewed:f.has('reviewed')};const plan=await eng6('evidence-preview',{part_id:pid,record}),actor=f.get('actor');review6('Review catalog evidence',plan,'IMPORT',g=>eng6('evidence-apply',{plan,actor,confirmation:g.get('confirmation')}));}catch(e){toast(e.message,true);}};}
function buildDefault6(){return {schema:'wayricad-build-plan-1',name:'Multi-build scenario',market:'IN',stock_age_hours:24,inventory_age_days:30,allow_split:false,independent_pools_reviewed:false,supplier_priority:[],builds:[{id:'Build-1',variant:S.variant,boards:1,priority:100,due_date:'',attrition_percent:'0'}],offers:[]};}
async function build6(){const c=E6.build||buildDefault6();showDialog('Multi-build demand and sourcing',`${field6('Scenario name','name',c.name)}<p class="fine">Each row represents a board build. Leave Project blank to use the current workspace; other projects are read from saved files.</p><div id="engBuildRows">${c.builds.map((b,i)=>buildRow6(b,i)).join('')}</div><button type="button" id="engAddBuild">+ Build</button><div class="columns2">${field6('Market','market',c.market)}${field6('Supplier observation maximum age, hours','stock_age_hours',c.stock_age_hours,'number')}${field6('Inventory observation maximum age, days','inventory_age_days',c.inventory_age_days,'number')}${field6('Supplier priority, comma-separated','priority',c.supplier_priority.join(', '))}</div><label class="check-label"><input name="split" type="checkbox" ${c.allow_split?'checked':''}>Allow reviewed split orders</label><label class="check-label"><input name="pools" type="checkbox" ${c.independent_pools_reviewed?'checked':''}>I reviewed the inventory pool IDs as independent, without overlapping listings</label>${area6('Dated offers JSON (full MPN catalog IDs, numeric lead days, price breaks)','offers',c.offers,9)}<label class="field"><span>Load complete scenario JSON</span><input type="file" id="engBuildFile" accept=".json"></label>${formActions('Save session scenario and run')}`,async f=>{const builds=$$('[data-build-row]').map(el=>Object.fromEntries([...el.querySelectorAll('[data-build-key]')].map(x=>[x.dataset.buildKey,['boards','priority'].includes(x.dataset.buildKey)?Number(x.value):x.value])));E6.build={schema:'wayricad-build-plan-1',name:f.get('name'),market:f.get('market'),stock_age_hours:Number(f.get('stock_age_hours')),inventory_age_days:Number(f.get('inventory_age_days')),allow_split:f.has('split'),independent_pools_reviewed:f.has('pools'),supplier_priority:String(f.get('priority')).split(',').map(x=>x.trim()).filter(Boolean),builds,offers:JSON.parse(f.get('offers'))};const r=await eng6('buildplan',{config:E6.build});report6(r,'Multi-build purchasing plan');});$('#engAddBuild').onclick=()=>$('#engBuildRows').insertAdjacentHTML('beforeend',buildRow6({id:'Build-'+($$('[data-build-row]').length+1),variant:S.variant,boards:1,priority:100},$$('[data-build-row]').length));$('#engBuildFile').onchange=async e=>{if(e.target.files[0]){E6.build=JSON.parse(await e.target.files[0].text());$('#dialog').close();build6();}};}
function buildRow6(b,i){return `<fieldset data-build-row class="eng-buildrow"><legend>Build ${i+1}</legend>${[['id','Build ID'],['project','Other project path (optional)'],['variant','Variant'],['boards','Boards'],['priority','Priority (lower first)'],['due_date','Due YYYY-MM-DD (optional)'],['attrition_percent','Attrition %']].map(([k,label])=>`<label><span>${label}</span><input data-build-key="${k}" value="${esc(b[k]??(k==='variant'?BASE:k==='attrition_percent'?'0':''))}" ${['boards','priority'].includes(k)?'type="number"':''}></label>`).join('')}<button type="button" data-act="engRemoveBuild">Remove</button></fieldset>`;}
async function inventory6(){const r=await eng6('inventory-list');showDialog('Enter inventory lot observations',`<div class="notice">Upsert reviewed observations. Omitted lots are kept. Mark scrap or set quantity to zero to retire a lot. Planning does not reserve or deduct stock.</div>${area6('Inventory JSON array','records',r.lots.length?r.lots:[{id:'Lot-1',part_id:'COPY-EXACT-CATALOG-ID',quantity:100,reserved:0,location:'Shelf A',expires:'',status:'available',source:'Physical count record',observed_at:'',notes:''}],13)}${field6('Inventory actor','actor')}<div class="form-actions"><button type="button" id="engInventoryPreview" class="primary">Preview inventory changes</button></div>`,()=>{});$('#engInventoryPreview').onclick=async()=>{try{const f=new FormData($('#dialogBody form')),plan=await eng6('inventory-preview',{records:JSON.parse(f.get('records'))}),actor=f.get('actor');review6('Review inventory observations',plan,'INVENTORY',g=>eng6('inventory-apply',{plan,actor,confirmation:g.get('confirmation')}));}catch(e){toast(e.message,true);}};}
Object.assign(handlers,{
 engTab:async el=>{E6.tab=el.dataset.tab;render();if(E6.tab==='catalog'&&!E6.info){try{E6.info=await eng6('info');if(E6.info.attached)await searchCatalog6();else render();}catch(e){toast(e.message,true);}}},
 engAttach:()=>connect6(false),engCreate:()=>connect6(true),engSearch:()=>{E6.offset=0;return searchCatalog6();},engNext:()=>{E6.offset=E6.page.next_offset;return searchCatalog6();},engPrevious:()=>{E6.offset=Math.max(0,E6.offset-50);return searchCatalog6();},
 engNewPart:()=>editPart6(),engEditPart:el=>editPart6(el.dataset.id),engPart:async el=>{const r=await eng6('get',{id:el.dataset.id});showDialog('Catalog identity · '+r.part.internal_pn,json6(r)+button6('engEditPart','Edit current revision…',`data-id="${esc(el.dataset.id)}"`),()=>{});},
 engHarvest:harvest6,engHarvestFull:async()=>{const r=await eng6('task-status',{id:E6.task.id,include_result:true});downloadJSON6(r.result,'WayriCAD_harvest_plan.json');},engHealth:health6,engSnapshot:()=>download('engineering/snapshot',{}),engNative:()=>{if(!E6.picked.size)throw Error('Select catalog parts first.');return download('engineering/native-export',{ids:[...E6.picked]});},engEvidence:el=>evidence6(el.dataset.id),
 engDownloadReport:()=>downloadJSON6(E6.report.data,'WayriCAD_engineering_report.json'),engPlanDownload:()=>downloadJSON6(E6.pending,'WayriCAD_review_plan.json'),engClearReport:()=>{E6.report=null;render();},
 engSuggest:()=>showDialog('Choose a component',componentSelect6()+formActions('Find candidates'),async f=>{const id=f.get('component');setTimeout(()=>suggestions6(id).catch(e=>toast(e.message,true)),0);}),
 engSuggestSelected:()=>{if(S.selected.size!==1)throw Error('Check exactly one BOM component, then use this action.');return suggestions6([...S.selected][0]);},engSuggestRow:el=>suggestions6(el.dataset.id),engChooseCandidate:chooseCandidate6,
 engMass:masses6,engNewVariant:()=>variant6(),engVariantAction:el=>variant6(el.dataset.name),engUseVariant:async el=>{await switchVariant(el.dataset.name);E6.report=null;render();},
 engQualify:qualification6,engAccounts:accounts6,engReviewPolicy:policy6,engReviewContext:async()=>report6(await eng6('review-context',{policy:E6.policy}),'Controlled review assessment'),engDecision:()=>decision6(),engWaiver:el=>decision6(el.dataset.target),
 engPipelineReview:async()=>{const info=await eng6('info');if(!info.attached)throw Error('Attach a library first.');downloadJSON6({schema:'wayricad-pipeline-1',name:'Controlled_BOM',variants:[S.variant],template:'Purchasing',formats:['csv','xlsx','json'],reports:['checks'],policy:{checks:'error',health:'none',require_stock:false,analytics:'none'},release_control:{library:info.path,policy:E6.policy}},'Controlled_pipeline.json');},
 engBuild:build6,engRemoveBuild:el=>el.closest('[data-build-row]').remove(),engRunBuild:async()=>{if(!E6.build)throw Error('Configure a scenario first.');report6(await eng6('buildplan',{config:E6.build}),'Multi-build purchasing plan');},engOffers:async()=>{const r=await eng6('catalog-offers');E6.build=E6.build||buildDefault6();E6.build.offers=r.offers;toast('Loaded dated offers into the session scenario. Review numeric lead days, markets, prices and pool identities.');build6();},engInventory:inventory6,engInventoryList:async()=>report6(await eng6('inventory-list'),'Current inventory observations'),engVerify:async()=>report6(await eng6('verify'),'Catalog integrity check'),
 engVirtual:()=>{E6.virtual=!E6.virtual;E6.vstart=0;S.view='bom';render();toast(E6.virtual?'Bounded virtual window enabled for ungrouped BOM. Grouped view keeps pagination.':'Standard pagination restored.');}
});
/* Keyboard and catalog selection remain independent from live-editor highlight. */
document.addEventListener('change',e=>{if(e.target.dataset.engSelect){if(e.target.checked)E6.picked.add(e.target.dataset.engSelect);else E6.picked.delete(e.target.dataset.engSelect);}});
document.addEventListener('keydown',e=>{if(e.target.id==='engQuery'&&e.key==='Enter'){e.preventDefault();handlers.engSearch().catch(x=>toast(x.message,true));}if(e.target.getAttribute('role')==='tab'&&['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){const tabs=$$('.eng-tabs [role="tab"]'),i=tabs.indexOf(e.target),n=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;e.preventDefault();tabs[n].focus();tabs[n].click();setTimeout(()=>$$('.eng-tabs [role="tab"]')[n]?.focus(),0);}});
/* Bounded DOM window; the source rows are still held in the existing workspace. */
const gridBefore6=gridTable;
gridTable=function(rows,columns,selectable=true){return gridBefore6(rows,columns,selectable).replace(/<button class="quiet small" data-inspect="([^"]+)"/g,`<button type="button" class="quiet small" data-act="engSuggestRow" data-id="$1" title="Find value / footprint catalog candidates" aria-label="Recommend catalog part">◇</button><button class="quiet small" data-inspect="$1"`);};
const bomBefore6=renderBOM;
renderBOM=function(){return `<div class="eng-bom-tools row"><button type="button" class="small" data-act="engVirtual">${E6.virtual?'✓ Bounded viewport':'Bounded viewport'}</button><button type="button" class="small" data-act="engSuggestSelected">Recommend selected part</button><span class="fine">◇ Find catalog candidates · suggestions never alter parts automatically</span></div>`+bomBefore6();};
let virtualRows6=[],vscroll6=0,vraf6=0;
function virtualWindow6(start){
 const holder=$('#engVirtualWindow');if(!holder)return;
 start=Math.max(0,Math.min(start,Math.max(0,virtualRows6.length-45)));E6.vstart=start;
 const rows=virtualRows6.slice(start,start+45);let html=gridTable(rows,S.columns).replace('<table ',`<table aria-rowcount="${virtualRows6.length+1}" `).replace('id="selectPage"','id="engSelectWindow"');
 let n=start+2;html=html.replace(/<tr data-row=/g,()=>`<tr aria-rowindex="${n++}" data-row=`);
 if(S.directEdit)html=html.replaceAll('editable edit-cell','live-cell edit-cell');
 holder.style.transform=`translateY(${start*40}px)`;holder.innerHTML=html;
 holder.querySelectorAll('td[data-field]').forEach(x=>x.tabIndex=-1);
 overlayGridDrafts();if(typeof paintLink4==='function')paintLink4();if(typeof paintThreshold5==='function')paintThreshold5();
}
function installVirtual6(){
 if(!E6.virtual||S.view!=='bom'||S.data.grouping?.fields?.length)return;
 const table=$('#main table.data-table');if(!table)return;const wrap=table.parentElement;
 virtualRows6=filteredRows();wrap.id='engVirtualViewport';wrap.classList.add('eng-viewport');wrap.tabIndex=0;wrap.setAttribute('role','region');wrap.setAttribute('aria-label','BOM virtual viewport. Arrow keys navigate rows; Control Home or End jumps to the first or last component. Enter edits the focused cell.');
 E6.vstart=Math.min(E6.vstart,Math.max(0,virtualRows6.length-45));vscroll6=E6.vstart*40;
 wrap.innerHTML=`<div class="eng-virtualspacer"><div id="engVirtualWindow"></div></div>`;
 wrap.querySelector('.eng-virtualspacer').style.height=(virtualRows6.length*40+45)+'px';
 virtualWindow6(E6.vstart);wrap.scrollTop=vscroll6;
 const footer=wrap.nextElementSibling;if(footer?.classList.contains('table-footer'))footer.innerHTML=`<span>${virtualRows6.length} matching components · at most 45 data rows rendered · group mode uses pagination</span>`;
 wrap.addEventListener('scroll',()=>{if(document.activeElement?.closest('#engVirtualViewport td input')){wrap.scrollTop=vscroll6;return;}vscroll6=wrap.scrollTop;cancelAnimationFrame(vraf6);vraf6=requestAnimationFrame(()=>{const start=Math.max(0,Math.min(Math.floor(vscroll6/40),Math.max(0,virtualRows6.length-45)));if(start!==E6.vstart)virtualWindow6(start);});});
}
const renderBefore6=render;
render=function(){renderBefore6();installVirtual6();if(S.view==='engineering')$('#main')?.setAttribute('aria-label','Engineering catalog and release control');else $('#main')?.removeAttribute('aria-label');};
const variantOptionsBefore6=variantOptions;
variantOptions=function(value=S.variant){return variantOptionsBefore6(value).replace(/<option value="([^"]*)"([^>]*)>(.*?)<\/option>/g,(all,key,attrs,label)=>{const v=Object.entries(S.data.variants).find(([k])=>esc(k)===key)?.[1];return v?.bom_only?`<option value="${key}"${attrs}>${label} · BOM only${v.locked?' · locked':''}</option>`:all;});};
const revealBefore6=revealLinked4;
revealLinked4=function(explicit=false){if(E6.virtual&&(!busyEditing4()||explicit)){const ids=new Set(S.link.ids||[]);const i=filteredRows().findIndex(r=>ids.has(r.id));if(i>=0)E6.vstart=i;}return revealBefore6(explicit);};
document.addEventListener('change',e=>{if(e.target.id==='engSelectWindow'){for(const row of virtualRows6.slice(E6.vstart,E6.vstart+45)){if(e.target.checked)S.selected.add(row.id);else S.selected.delete(row.id);}render();}});
document.addEventListener('keydown',e=>{
 if(!e.target.closest('#engVirtualViewport')||['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;
 if(!['ArrowDown','ArrowUp','ArrowLeft','ArrowRight','Home','End','PageDown','PageUp'].includes(e.key))return;
 e.preventDefault();e.stopImmediatePropagation();
 const cell=e.target.closest('td[data-field]');let index=cell?virtualRows6.findIndex(r=>r.id===cell.dataset.id):E6.vstart,col=cell?S.columns.indexOf(cell.dataset.field):0;
 if(e.key==='ArrowDown')index++;if(e.key==='ArrowUp')index--;if(e.key==='PageDown')index+=12;if(e.key==='PageUp')index-=12;
 if(e.key==='ArrowLeft')col--;if(e.key==='ArrowRight')col++;if(e.key==='Home'){col=0;if(e.ctrlKey)index=0;}if(e.key==='End'){col=S.columns.length-1;if(e.ctrlKey)index=virtualRows6.length-1;}
 index=Math.min(Math.max(index,0),virtualRows6.length-1);col=Math.min(Math.max(col,0),S.columns.length-1);if(index<0)return;
 const view=$('#engVirtualViewport');virtualWindow6(Math.max(0,index-3));vscroll6=Math.max(0,(index-3)*40);view.scrollTop=vscroll6;
 const target=[...view.querySelectorAll('td[data-id]')].find(x=>x.dataset.id===virtualRows6[index].id&&x.dataset.field===S.columns[col]);if(target){target.tabIndex=0;target.focus({preventScroll:true});}
},true);
// A nonintrusive automatic suggestion cue on a normal BOM row click.
let reuseTimer6;
document.addEventListener('click',e=>{if(S.view!=='bom'||!E6.info?.attached||e.target.closest('button,input,select,textarea'))return;const cell=e.target.closest('td[data-id]');if(!cell)return;const id=cell.dataset.id,seq=++E6.req;clearTimeout(reuseTimer6);reuseTimer6=setTimeout(async()=>{try{const r=await eng6('recommend',{component:id,limit:3});if(seq!==E6.req||S.view!=='bom'||$('#dialog').open)return;$('#reuseCue6')?.remove();const cue=document.createElement('aside');cue.id='reuseCue6';cue.setAttribute('role','status');cue.innerHTML=`<b>${esc(r.component)} · ${r.items.length}${r.items.length===3?'+':''} catalog candidates</b><p>${esc(r.items.map(x=>x.part.fields.MPN).join(' · ')||r.reason||'No matching recorded value and footprint.')}</p>${button6('engSuggestRow','Review candidates',`data-id="${esc(id)}"`)} ${button6('engCloseCue','Dismiss')}`;document.body.append(cue);}catch(_){/* missing/unattached library must not disturb ordinary editing */}},350);});
handlers.engCloseCue=()=>$('#reuseCue6')?.remove();

// Startup moved here so all modules are registered before the first response.
refresh().then(async()=>{if(S.data?.startup_note)toast(S.data.startup_note);try{E6.info=await eng6('info');}catch(_){}const status=await api('link/poll',{});if(status.connected){adoptLink4(status);render();}}).catch(e=>toast(e.message,true));
