'use strict';
/* Local screening and editable grouped BOM. No external fetches or remote code. */
Object.assign(titles,{health:['BOM health','Evidence first. Unknown is not a pass.'],analyzer:['Smart analyzer & consolidation','Find repeat demand and assess standardization without silent substitutions.'],evidence:['Supplier & package evidence','No API keys: import supplier results or review a captured product page.']});
Object.assign(S,{directEdit:true,gridDraft:new Map(),expandedGroups:new Set(),healthReport:null,analysisReport:null,evidencePlan:null});
const readonlyGrid=new Set(['Reference','Qty','Sheet','UUID','Source','Required','OrderQty','LineCost','OrderCost','Item']);
const evidenceFields=['manufacturer','mpn','supplier','sku','stock','observed_at','source_url','package','pin_count','pitch_mm','body_x_mm','body_y_mm','mounting','exposed_pad','pin_numbers','pin_names','lifecycle','moq','order_multiple','lead_time','packaging','region','currency','unit_price','notes','value','tolerance','voltage_rating','power_rating','dielectric'];
function withGridDraft(row){const d=S.gridDraft.get(row.id);return d?{...row,fields:{...row.fields,...d}}:row;}
function pendingGridCount(){return [...S.gridDraft.values()].reduce((a,b)=>a+Object.keys(b).length,0);}
function confirmPendingGrid(){if(!S.gridDraft.size)return true;if(!confirm('Discard unstaged grid edits? Use Review grid edits to keep them first.'))return false;S.gridDraft.clear();return true;}
const beforeRender3=render;
render=function(){beforeRender3();if(S.view==='bom')overlayGridDrafts();if(S.gridDraft.size&&S.view!=='bom')$('#main').insertAdjacentHTML('afterbegin','<div class="notice warning">Unstaged grid edits are not in exports, health or saved workspace yet. <button class="linkbutton" data-view="bom">Return to BOM</button></div>');};
function overlayGridDrafts(){
 for(const cell of $$('#main td[data-field]')){
  if(cell.querySelector('input'))continue;const f=cell.dataset.field;let values=[];
  if(cell.dataset.group){const g=groupById(cell.dataset.group);if(!g||!g.ids.some(id=>Object.hasOwn(S.gridDraft.get(id)||{},f)))continue;values=[...new Set(g.rows.map(r=>String(S.gridDraft.get(r.id)?.[f]??r.fields[f]??'')))];}
  else{const draft=S.gridDraft.get(cell.dataset.id);if(!draft||!Object.hasOwn(draft,f))continue;values=[String(draft[f])];}
  cell.textContent=values.length===1?values[0]:'<mixed>';cell.title='Unstaged draft — review before save/export';cell.classList.add('pending-cell');
 }
}
const beforeSave3=save;
save=async function(){if(S.gridDraft.size){await reviewGrid();toast('Review and stage the grid edits, then Save workspace.');return;}await beforeSave3();};handlers.save=save;
function groupingRows(){const fields=S.data.grouping?.fields||[],raw=!!S.data.grouping?.raw,map=new Map();for(const r of filteredRows()){const k=JSON.stringify(fields.map(f=>raw?(r.raw[r.field_name_sources?.[f]||f]??r.fields[f]??''):(r.fields[f]??'')));if(!map.has(k))map.set(k,[]);map.get(k).push(r);}return [...map].map(([key,rows],i)=>({key:'g'+i,rows,ids:rows.map(r=>r.id),label:fields.map(f=>f+': '+String(rows[0].fields[f]??'—')).join(' · ')}));}
const beforeBOM3=renderBOM;
renderBOM=function(){
 const fields=S.data.grouping?.fields||[];
 const tools=`<section class="panel grid-tools"><div class="toolbar"><button class="${S.directEdit?'primary':'secondary'} small" data-act="toggleDirect">${S.directEdit?'✓ In-grid editing':'Enable in-grid editing'}</button><button class="small" data-act="groupingDialog">Group by ${fields.length?esc(fields.join(' + ')):'— ungrouped'}</button><button class="small" data-act="pasteGrid">Paste table…</button><span class="grow"></span><span id="gridDraftCount" class="fine">${pendingGridCount()} draft cells</span><button class="small primary" data-act="reviewGrid">Review grid edits</button><button class="small" data-act="discardGrid">Discard drafts</button></div><p class="fine grid-help">Double-click a value to type; Enter/Tab queues a draft, Escape cancels. Group cells edit all members shown by the filter. Native files change only after separate APPLY.</p></section>`;
 if(!fields.length){let text=beforeBOM3();if(S.directEdit)text=text.replaceAll('editable edit-cell','live-cell edit-cell').replaceAll('data-field="','tabindex="0" data-field="');return tools+text;}
 const groups=groupingRows();S.visibleGroups=groups;const pageSize=50,pages=Math.max(1,Math.ceil(groups.length/pageSize));S.page=Math.min(S.page,pages-1);
 let html=metrics()+`<section class="panel"><div class="toolbar"><input class="searchbox" id="search" value="${esc(S.search)}" placeholder="Filter components before grouping"><select id="populationFilter"><option value="all">All components</option><option value="fitted" ${S.filter==='fitted'?'selected':''}>Fitted</option><option value="not_fitted" ${S.filter==='not_fitted'?'selected':''}>DNP / DNI</option></select><button data-act="columns">Columns</button><button data-act="undo" ${!S.data.undo?'disabled':''}>↶ Undo</button><button data-act="redo" ${!S.data.redo?'disabled':''}>↷ Redo</button></div><div class="notice warning">Viewing groups only. Mixed MPNs or ratings stay visible as &lt;mixed&gt;; purchasing exports still separate incompatible parts.</div><div class="table-wrap"><table class="data-table"><thead><tr><th>Group</th>${S.columns.map(c=>`<th>${esc(c)}</th>`).join('')}<th>Edit</th></tr></thead><tbody>`;
 for(const g of groups.slice(S.page*pageSize,(S.page+1)*pageSize)){
  const expanded=S.expandedGroups.has(g.label);html+=`<tr class="group-row"><td><button class="quiet small" data-act="expandGroup" data-group="${g.key}">${expanded?'▾':'▸'} ${g.rows.length} parts</button></td>`;
  for(const field of S.columns){const vals=[...new Set(g.rows.map(r=>String(r.fields[field]??'')))];const text=(field==='Reference'||field==='@field:Reference')?g.rows.map(r=>r.ref).join(', '):field==='Qty'?String(g.rows.length):vals.length===1?vals[0]:'<mixed>';
   html+=`<td class="${!readonlyGrid.has(field)&&S.directEdit?'live-cell edit-cell':''} ${vals.length>1&&field!=='Reference'?'mixed-cell':''}" tabindex="0" data-group="${g.key}" data-field="${esc(field)}" title="${esc(text)}">${esc(text||'—')}</td>`;}
  html+=`<td><button class="small" data-act="editGroup" data-group="${g.key}">Edit group…</button></td></tr>`;
  if(expanded)for(const r of g.rows)html+=`<tr class="group-child"><td><button class="quiet small" data-inspect="${esc(r.id)}">↗</button></td>${S.columns.map(f=>`<td class="${!readonlyGrid.has(f)&&S.directEdit?'live-cell edit-cell':''}" tabindex="0" data-id="${esc(r.id)}" data-field="${esc(f)}">${esc(r.fields[f]??'—')}</td>`).join('')}<td></td></tr>`;
 }
 html+=`</tbody></table></div><div class="table-footer"><span>${groups.length} groups over ${filteredRows().length} filtered components</span><div class="row"><button data-act="prevPage" ${!S.page?'disabled':''}>←</button>${S.page+1} / ${pages}<button data-act="nextPage" ${S.page>=pages-1?'disabled':''}>→</button></div></div></section>`;
 return tools+html;
};
function groupById(id){return (S.visibleGroups||[]).find(g=>g.key===id);}
function startInline(cell){
 if(cell.querySelector('input')||readonlyGrid.has(cell.dataset.field))return;
 const field=cell.dataset.field,ids=cell.dataset.group?groupById(cell.dataset.group).ids:[cell.dataset.id];
 const rows=ids.map(id=>S.data.rows.find(r=>r.id===id));
 if(rows.some(r=>(r.generated_fields||[]).includes(r.field_name_sources?.[field]||field))){toast('Generated field: edit the underlying project variable instead.',true);return;}
 const vals=[...new Set(rows.map(r=>String(S.gridDraft.get(r.id)?.[field]??r.raw[r.field_name_sources?.[field]||field]??r.fields[field]??'')))];
 const was=cell.textContent;cell.textContent='';const input=document.createElement('input');input.className='inline-input';input.setAttribute('aria-label','Edit '+field);input.value=vals.length===1?vals[0]:'';input.placeholder=vals.length>1?'Mixed values — type replacement for all':'';cell.append(input);input.focus();input.select();let done=false;
 const finish=cancel=>{if(done)return;done=true;if(cancel){cell.textContent=was;return;}let value=input.value;
  if(Object.hasOwn(flagMap,field)||Object.values(flagMap).includes(field)){if(!/^(true|false|yes|no|1|0)$/i.test(value.trim())){done=false;toast('Use true or false for flags.',true);input.focus();return false;}value=/^(true|yes|1)$/i.test(value.trim());}
  if(field==='Assembly'){value=value.trim().toUpperCase();if(!['FIT','DNP','DNI'].includes(value)){done=false;toast('Use FIT, DNP or DNI.',true);input.focus();return false;}}
  for(const id of ids){const d=S.gridDraft.get(id)||{};d[field]=value;S.gridDraft.set(id,d);}cell.textContent=String(value);cell.classList.add('pending-cell');$('#gridDraftCount').textContent=pendingGridCount()+' draft cells';return true;};
 input.addEventListener('blur',()=>finish(false));input.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();finish(true);cell.focus();}if(e.key==='Enter'||e.key==='Tab'){e.preventDefault();e.stopPropagation();if(finish(false)!==false){const cells=$$('.live-cell'),i=cells.indexOf(cell);(cells[i+(e.shiftKey?-1:1)]||cell).focus();}}});
}
document.addEventListener('dblclick',e=>{const c=e.target.closest('td.live-cell');if(c)startInline(c);});
document.addEventListener('keydown',e=>{if(e.target.matches('td.live-cell')&&['Enter','F2'].includes(e.key)){e.preventDefault();e.stopImmediatePropagation();startInline(e.target);}},true);
window.addEventListener('beforeunload',e=>{if(S.gridDraft.size){e.preventDefault();e.returnValue='';}});
function groupingDialog(){const selected=S.data.grouping?.fields||[],fields=[...new Set(['Value','Footprint','MPN','Manufacturer',...S.data.rows.flatMap(r=>Object.keys(r.fields))])].filter(f=>!['Source','UUID','Qty'].includes(f));showDialog('Group the editable BOM',`<p>Choose any combination of fields. This changes presentation, not electrical equivalence or purchasing grouping.</p><div class="row"><button type="button" data-act="groupPreset" data-fields="Value,Footprint">Value + Footprint</button><button type="button" data-act="groupPreset" data-fields="MPN,Manufacturer">MPN + Manufacturer</button><button type="button" data-act="groupPreset" data-fields="">Ungroup</button></div><div class="checkbox-grid grouping-list">${fields.map(f=>`<label class="check-label"><input name="groupfield" type="checkbox" value="${esc(f)}" ${selected.includes(f)?'checked':''}>${esc(f)}</label>`).join('')}</div><label class="check-label"><input name="raw" type="checkbox" ${S.data.grouping?.raw?'checked':''}>Group raw expressions rather than resolved values</label>${formActions('Apply grouping')}`,async f=>{await api('grouping/settings',{variant:S.variant,fields:f.getAll('groupfield'),raw:!!f.get('raw')});S.page=0;await refresh();});}
function gridEntries(){return [...S.gridDraft].map(([id,changes])=>({ids:[id],changes}));}
async function reviewGrid(entries=gridEntries()){
 if(!entries.length){toast('No grid edits queued. Double-click a cell, or paste a table first.');return;}
 const plan=await api('grid/preview',{variant:S.variant,entries});S.gridPlan={plan,entries,variant:S.variant};
 showDialog('Review BOM edits',`<div class="notice">${plan.affected} affected components · ${plan.events.length} field changes across the reported variants. No schematic files have changed.</div>${plan.warnings.map(w=>`<div class="notice warning">${esc(w)}</div>`).join('')}<div class="table-wrap tall"><table class="data-table"><thead><tr><th>Variant</th><th>Reference</th><th>Field</th><th>Before</th><th>After</th></tr></thead><tbody>${plan.events.slice(0,500).map(e=>`<tr class="${e.variable_loss?'loss-row':''}"><td>${esc(e.variant)}</td><td>${esc(e.reference)}${e.expanded?' (shared)':''}</td><td>${esc(e.field)}</td><td>${esc(e.before)}</td><td>${esc(e.after)}</td></tr>`).join('')}</tbody></table></div><p class="fine">Showing up to 500 changes. <button type="button" class="linkbutton" data-act="saveGridReview">Save complete review JSON</button></p>${plan.variable_losses?'<label class="check-label"><input name="loss" type="checkbox" required>I acknowledge replacement/loss of raw variable expressions.</label>':''}<div class="field"><label>Type EDIT to stage as one undoable operation</label><input name="confirmation" required autocomplete="off"></div>${formActions('Stage reviewed edits')}`,async f=>{const r=await api('grid/apply',{variant:S.gridPlan.variant,entries:S.gridPlan.entries,fingerprint:plan.fingerprint,confirmation:f.get('confirmation'),acknowledge_loss:!!f.get('loss')});for(const entry of S.gridPlan.entries)for(const id of entry.ids){const draft=S.gridDraft.get(id);if(!draft)continue;for(const [field,value] of Object.entries(entry.changes))if(draft[field]===value)delete draft[field];if(!Object.keys(draft).length)S.gridDraft.delete(id);}await refresh();toast(r.affected+' components edited. Save workspace; native APPLY remains separate.');});
}
function saveJSON(data,name){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function pasteGrid(){showDialog('Paste a BOM table',`<p class="fine">Paste CSV or spreadsheet TSV with a Reference header and field headings, such as Value, Footprint or MPN. Use exact references (comma-separated lists allowed), not R1–R8 ranges. This changes fields; it does not add/delete schematic symbols.</p><textarea id="gridPasteText" rows="12" placeholder="Reference&#9;Value&#9;Footprint&#10;R1&#9;10k&#9;Resistor_SMD:R_0603_1608Metric"></textarea><button class="primary spaced" data-act="previewPasteGrid">Review pasted changes</button>`);}
function staleReport(report){return !report||report.variant!==S.variant||report.revision!==S.data.revision;}
function reportTop(kind){return `<div class="toolbar panel"><button class="primary" data-act="${kind==='health'?'runHealth':'runAnalyzer'}">${kind==='health'?'Run BOM health':'Run smart analyzer'}</button><button data-act="healthSettings">Health settings</button><button data-act="downloadReport" data-kind="${kind}">Export fresh report JSON</button><button data-view="evidence">Supplier evidence →</button></div>`;}
function miniStats(items){return '<div class="health-metrics">'+items.map(([name,value])=>`<article class="metric"><div class="metric-label">${esc(name)}</div><div class="metric-value">${esc(value)}</div></article>`).join('')+'</div>';}
function safeLink(url,label){try{const u=new URL(url);if(u.protocol!=='https:')return esc(label||url);return `<a href="${esc(u.href)}" target="_blank" rel="noopener noreferrer">${esc(label||url)}</a>`;}catch{return '';}}
function renderHealth(){
 const r=S.healthReport;let out=reportTop('health')+'<div class="notice">Local rules screen the current workspace, saved geometry and reviewed evidence. No score or green badge can qualify the physical part. Health is advisory; existing export checks are separate.</div>';
 if(!r)return out+'<section class="panel panel-body"><h2>Check the selected part, not just the label.</h2><p>Read local footprint pads, compare symbol pin numbers, review exact-MPN package evidence, and aggregate fitted demand against recent supplier observations.</p><p>Without part evidence or local footprint geometry, the result will say Unknown. Set library roots under Health settings.</p></section>';
 if(staleReport(r))out+='<div class="notice warning">This report belongs to an older workspace revision or another variant. Run it again. Files changed outside this app also require a new run.</div>';
 const x=r.summary;out+=miniStats([['Errors',x.errors],['Warnings',x.warnings],['Unknowns',x.unknowns],['Geometry read',x.geometry_read+' / '+x.components],['Stock observations cover',x.stock_observed_covered+' / '+x.purchasing_identities]]);
 out+=`<section class="panel"><div class="panel-title"><h2>Prioritized findings</h2><span class="fine">${esc(r.generated_at)} · ${esc(r.variant)}</span></div><div class="table-wrap tall"><table class="data-table"><thead><tr><th>Severity</th><th>References</th><th>Check</th><th>Assessment / next action</th></tr></thead><tbody>${r.issues.slice(0,600).map(i=>`<tr><td><span class="pill health-${esc(i.severity)}">${esc(i.severity)}</span></td><td class="ref">${esc(i.reference)}</td><td>${esc(i.code)}</td><td class="wrap-cell">${esc(i.message)}</td></tr>`).join('')||'<tr><td colspan="4">No implemented rules fired. This is not engineering qualification.</td></tr>'}</tbody></table></div><p class="fine panel-body">Showing up to 600 findings; the JSON report contains all findings and source evidence IDs.</p></section>`;
 out+=`<section class="panel spaced"><div class="panel-title"><h2>Fitted demand and stock evidence</h2></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Exact part</th><th>Refs</th><th>Required</th><th>Stock assessment</th><th>Observed offers (not summed)</th><th>Research</th></tr></thead><tbody>${r.demand.map(d=>`<tr><td>${esc(d.manufacturer)}<br><b>${esc(d.mpn||'MPN missing')}</b></td><td>${esc(d.references.join(', '))}</td><td>${d.required}</td><td>${esc(d.stock.status)}</td><td class="wrap-cell">${d.stock.offers.map(o=>`${esc(o.supplier)}: ${o.stock??'unknown'} · ${o.age_hours??'?'} h · order ${o.order_quantity} ${o.reasons.length?'('+esc(o.reasons.join(', '))+')':''} ${safeLink(o.source_url,'source')}`).join('<br>')||'No exact manufacturer + MPN evidence'}</td><td>${safeLink(d.links.DigiKey,'DigiKey')} · ${safeLink(d.links.Mouser,'Mouser')}</td></tr>`).join('')}</tbody></table></div></section>`;
 out+=`<section class="panel spaced"><div class="panel-title"><h2>Part-by-part inspection</h2></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Reference</th><th>Footprint</th><th>Geometry source</th><th>Unique pads</th><th>Package screening</th><th>Details</th></tr></thead><tbody>${r.parts.map(p=>`<tr><td>${esc(p.reference)}</td><td>${esc(p.footprint)}</td><td>${esc(p.inspection.selected_source)}</td><td>${p.inspection.selected?.unique_electrical_pads??'Unknown'}</td><td>${esc(p.package_status)}</td><td><button data-act="inspectHealthPart" data-id="${esc(p.id)}">Inspect</button></td></tr>`).join('')}</tbody></table></div></section>`;
 return out+'<div class="notice warning spaced">'+r.limits.map(esc).join('<br>')+'</div>';
}
function renderAnalyzer(){const r=S.analysisReport;let out=reportTop('analysis')+'<div class="notice">This explainable rules engine needs no paid AI or API. Consolidation candidates are proposals, never automatic part substitutions.</div>';if(!r)return out+'<section class="panel panel-body"><h2>Assess opportunities</h2><p>Recognize passive value spellings, aggregate identical manufacturer/MPN demand, and flag possible standardization groups with conflicting or missing ratings.</p></section>';if(staleReport(r))out+='<div class="notice warning">Analysis is stale. Run it again after changes.</div>';
 out+=miniStats([['Candidate groups',r.summary.candidate_groups],['Equivalent-label groups',r.summary.normalization_groups],['Exact repeated identities',r.summary.exact_repeat_identities]]);
 out+=`<section class="panel"><div class="panel-title"><h2>Consolidation assessment</h2></div><div class="table-wrap"><table class="data-table"><thead><tr><th>References / value</th><th>Footprint / identities</th><th>Assessment</th><th>Engineering review</th></tr></thead><tbody>${r.consolidation_candidates.map((c,i)=>`<tr><td>${esc(c.references.join(', '))}<br>${esc(c.normalized_value)}</td><td>${esc(c.footprint)}<br>${c.identities.map(p=>esc(p.manufacturer+' / '+p.mpn)).join('<br>')}</td><td class="wrap-cell"><b>${esc(c.status)}</b><br>Conflicts: ${esc(c.differing_constraints.join(', ')||'none recorded')}<br>Missing: ${esc(c.missing_constraints.join(', '))}</td><td><button data-act="selectCandidate" data-candidate="${i}">Inspect/edit members</button><p class="fine">No qualification or savings inferred.</p></td></tr>`).join('')||'<tr><td colspan="4">No same-value/same-footprint different-identity groups were found.</td></tr>'}</tbody></table></div></section>`;
 out+=`<section class="panel spaced"><div class="panel-title"><h2>Equivalent passive value labels</h2></div><div class="table-wrap"><table class="data-table"><thead><tr><th>References</th><th>Labels</th><th>Normalized meaning</th><th>Review</th></tr></thead><tbody>${r.normalization_opportunities.map((n,i)=>`<tr><td>${esc(n.references.join(', '))}</td><td>${esc(n.values.join(' / '))}</td><td>${esc(n.normalized)}</td><td><button data-act="normalizeCandidate" data-normalize="${i}">Review label edit…</button></td></tr>`).join('')||'<tr><td colspan="4">No equivalent-label opportunities found.</td></tr>'}</tbody></table></div></section>`;
 out+=`<section class="panel spaced"><div class="panel-title"><h2>Repeat demand for exact manufacturer + MPN</h2></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Manufacturer / MPN</th><th>References</th><th>Per board</th><th>Total required</th></tr></thead><tbody>${r.exact_identity_aggregation.map(d=>`<tr><td>${esc(d.manufacturer+' / '+d.mpn)}</td><td>${esc(d.references.join(', '))}</td><td>${d.per_board}</td><td>${d.required}</td></tr>`).join('')}</tbody></table></div></section>`;return out+`<div class="notice warning spaced">${esc(r.warning)}</div>`;
}
function renderEvidence(){const records=S.data.evidence||[];return `<div class="notice">The app does not fetch distributor stock. Use supplier websites in your browser, then import their results. A free website account may be needed; no API keys are required here.</div><div class="health-steps"><section class="panel panel-body"><h2>1 · Prepare a supplier request</h2><p>The request file includes only fitted, BOM-included demand for this variant. This app does not upload it; review private part data before sending it.</p><div class="row"><button data-act="supplierRequest" data-supplier="DigiKey">DigiKey CSV</button><button data-act="supplierRequest" data-supplier="Mouser">Mouser CSV</button></div><p>${safeLink('https://www.digikey.in/en/mylists','Open DigiKey myLists')} · ${safeLink('https://www.mouser.in/en/bomtool/','Open Mouser FORTE')}</p></section><section class="panel panel-body"><h2>2 · Bring back evidence</h2><p>Import CSV/TSV or values-only XLSX with a column-mapping preview. Or use the included optional browser capture extension on an opened product page.</p><button class="primary" data-act="importEvidence">Import supplier / capture file…</button><button class="spaced" data-act="manualEvidence">Add reviewed part evidence…</button></section><section class="panel panel-body"><h2>3 · Screen, then resolve</h2><p>Review exact MPN suffix, manufacturer, package, observation time and market. Numeric stock is required; “in stock” alone is not a quantity.</p><button data-view="health">Run BOM health →</button><p class="fine">Default stock freshness: 24 hours. No CAPTCHA bypass, cookie harvesting, background crawling or fabricated availability.</p></section></div><section class="panel spaced"><div class="panel-title"><h2>Evidence ledger</h2><span>${records.length} records</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Manufacturer / MPN</th><th>Supplier / SKU</th><th>Observed</th><th>Stock / market</th><th>Package / pins</th><th>Source</th><th></th></tr></thead><tbody>${records.slice(-500).reverse().map(r=>`<tr><td>${esc(r.manufacturer)}<br><b>${esc(r.mpn)}</b></td><td>${esc(r.supplier)}<br>${esc(r.sku)}</td><td>${esc(r.observed_at||'Undated')}</td><td>${r.stock??'Unknown'} / ${esc(r.region||'?')}</td><td>${esc(r.package)} / ${r.pin_count??'?'}</td><td>${safeLink(r.source_url,'Open source')}</td><td><button data-act="removeEvidence" data-id="${esc(r.id)}">Remove</button></td></tr>`).join('')||'<tr><td colspan="7">No evidence imported. Unknown stock will remain unknown.</td></tr>'}</tbody></table></div></section>`;}
function healthSettings(){const s={stock_age_hours:24,region:'IN',dimension_tolerance_mm:.05,library_roots:[],board_path:'',...S.data.health_settings};showDialog('BOM health settings',`<div class="field-row"><div class="field"><label>Stock freshness (hours)</label><input name="stock_age_hours" type="number" min="0.01" max="8760" step="0.01" value="${s.stock_age_hours}"></div><div class="field"><label>Market / region (must match evidence)</label><input name="region" value="${esc(s.region)}" placeholder="IN"></div></div><div class="field"><label>Additional footprint library roots (one directory per line)</label><textarea name="roots" placeholder="C:\\Program Files\\KiCad\\10.0\\share\\kicad\\footprints">${esc(s.library_roots.join('\n'))}</textarea><small>Project fp-lib-table, common install directories and KICAD10_FOOTPRINT_DIR are also checked. No full-disk scan.</small></div><div class="field"><label>Optional saved .kicad_pcb path</label><input name="board" value="${esc(s.board_path)}"><small>Blank uses the project filename. Read only; active variant may differ from saved PCB.</small></div><div class="field"><label>Package-name dimension screening tolerance (mm)</label><input name="tolerance" type="number" min="0" max="1" step="0.01" value="${s.dimension_tolerance_mm}"></div>${formActions('Save health settings')}`,async f=>{await action('health/settings',{settings:{stock_age_hours:Number(f.get('stock_age_hours')),region:f.get('region').trim(),library_roots:f.get('roots').split('\n').map(s=>s.trim()).filter(Boolean),board_path:f.get('board').trim(),dimension_tolerance_mm:Number(f.get('tolerance'))}},'Health settings saved.');});}
function importEvidence(){S.evidencePayload=null;S.evidencePlan=null;showDialog('Import supplier or browser evidence',`<p class="fine">CSV, TSV, values-only XLSX, or WayriCAD capture JSON. Only explicitly imported files are read. Formula cells are rejected; legacy .xls is not supported.</p><div class="field"><label>File</label><input type="file" id="evidenceFile" accept=".csv,.tsv,.xlsx,.json"></div><div class="field"><label>Or paste CSV/TSV/JSON</label><textarea id="evidenceText" rows="5"></textarea></div><div class="field-row"><div class="field"><label>Worksheet index (XLSX; 0-based)</label><input type="number" min="0" value="0" id="evidenceSheet"></div><div class="field"><label>Header row index (0-based)</label><input type="number" min="0" value="0" id="evidenceHeader"></div></div><button data-act="inspectEvidenceFile">Read headers / JSON</button><div id="evidenceMapping" class="spaced"></div><div id="evidencePreview" class="spaced"></div>`);}
async function readEvidenceFile(){const file=$('#evidenceFile').files[0];if(file&&file.size>10*1024*1024)throw Error('Files are limited to 10 MiB.');if(file?.name.toLowerCase().endsWith('.xlsx')){const arr=new Uint8Array(await file.arrayBuffer());let str='';for(let i=0;i<arr.length;i+=8192)str+=String.fromCharCode(...arr.subarray(i,i+8192));return {format:'xlsx',base64:btoa(str),sheet_index:Number($('#evidenceSheet').value),header_index:Number($('#evidenceHeader').value)};}const text=file?await file.text():$('#evidenceText').value;return {format:text.trim().startsWith('{')?'json':'csv',text,header_index:Number($('#evidenceHeader').value)};}
async function inspectEvidenceFile(){const payload=await readEvidenceFile();S.evidencePayload=payload;if(payload.format==='json'){await previewEvidence(payload);return;}const info=await api('evidence/inspect',{payload});$('#evidenceMapping').innerHTML=`<h3>Map supplier columns</h3><p class="fine">${info.rows} rows. ${info.sheets.length?'Worksheets: '+esc(info.sheets.join(', ')):''} Choose exact manufacturer MPN, not a suggested alternate or supplier SKU.</p><div class="mapping-grid">${evidenceFields.map(f=>`<label>${esc(f)}<select data-evidence-map="${f}"><option value="">Do not import</option>${info.headers.map(h=>`<option value="${esc(h)}" ${info.mapping[f]===h?'selected':''}>${esc(h)}</option>`).join('')}</select></label>`).join('')}</div><div class="field-row"><div class="field"><label>Supplier fallback</label><select id="evidenceSupplier"><option>DigiKey</option><option>Mouser</option><option>Manual</option></select></div><div class="field"><label>Market fallback</label><input id="evidenceRegion" value="IN"></div></div><div class="field"><label>Observation date/time fallback (leave blank when unknown)</label><input id="evidenceDate" placeholder="2026-09-09T10:00:00Z"></div><div class="field"><label>Source URL fallback (supplier BOM result page)</label><input id="evidenceURL" placeholder="https://..."></div><button class="primary" data-act="previewMappedEvidence">Preview evidence</button>`;$('#evidencePreview').innerHTML='';}
async function previewMappedEvidence(){const current=await readEvidenceFile();if(JSON.stringify(current)!==JSON.stringify(S.evidencePayload))throw Error('File or table settings changed. Read headers again.');const mapping={};$$('[data-evidence-map]').forEach(el=>{if(el.value)mapping[el.dataset.evidenceMap]=el.value;});await previewEvidence({...current,mapping,supplier:$('#evidenceSupplier').value,region:$('#evidenceRegion').value,observed_at:$('#evidenceDate').value,source_url:$('#evidenceURL').value});}
async function previewEvidence(payload){const plan=await api('evidence/preview',{payload});S.evidencePlan={plan,payload};const html=`<div class="notice warning">${esc(plan.warning)}</div>${plan.errors.map(e=>`<p class="error-text">Row ${e.row}: ${esc(e.message)}</p>`).join('')}<div class="table-wrap tall"><table class="data-table"><thead><tr><th>MPN / manufacturer</th><th>Stock / timestamp</th><th>Package</th><th>Identity match</th></tr></thead><tbody>${plan.items.slice(0,100).map(({record:r,match})=>`<tr><td>${esc(r.mpn)}<br>${esc(r.manufacturer||'MANUFACTURER MISSING')}</td><td>${r.stock??'Unknown'}<br>${esc(r.observed_at||'UNDATED')}</td><td>${esc(r.package)}</td><td>${esc(match)}</td></tr>`).join('')}</tbody></table></div><p class="fine">${plan.items.length} records (first 100 shown). Import does not overwrite component fields. <button data-act="saveEvidenceReview" class="linkbutton">Save complete review</button></p><label class="check-label"><input id="evidenceReviewed" type="checkbox">I reviewed the exact manufacturer/MPN, stock, market and source date. This does not authenticate the source.</label><div class="field"><label>Type IMPORT</label><input id="evidenceConfirm"></div><button class="primary" data-act="applyEvidence" ${plan.errors.length?'disabled':''}>Import reviewed evidence</button>`;if($('#evidencePreview'))$('#evidencePreview').innerHTML=html;else showDialog('Review part evidence',html);}
function manualEvidence(){showDialog('Add package / stock evidence',`<p class="fine">Copy facts for the exact orderable manufacturer MPN from the source. Leave unknowns blank. Package-family names and pin counts alone never certify a match.</p><div class="mapping-grid">${evidenceFields.map(f=>`<label>${esc(f)}<input name="${f}" ${f==='mpn'?'required':''} value="${f==='supplier'?'Manual':f==='region'?'IN':''}" placeholder="${f==='pin_names'?'JSON object: {&quot;1&quot;:&quot;GND&quot;}':f==='pin_numbers'?'1,2,3':f==='mounting'?'SMD / THT':f==='observed_at'?'ISO date, or blank':''}"></label>`).join('')}</div>${formActions('Review evidence')}`,async f=>{const record=Object.fromEntries(f.entries());setTimeout(()=>previewEvidence({format:'manual',record}).catch(e=>toast(e.message,true)),0);});}
Object.assign(handlers,{
 toggleDirect:()=>{S.directEdit=!S.directEdit;render();},groupingDialog,
 groupPreset:el=>{const fields=el.dataset.fields.split(',');$$('[name=groupfield]').forEach(i=>i.checked=fields.includes(i.value));},
 expandGroup:el=>{const g=groupById(el.dataset.group);S.expandedGroups.has(g.label)?S.expandedGroups.delete(g.label):S.expandedGroups.add(g.label);render();},
 editGroup:el=>editDialog(groupById(el.dataset.group).ids,'Value'),
 reviewGrid:()=>reviewGrid(),discardGrid:()=>{if(confirmPendingGrid())render();},pasteGrid,
 previewPasteGrid:async()=>{const r=await api('grid/paste',{variant:S.variant,text:$('#gridPasteText').value});await reviewGrid(r.entries);},
 saveGridReview:()=>saveJSON(S.gridPlan.plan,'WayriCAD_grid_edit_review.json'),
 runHealth:async()=>{toast('Reading local geometry and evidence…');S.healthReport=await api('health/run',{variant:S.variant});render();},
 runAnalyzer:async()=>{S.analysisReport=await api('analyzer/run',{variant:S.variant});render();},healthSettings,importEvidence,manualEvidence,inspectEvidenceFile,previewMappedEvidence,
 saveEvidenceReview:()=>saveJSON(S.evidencePlan.plan,'WayriCAD_evidence_import_review.json'),
 applyEvidence:async()=>{const p=S.evidencePlan;await api('evidence/apply',{payload:p.payload,fingerprint:p.plan.fingerprint,confirmation:$('#evidenceConfirm').value,reviewed:$('#evidenceReviewed').checked});$('#dialog').close();await refresh();toast('Evidence imported. Run BOM health to assess it.');},
 removeEvidence:async el=>{if(confirm('Remove this observation from the local ledger? Undo can restore it.'))await action('evidence/remove',{ids:[el.dataset.id]},'Evidence removed.');},
 supplierRequest:el=>originalDownload('supplier/request',{supplier:el.dataset.supplier}),
 downloadReport:el=>originalDownload('health/export',{kind:el.dataset.kind}),
 inspectHealthPart:el=>{const p=S.healthReport.parts.find(p=>p.id===el.dataset.id);showDialog(p.reference+' · Read-only evidence',`<p>Selected geometry source: ${esc(p.inspection.selected_source)}. Full pad positions, file hash, symbol pin map and matched evidence IDs follow.</p><pre class="json-inspection">${esc(JSON.stringify(p,null,2))}</pre>`);},
 selectCandidate:el=>{if(staleReport(S.analysisReport))throw Error('Run a fresh analysis first.');const c=S.analysisReport.consolidation_candidates[Number(el.dataset.candidate)];S.selected=new Set(c.ids);S.view='bom';S.search='';S.page=0;render();editDialog(c.ids,'MPN');},
 normalizeCandidate:el=>{if(staleReport(S.analysisReport))throw Error('Run a fresh analysis first.');const c=S.analysisReport.normalization_opportunities[Number(el.dataset.normalize)];editDialog(c.ids,'Value');}
});
// Upgrade the existing modal editor to the same reviewed transaction. Population
// shortcuts remain separate explicit decisions; no automatic part substitutions.
const beforeEditDialog3=editDialog;
editDialog=function(ids=[...S.selected],field='MPN'){
 if(!ids.length){toast('Select components first.');return;}
 const r=S.data.rows.find(r=>r.id===ids[0]);const value=ids.length===1?(r.raw[r.field_name_sources?.[field]||field]??r.fields[field]??''):'';
 showDialog(ids.length===1?'Edit '+r.ref:'Edit '+ids.length+' components',`<p class="fine">Edit real component properties, including Value and Footprint. Review shows shared-sheet and inherited-variant effects. It does not change the schematic symbol definition.</p><div class="field"><label>Field</label><input name="field" id="editField" list="fieldNames" value="${esc(field)}"><datalist id="fieldNames">${allFields().map(f=>`<option value="${esc(f)}">`).join('')}</datalist></div><div class="field"><label>Raw value / expression</label><textarea name="value" id="editValue">${esc(value)}</textarea></div><label class="check-label"><input type="checkbox" name="reset">Reset workspace override to default/native value</label>${formActions('Preview changes')}`,async f=>{
  const key=f.get('field').trim();let value=f.get('reset')?null:f.get('value');if(value!==null&&(Object.hasOwn(flagMap,key)||Object.values(flagMap).includes(key))){if(!/^(true|false|yes|no|1|0)$/i.test(value.trim()))throw Error('Flags require true/false.');value=/^(true|yes|1)$/i.test(value.trim());}
  if(key==='Assembly'&&value!==null)value=value.trim().toUpperCase();const changes={[key]:value};if(key==='Assembly'&&value===null)changes.dnp=null;
  setTimeout(()=>reviewGrid([{ids,changes}]).catch(e=>toast(e.message,true)),0);
 });
};
// Grid drafts are not silently discarded by changing projects or sample data.
$('#openButton').addEventListener('click',e=>{if(!confirmPendingGrid()){e.stopImmediatePropagation();e.preventDefault();}},true);
