'use strict';
/* Create-only native libraries. Preview and explicit CREATE are separate operations. */
const L8={request:null,plan:null};
const libraryPrior8=renderEngineering;
renderEngineering=function(){return `<section class="panel library-create-bar8"><div class="toolbar"><div><b>KiCad symbols + footprints + 3D models</b><p class="fine">Create native libraries directly. No pre-existing catalogue is required.</p></div><span class="grow"></span>${b8('libraryCreate8','Create KiCad library…')}</div></section>`+libraryPrior8();};
const renderLibraryPrior8=render;
render=function(){const value=renderLibraryPrior8();if(!S.data?.project&&S.view==='engineering'&&!$('#newNativeLibrary8')){const bar=document.createElement('div');bar.id='newNativeLibrary8';bar.className='toolbar';bar.innerHTML='<span>Create symbols, footprints and models without an existing parts library.</span><span class="grow"></span>'+b8('libraryCreate8','Create KiCad library…');$('#main').prepend(bar);}return value;};
const harvestPrior8=handlers.engHarvest;
handlers.engHarvest=async()=>{E6.info=await eng6('info');if(!E6.info.attached)return createLibrary8('projects');return harvestPrior8();};
handlers.engExport=handlers.engSnapshot;
function librarySource8(){return S.data?.project?.pro_path||S.data?.project?.path||S.data?.project_path||'';}
async function createLibrary8(mode){
 try{E6.info=await eng6('info');}catch(_){/* independent blank library creation remains possible */}
 const previous=L8.request||{},defaultMode=mode||previous.mode||(E6.info?.attached&&E6.picked.size?'catalogue':S.data?.project?'projects':'empty');
 showDialog('Create KiCad parts library',`<div class="notice">This creates a <b>new native library folder</b>, not just a catalogue database. Symbols and pad geometry must come from real saved sources; missing geometry is never invented. No existing KiCad library tables are changed.</div><div class="columns2"><label class="field"><span>Part source</span><select name="mode" id="libraryMode8">${[['empty','Empty library + new local catalogue'],['projects','Harvest projects + create catalogue automatically'],['catalogue','Selected parts from attached catalogue']].map(([v,l])=>`<option value="${v}" ${v===defaultMode?'selected':''} ${v==='catalogue'&&!E6.info?.attached?'disabled':''}>${l}</option>`).join('')}</select></label>${field6('Library nickname','name',previous.name||'WayriCADParts')}${field6('New destination folder (absolute path)','destination',previous.destination||'')}${field6('Author / import actor','actor',previous.actor||'Local user')}</div><p class="fine">The parent folder must exist. Example: C:/Users/You/Documents/MyParts (MyParts must be new). Avoid the plugin installation directory.</p><section id="libraryProjects8">${area6('Saved projects or source folders, one per line','projects',(previous.projects||[librarySource8()]).filter(Boolean).join('\n'),4)}<label class="check-label"><input name="recursive" type="checkbox" ${previous.recursive?'checked':''}>Include subdirectories of those source folders</label><label class="check-label"><input name="all_variants" type="checkbox" ${previous.all_variants?'checked':''}>Capture all variants</label><label class="check-label"><input name="partial_projects" type="checkbox">Explicitly allow successful projects despite failed scans</label><details><summary>Custom symbol/footprint/model directories and variables</summary>${area6('Asset resolution JSON','asset_options',previous.asset_options||{},4)}</details></section><section id="libraryCatalogue8"><p><b>${E6.picked.size} selected catalogue identities.</b> Multiple geometry observations may require explicit source-set choices.</p><label class="check-label"><input name="all_parts" type="checkbox">Publish all catalogue identities instead (maximum 10,000)</label>${area6('Optional source-set choices JSON: part ID → asset-set ID','choices',previous.choices||{},3)}</section><label class="check-label"><input name="require_complete" type="checkbox" ${previous.require_complete===false?'':'checked'}>Require every assigned asset reference to be captured (recommended)</label><p class="fine">Unchecked permits explicitly reported partial libraries. An unassigned model is not the same as a missing assigned model. New model paths point to this destination; relocation requires relinking.</p>${formActions('Preview library creation')}`,async f=>{
  const r={mode:f.get('mode'),name:f.get('name'),destination:f.get('destination'),actor:f.get('actor'),require_complete:f.has('require_complete'),recursive:f.has('recursive'),all_variants:f.has('all_variants'),allow_partial_projects:f.has('partial_projects')};
  if(r.mode==='projects'){r.projects=String(f.get('projects')).split('\n').map(x=>x.trim()).filter(Boolean);r.asset_options=JSON.parse(f.get('asset_options')||'{}');}
  if(r.mode==='catalogue'){r.library=E6.info.path;r.ids=[...E6.picked];r.all_parts=f.has('all_parts');r.choices=JSON.parse(f.get('choices')||'{}');}
  L8.request=r;L8.task=await api('library/preview-start',{request:r});setTimeout(pollLibrary8,60);
 });
 const update=()=>{const m=$('#libraryMode8').value;$('#libraryProjects8').hidden=m!=='projects';$('#libraryCatalogue8').hidden=m!=='catalogue';};$('#libraryMode8').onchange=update;update();
}
async function pollLibrary8(){if(!L8.task)return;try{const t=await api('library/task-status',{id:L8.task.id});if(t.state==='ready'){L8.plan=t.result;L8.task=null;libraryReview8();return;}if(t.state==='running'){showDialog('Preparing KiCad library',`<p role="status">${esc(t.message)}</p><progress aria-label="Library preparation progress" max="${t.total||1}" value="${t.current||0}"></progress><p class="fine">Preview only. Destination remains unchanged.</p>${b8('libraryCancel8','Cancel preparation')}`);setTimeout(pollLibrary8,300);}else{L8.task=null;showDialog(t.state==='canceled'?'Preparation canceled':'Library preparation failed',`<div class="notice warning">${esc(t.message)}</div><p>No destination directory was created.</p>${b8('libraryCreate8','Change options…')}`);}}catch(e){L8.task=null;toast(e.message,true);}}
handlers.libraryCancel8=async()=>{if(L8.task)await api('library/task-cancel',{id:L8.task.id});};
function libraryReview8(){const p=L8.plan;showDialog('Review new KiCad library',`<div class="notice"><b>No destination files have been created.</b> Inspect the paths and source warnings before applying.</div><p><code>${esc(p.request.destination)}</code></p>${table6(['Output','Count / location'],[
 `<tr><td>Symbols</td><td>${p.counts.symbols} · ${esc(p.request.name)}.kicad_sym</td></tr>`,
 `<tr><td>Footprints</td><td>${p.counts.footprints} · ${esc(p.request.name)}.pretty/</td></tr>`,
 `<tr><td>3D originals</td><td>${p.counts.models} · ${esc(p.request.name)}.3dshapes/</td></tr>`,
 `<tr><td>${p.new_catalogue?'New catalogue':'Existing catalogue unchanged'}</td><td>${esc(p.catalogue_path)} · ${p.counts.catalogue_parts} parts</td></tr>`])}${p.warnings.length?`<div class="notice warning">${p.warnings.length} warnings. Partial or missing assets must not be treated as qualified.</div>${json6(p.warnings)}`:''}<details><summary>Native file hashes and source revision review</summary><pre>${esc(JSON.stringify({source:p.source,files:p.native_files,mapping:p.mapping},null,2))}</pre></details><div class="row">${b8('libraryPlanSave8','Save complete review JSON')}${b8('libraryCreate8','Change options…')}</div><label class="check-label"><input name="attach" type="checkbox" checked>Attach the resulting catalogue to this session</label><label class="check-label"><input name="remember" type="checkbox">Remember this catalogue on this computer</label>${field6('Type CREATE','confirmation')}${formActions('Create reviewed library')}`,async f=>{
  const result=await api('library/apply',{review_id:p.review_id,confirmation:f.get('confirmation'),attach:f.has('attach'),remember:f.has('remember')});L8.plan=null;
  await refresh();E6.info=await eng6('info');E6.query='';E6.offset=0;F8.category=F8.manufacturer=F8.lifecycle='';A7.filters=[];A7.has=A7.status=A7.kind='';if(E6.info.attached){E6.page=await eng6('search',{query:'',limit:50,summary:true});E6.tab='catalog';S.view='engineering';}
  render();setTimeout(()=>showDialog('KiCad library created',`<div class="notice success">Created and checksum-verified the new directory. Source designs and existing KiCad library tables were not changed.</div><dl class="created-paths8"><dt>Symbol library</dt><dd>${esc(result.symbol_library)}</dd><dt>Footprint library</dt><dd>${esc(result.footprint_library)}</dd><dt>3D models</dt><dd>${esc(result.model_directory)}</dd><dt>Local catalogue</dt><dd>${esc(result.catalogue_path)}</dd></dl><p>In KiCad, add the symbol and footprint libraries in <b>Preferences → Manage Symbol / Footprint Libraries</b>, using the nickname <b>${esc(result.request.name)}</b> for both. Choose project-local or global scope there. The new folder also contains table snippets to merge, not replacements for existing tables.</p><p class="fine">This is a native-library snapshot. Further catalogue edits do not silently rewrite it. Actual KiCad host loading still needs target-machine verification.</p>${json6(result)}`),40);
 });}
Object.assign(handlers,{libraryCreate8:()=>createLibrary8(),libraryPlanSave8:()=>jsonSave8(L8.plan,'WayriCAD_library_creation_review.json')});
// Also cover fast local state responses that arrived before this deferred script.
if(S.data?.project||S.view==='engineering')render();
