'use strict';
/* Explicit read-only purchasing view. Native BOM authority and properties stay untouched. */
titles.vendors=['Vendor split & upload','Route once. Review quantities. Export a clean file for each distributor.'];
const VS={config:null,report:null,project:'',variant:'',revision:-1,busy:false,tab:'',page:0,selected:new Set(),draft:false,loadedRevision:-1,previewConfig:'',allowPartial:false};
const vendorDefault=()=>({schema:'wayricad-vendor-config-1',vendor_field:'',mpn_field:'',manufacturer_field:'',sku_field:'',customer_field:'',moq_field:'',multiple_field:'',boards:null,attrition_percent:null,quantity_basis:'order',formats:['csv','xlsx'],profiles:{},assignments:{}});
function vendorContext(){
 const project=S.data?.project?.path||'';
 if(VS.project!==project){VS.project=project;VS.config={...vendorDefault(),...(S.data?.vendor_export_settings||{})};VS.report=null;VS.draft=false;VS.selected.clear();VS.loadedRevision=S.data.revision;VS.allowPartial=false;}
 if(VS.variant!==S.variant){VS.variant=S.variant;VS.report=null;VS.selected.clear();VS.page=0;VS.allowPartial=false;}
 if(!VS.draft&&!VS.busy&&VS.loadedRevision!==S.data.revision){VS.config={...vendorDefault(),...(S.data?.vendor_export_settings||{})};VS.loadedRevision=S.data.revision;}
}
function vendorStale(){return !VS.report||VS.revision!==S.data.revision||JSON.stringify(VS.config)!==VS.previewConfig;}
const vsButton=(action,text,extra='')=>`<button type="button" class="small" data-act="${action}" ${extra}>${esc(text)}</button>`;
function vendorField(label,key,c){const names=[...new Set(S.data.field_inventory.fields.map(f=>f.name))];return `<label>${esc(label)}<input data-vs-map="${key}" list="vendorFields" value="${esc(c[key])}" placeholder="Auto: inspect conflicts" aria-label="${esc(label)}"></label>`;}
function renderVendors(){
 vendorContext();const c=VS.config,r=VS.report,stale=r&&vendorStale(),sum=r?.summary;
 const fields=['vendor_field','mpn_field','manufacturer_field','sku_field','customer_field','moq_field','multiple_field'];
 const labels=['Vendor / Supplier field','Manufacturer part-number field','Manufacturer field','Generic supplier SKU field','Customer / Internal part number','MOQ field','Order-multiple field'];
 let content=`<section class="panel"><div class="panel-body"><div class="notice"><b>Separate purchasing export.</b> Your KiCad BOM format, field-name templates and component values remain unchanged. All quantities are component pieces. No supplier upload or purchase occurs here.</div><div class="vendor-config-grid">${fields.map((k,i)=>vendorField(labels[i],k,c)).join('')}<label>Board quantity<input type="number" min="1" max="1000000" data-vs-map="boards" value="${c.boards??''}" placeholder="Project: ${S.data.settings.boards}" aria-label="Vendor board quantity"></label><label>Attrition %<input type="number" min="0" max="100" step="any" data-vs-map="attrition_percent" value="${c.attrition_percent??''}" placeholder="Project: ${S.data.settings.attrition}" aria-label="Vendor attrition percentage"></label><label>Upload quantity basis<select data-vs-map="quantity_basis" aria-label="Upload quantity basis">${[['order','Order: build + attrition + MOQ / multiples'],['required','Required: build + attrition'],['installed','Installed: build only']].map(([v,l])=>`<option value="${v}" ${c.quantity_basis===v?'selected':''}>${l}</option>`).join('')}</select></label></div><datalist id="vendorFields">${S.data.field_inventory.fields.map(f=>`<option value="${esc(f.name)}">`).join('')}</datalist><div class="toolbar"><span>Include in ZIP:</span>${['csv','xlsx','tsv'].map(f=>`<label class="check-label"><input type="checkbox" data-vs-format="${f}" ${c.formats.includes(f)?'checked':''}>${f.toUpperCase()}</label>`).join('')}<span class="grow"></span>${vsButton('vendorProfiles','Vendor profiles & column mapping…')}${vsButton('vendorImportConfig','Import settings…')}${vsButton('vendorShareConfig','Share settings')}</div><div class="toolbar">${vsButton('vendorPreview',VS.busy?'Working…':'Preview vendor split',VS.busy?'disabled':'')}${vsButton('vendorSaveConfig','Save mappings to workspace')}${vsButton('vendorResetAssignments','Clear this variant’s routing overrides…')}<span class="fine">${VS.draft?'Mapping draft not saved.':'Saved mapping / project defaults.'}</span></div></div></section>`;
 if(!r)return content+`<section class="panel empty"><h2>Prepare distributor files without rebuilding your BOM</h2><p>Choose the column containing DigiKey, Mouser or another supplier. Leave other mappings blank for conflict-checked discovery. DNP/DNI and BOM-excluded items never create purchasing demand.</p><p>Preview lists routed, unassigned and excluded parts. Assign unresolved rows here without changing native fields, then export.</p></section>`;
 content+=`<div class="spacer"></div>${stale?'<div class="notice warning" role="status">Preview is stale after configuration or workspace changes. Preview again before exporting.</div>':''}<div class="metrics">${[['Routed components',sum.routed_components],['Unassigned / blocked',sum.unassigned_components+sum.blocked_components],['Excluded DNP / BOM',sum.excluded_components],['Requested pieces',sum.upload_pieces]].map(([l,v])=>`<article class="metric"><div class="metric-label">${l}</div><div class="metric-value">${v}</div></article>`).join('')}</div>`;
 const blocked=r.blocking_checks.length>0;
 if(blocked)content+=`<div class="notice error"><b>BOM checks block uploads.</b> Partial routing cannot bypass uncertain rule areas, variable conflicts or other source errors. ${vsButton('vendorChecks','Inspect checks')}${r.blocking_checks.slice(0,5).map(x=>`<p>${esc(x.reference)}: ${esc(x.message)}</p>`).join('')}</div>`;
 content+=`<section class="panel"><div class="toolbar"><b>${esc(r.status)} · ${sum.upload_lines} upload lines · ${sum.vendors} vendors</b><span class="grow"></span>${vsButton('vendorDownloadReport','Full routing audit (JSON)')}${vsButton('vendorExportAll',sum.eligible_components?'Export vendor ZIP':'Export audit ZIP (no demand)',stale||blocked||(!sum.vendors&&sum.eligible_components)?'disabled':'')}</div><div class="panel-body"><p class="fine"><b>Reconciled:</b> ${sum.routed_installed_pieces} routed + ${sum.unresolved_installed_pieces} unresolved = ${sum.installed_pieces} installed pieces. MOQ/attrition overage is separate.</p><label class="check-label"><input id="vendorPartial" type="checkbox" ${VS.allowPartial?'checked':''}>Allow an explicitly PARTIAL package with unresolved parts listed separately.</label><p class="notice warning">On the supplier website set assembly multiplier to <b>1</b> and extra attrition to <b>0</b>. CSV/XLSX/TSV are alternative encodings of the same order demand—upload only one format per vendor/chunk.</p></div><div class="toolbar vendor-tabs">${r.vendors.map(v=>vsButton('vendorTab',`${v.name} (${v.line_count})`,`data-vendor="${esc(v.id)}" aria-pressed="${VS.tab===v.id}"`)).join('')}${vsButton('vendorTab',`Unassigned (${r.unassigned.length})`,'data-vendor="unassigned"')}${vsButton('vendorTab',`All eligible (${r.components.length})`,'data-vendor="all"')}${vsButton('vendorTab',`Excluded (${r.excluded.length})`,'data-vendor="excluded"')}</div><div id="vendorTableArea">${vendorTable(r,stale||blocked)}</div></section>`;
 return content;
}
function vendorTable(r,disabled){
 if(!VS.tab)VS.tab=r.unassigned.length?'unassigned':r.vendors[0]?.id||'all';
 const v=r.vendors.find(v=>v.id===VS.tab);
 if(v){const lines=v.lines.slice(VS.page*100,(VS.page+1)*100);return `<div class="panel-body"><div class="toolbar"><h2>${esc(v.name)}</h2>${vsButton('vendorSite','Open supplier site',`data-url="${esc(v.profile.url)}" ${!v.profile.url?'disabled':''}`)}<span class="grow"></span>${['csv','xlsx','tsv'].map(f=>vsButton('vendorExportOne',f.toUpperCase(),`data-format="${f}" data-vendor="${esc(v.id)}" ${disabled?'disabled':''}`)).join('')}</div><p class="fine">${esc(v.profile.mapping)} ${v.file_parts>1?`Export ZIP: ${v.file_parts} file chunks required.`:''}</p><p class="fine">Upload headers: ${v.profile.headers.map(esc).join(' · ')}</p></div><div class="table-wrap"><table class="data-table"><thead><tr><th>References</th><th>Exact MPN</th><th>Vendor SKU</th><th>Installed</th><th>Required</th><th>Order</th><th>Upload</th></tr></thead><tbody>${lines.map(l=>`<tr><td>${esc(l.references)}</td><td>${esc(l.mpn)}</td><td>${esc(l.sku||'MPN lookup')}</td><td>${l.installed_qty}</td><td>${l.required_qty}</td><td>${l.order_qty}</td><td><b>${l.upload_qty}</b></td></tr>`).join('')}</tbody></table></div>${vendorPager(v.lines.length)}`;}
 if(VS.tab==='excluded')return `<div class="table-wrap"><table class="data-table"><thead><tr><th>Reference</th><th>Not purchased because</th></tr></thead><tbody>${r.excluded.slice(VS.page*100,(VS.page+1)*100).map(x=>`<tr><td>${esc(x.reference)}</td><td>${esc(x.reason)}</td></tr>`).join('')}</tbody></table></div>${vendorPager(r.excluded.length)}`;
 const rows=VS.tab==='unassigned'?r.unassigned:r.components,visible=rows.slice(VS.page*100,(VS.page+1)*100);
 return `<div class="toolbar"><b>${VS.selected.size} routing targets (not BOM edit selection)</b>${vsButton('vendorSelectResults','Select all rows in this tab')}${vsButton('vendorClearSelection','Clear')}${vsButton('vendorAssign','Assign vendor…',!VS.selected.size?'disabled':'')}</div><div class="table-wrap"><table class="data-table" id="vendorRoutingTable"><thead><tr><th>Route</th><th>Reference</th><th>Vendor</th><th>MPN</th><th>SKU</th><th>Status / reason</th></tr></thead><tbody>${visible.map(x=>`<tr><td><input type="checkbox" data-vs-select="${esc(x.id)}" ${VS.selected.has(x.id)?'checked':''} aria-label="Route ${esc(x.reference)}"></td><td>${esc(x.reference)}</td><td>${esc(x.vendor||'Unassigned')}</td><td>${esc(x.mpn)}</td><td>${esc(x.sku)}</td><td><span class="pill ${x.status==='ready'?'fit':'warning'}" title="${esc(x.reasons.join('; '))}">${esc(x.status)}</span> ${esc(x.reasons.join('; '))}</td></tr>`).join('')}</tbody></table></div>${vendorPager(rows.length)}`;
}
function vendorPager(n){return `<div class="table-footer"><span>${n} rows · page ${VS.page+1} of ${Math.max(1,Math.ceil(n/100))}</span><div>${vsButton('vendorPrev','Previous',VS.page===0?'disabled':'')}${vsButton('vendorNext','Next',(VS.page+1)*100>=n?'disabled':'')}</div></div>`;}
async function vendorPreview(){if(VS.busy)return;VS.busy=true;render();try{const r=await api('vendors/preview',{variant:S.variant,config:VS.config});VS.report=r;VS.config=r.config;VS.revision=S.data.revision;VS.previewConfig=JSON.stringify(r.config);VS.page=0;VS.tab=r.unassigned.length?'unassigned':r.vendors[0]?.id||'all';VS.selected.clear();}finally{VS.busy=false;render();}}
async function vendorDownload(format,vendor){
 if(vendorStale())throw Error('Preview again before export.');
 const allow=VS.allowPartial;
 if(VS.report.unassigned.length&&!allow)throw Error('Resolve unassigned/blocked rows or acknowledge a PARTIAL export.');
 await download('vendors/export',{config:VS.report.config,variant:S.variant,format,vendor,allow_partial:allow,fingerprint:VS.report.fingerprint});
}
Object.assign(handlers,{
 vendorPreview,
 vendorExportAll:()=>vendorDownload('zip'),vendorExportOne:b=>vendorDownload(b.dataset.format,b.dataset.vendor),
 vendorDownloadReport:()=>jsonSave8(VS.report,'Vendor_routing_report.json'),
 vendorSaveConfig:async()=>{const c=await api('vendors/settings',{config:VS.config});VS.config=c;VS.draft=false;await refresh();toast('Mappings staged. Save workspace to persist; native fields unchanged.');},
 vendorShareConfig:()=>jsonSave8({...VS.config,assignments:{}},'Vendor_mapping_profile.json'),
 vendorImportConfig:()=>showDialog('Import vendor mapping profile',`<p>Paste shared configuration JSON. Imported settings do not alter KiCad fields. Cross-project routing overrides are not imported.</p><textarea name="config" rows="14" required aria-label="Vendor profile JSON"></textarea>${formActions('Load mappings')}`,async f=>{const c=JSON.parse(f.get('config'));c.assignments={};await api('vendors/preview',{variant:S.variant,config:c});VS.config=c;VS.draft=true;VS.report=null;render();}),
 vendorProfiles:()=>showDialog('Vendor profiles & upload columns',`<p>Profiles map vendor aliases, vendor-specific SKU fields, output headings/keys and maximum lines per file. DigiKey and Mouser defaults remain unless overridden. Other vendors use an explicitly labelled generic mapping.</p><p class="fine">Use keys sku, mpn, manufacturer, upload_qty, customer_reference, references. Never map a pack/reel quantity as component pieces.</p><textarea name="profiles" rows="14" aria-label="Custom vendor profiles">${esc(JSON.stringify(VS.config.profiles,null,2))}</textarea>${formActions('Use profiles')}`,async f=>{const c={...VS.config,profiles:JSON.parse(f.get('profiles'))};await api('vendors/preview',{variant:S.variant,config:c});VS.config=c;VS.draft=true;render();}),
 vendorResetAssignments:()=>showDialog('Clear routing overrides for this variant',`<p>Revert to the component vendor/SKU fields for ${esc(S.variant)}. Does not edit any component property.</p>${formActions('Clear routing overrides')}`,async()=>{delete VS.config.assignments[S.variant];VS.draft=true;VS.report=null;render();}),
 vendorTab:b=>{VS.tab=b.dataset.vendor;VS.page=0;VS.selected.clear();render();},vendorPrev:()=>{VS.page=Math.max(0,VS.page-1);render();},vendorNext:()=>{VS.page++;render();},
 vendorClearSelection:()=>{VS.selected.clear();render();},vendorSelectResults:()=>{const rows=VS.tab==='unassigned'?VS.report.unassigned:VS.report.components;VS.selected=new Set(rows.map(x=>x.id));render();},
 vendorAssign:()=>{
 const rows=VS.report.components.filter(r=>VS.selected.has(r.id));
 if(!rows.length)throw Error('Select routing targets first.');
 showDialog('Assign vendor for purchasing export',`<p>${rows.length} physical component(s): ${esc(rows.map(r=>r.reference).slice(0,30).join(', '))}. Full quantity goes to exactly one vendor; this is not split-quantity allocation.</p><label>Vendor<input name="vendor" list="vendorNames" required aria-label="Assigned vendor"></label><datalist id="vendorNames"><option>DigiKey</option><option>Mouser</option></datalist>${rows.length===1?'<label>Vendor SKU override (optional)<input name="sku" aria-label="Assigned vendor SKU"></label>':''}<p class="fine">Overrides are scoped to this variant and bind to the current part properties. Generic old-vendor SKUs are not reused after a vendor change. Native component fields stay unchanged.</p>${formActions('Apply routing only')}`,async f=>{const config=structuredClone(VS.config);config.assignments[S.variant]??={};for(const r of rows){const entry={vendor:f.get('vendor'),signature:r.signature};if(rows.length===1&&f.get('sku'))entry.sku=f.get('sku');config.assignments[S.variant][r.id]=entry;}const report=await api('vendors/preview',{variant:S.variant,config});VS.config=config;VS.report=report;VS.revision=S.data.revision;VS.draft=true;VS.previewConfig=JSON.stringify(config);VS.selected.clear();VS.busy=true;render();VS.busy=false;toast('Routing prepared; save mappings to retain it.');});
 },
 vendorSite:async b=>{const url=b.dataset.url;if(!url)return;if(S.data.ui_mode==='desktop'){const r=await window.pywebview.api.open_external(url,token);if(!r.ok)throw Error(r.error);}else window.open(url,'_blank','noopener,noreferrer');},
 vendorChecks:()=>{S.view='checks';render();}
});
document.addEventListener('input',e=>{const key=e.target.dataset.vsMap;if(!key)return;let v=e.target.value;if(key==='boards')v=v===''?null:Number(v);if(key==='attrition_percent'&&v==='')v=null;VS.config[key]=v;VS.draft=true;VS.report=null;});
document.addEventListener('change',e=>{if(e.target.id==='vendorPartial')VS.allowPartial=e.target.checked;if(e.target.dataset.vsFormat){const f=e.target.dataset.vsFormat;VS.config.formats=e.target.checked?[...new Set([...VS.config.formats,f])]:VS.config.formats.filter(x=>x!==f);VS.draft=true;VS.report=null;}if(e.target.dataset.vsSelect){const id=e.target.dataset.vsSelect;e.target.checked?VS.selected.add(id):VS.selected.delete(id);render();}});
// Pending mapping drafts survive navigation. Top-level Save commits them before
// saving the sidecar; leaving the app or opening another project warns first.
const saveBeforeVendor=save;
save=async function(){if(VS.draft&&VS.project===S.data?.project?.path){await api('vendors/settings',{config:VS.config});VS.draft=false;}return saveBeforeVendor();};
handlers.save=save;
window.addEventListener('beforeunload',e=>{if(VS.draft){e.preventDefault();e.returnValue='';}});
document.addEventListener('click',e=>{if(!VS.draft)return;const b=e.target.closest('button');if(!b)return;if(b.id==='quitButton'||b.id==='openButton'||['demo','reload'].includes(b.dataset.act)){if(!confirm('Unsaved vendor mapping/routing changes. Discard them? Use Save workspace to retain them.')){e.preventDefault();e.stopImmediatePropagation();}else{VS.draft=false;VS.loadedRevision=-1;}}},true);
if(S.data?.project&&S.view==='vendors')render();
