/* WayriCAD BOM Studio v0.2 — columns, templates, text exports, reviewed schemas. */
'use strict';
titles.fieldtemplates=['Field name templates','A shared field standard, with explicit control over what changes.'];
S.fieldProfile='Engineering standard';
const FORMAT_CHOICES=[['xlsx','Excel workbook (.xlsx)'],['csv','CSV (.csv)'],['tsv','Tab-separated (.tsv)'],['ods','OpenDocument spreadsheet (.ods)'],['txt','Unicode text report (.txt)'],['ascii','7-bit ASCII report (.asc)'],['xml','Generic BOM XML (.xml)'],['json','JSON + metadata (.json)'],['jsonl','JSON Lines (.jsonl)'],['html','Printable HTML (.html)'],['md','Markdown table (.md)']];
const optionList=(items,current)=>items.map(([v,t])=>`<option value="${esc(v)}" ${v===current?'selected':''}>${esc(t)}</option>`).join('');
const checked=v=>v?'checked':'';
function catalogToolbar(section){return `<div class="template-tools" data-catalog-section="${section}"><button class="small" data-act="newDefinition" data-section="${section}">+ New</button><button class="small" data-act="manageDefinition" data-op="duplicate" data-section="${section}">Duplicate</button><button class="small" data-act="manageDefinition" data-op="rename" data-section="${section}">Rename</button><button class="small quiet" data-act="manageDefinition" data-op="delete" data-section="${section}">Delete</button><button class="small" data-act="shareDefinition" data-section="${section}">Share JSON ↗</button><button class="small" data-act="importDefinitions">Import…</button></div>`;}
function activeDefinition(section){return section==='templates'?S.template:section==='field_profiles'?S.fieldProfile:$('#viewPreset')?.value;}
async function ensureTemplateSaved(){
  if(S.view!=='exports'||!$('#templateName'))return;
  const t=collectTemplateV2();await api('template',{template:t});S.template=t.name;S.data.templates[t.name]=t;S.data.dirty=true;S.formDirty=false;header();
}
function templateColumnV2(c={field:'',label:''}){
  return `<div class="column-row export-column" draggable="true" data-drag-row="export"><span class="drag-handle" title="Drag to reorder">⠿</span><label class="tiny-check" title="Include this column in exports"><input type="checkbox" data-column-export ${checked(c.export!==false)} aria-label="Export column"></label><input data-column-field aria-label="Column field" placeholder="MPN or \${QUANTITY}" value="${esc(c.field)}" list="exportFieldNames"><input data-column-label aria-label="Column label" placeholder="Header" value="${esc(c.label)}"><button type="button" data-act="columnUp" aria-label="Move column up">↑</button><button type="button" data-act="columnDown" aria-label="Move column down">↓</button><button type="button" data-act="columnRemove" aria-label="Remove column">×</button></div>`;
}
function renderExportsV2(){
  if(!S.data.templates[S.template])S.template=Object.keys(S.data.templates)[0];
  const t=S.data.templates[S.template],o=t.options||{};
  return `<div class="exports-layout"><section class="panel"><div class="panel-title"><h2>BOM template</h2><span class="chip">Reusable · shareable</span></div><div class="template-form">
    <div class="field"><label for="templateSelect">Saved template</label><select id="templateSelect">${Object.keys(S.data.templates).map(k=>`<option ${k===S.template?'selected':''}>${esc(k)}</option>`).join('')}</select></div>${catalogToolbar('templates')}
    <div class="field-row"><div class="field"><label for="templateName">Template name</label><input id="templateName" value="${esc(t.name)}"></div><div class="field"><label for="templateRevision">Revision</label><input id="templateRevision" value="${esc(t.revision||'1')}"></div></div>
    <details><summary>Description & author</summary><div class="field"><label>Description</label><textarea id="templateDescription">${esc(t.description||'')}</textarea></div><div class="field"><label>Author</label><input id="templateAuthor" value="${esc(t.author||'')}"></div></details>
    <div class="section-label">COLUMNS — DRAG OR USE ARROWS TO REORDER</div><p class="fine">The checkbox controls export inclusion. An unchecked column stays in the template; no component data is deleted.</p>
    <div class="column-legend"><span>Export</span><span>Source field / virtual expression</span><span>Export header</span></div><div id="templateColumns">${t.columns.map(templateColumnV2).join('')}</div>
    <datalist id="exportFieldNames">${[...new Set([...allFields(),'Reference','Qty','Required','OrderQty','LineCost','OrderCost','Item','${QUANTITY}','${ITEM_NUMBER}','${SYMBOL_LIBRARY}:${SYMBOL_NAME}'])].map(k=>`<option value="${esc(k)}">`).join('')}</datalist>
    <div class="row spread"><button class="small" data-act="addColumn">+ Column</button><button class="small" data-act="useExportColumns">Use these columns in workspace</button></div>
    <details class="spaced-details"><summary>Population & grouping</summary><div class="field"><label>Population</label><select id="templatePopulation">${optionList([['all','All population states'],['fitted','Fitted only'],['not_fitted','DNP / DNI only']],t.population||'all')}</select></div><label class="check-label"><input type="checkbox" id="templateExcluded" ${checked(t.include_excluded)}>Include parts excluded from BOM</label><div class="field"><label>Group by fields</label><input id="templateGroups" value="${esc((t.group_by||[]).join(', '))}"><small>Empty = one line per reference. Incompatible packages, MPNs, prices and exported values are kept separate.</small></div><div class="field"><label>Sort field</label><input id="templateSort" value="${esc(t.sort_field||'Reference')}"></div></details>
    <details class="spaced-details"><summary>Text, variables & export options</summary><div class="notice">Stored expressions are preserved in the project. Choose resolved text for purchasing; raw expressions for an engineering audit. Virtual columns still evaluate their expressions.</div>
    <div class="field-row"><div class="field"><label>Field values</label><select id="templateTextMode">${optionList([['resolved','Resolve variables'],['raw','Keep raw expressions']],o.text_mode||'resolved')}</select></div><div class="field"><label>CSV delimiter</label><select id="templateDelimiter">${optionList([[',','Comma'],[';','Semicolon'],['tab','Tab'],['|','Pipe']],t.delimiter==='\t'?'tab':t.delimiter||',')}</select></div></div>
    <div class="field-row"><div class="field"><label>CSV / TSV encoding</label><select id="templateEncoding">${optionList([['utf-8-sig','UTF-8 with BOM (Excel-friendly)'],['utf-8','UTF-8'],['ascii','7-bit ASCII'],['cp1252','Windows-1252']],o.encoding||'utf-8-sig')}</select></div><div class="field"><label>Line endings</label><select id="templateLineEnd">${optionList([['crlf','Windows CRLF'],['lf','Unix LF']],o.line_ending||'crlf')}</select></div></div>
    <div class="field-row"><div class="field"><label>CSV quoting</label><select id="templateQuoting">${optionList([['minimal','Quote when needed'],['all','Quote every cell']],o.quoting||'minimal')}</select></div><div class="field"><label>Non-ASCII characters</label><select id="templateAsciiPolicy">${optionList([['escape','Preserve as character escapes'],['error','Stop export and report error']],o.ascii_policy||'escape')}</select></div></div>
    <div class="field-row"><div class="field"><label>Text report column width</label><input id="templateAsciiWidth" type="number" min="8" max="120" value="${o.ascii_width||36}"></div><div class="field"><label>Reference separator</label><input id="templateRefSeparator" value="${esc(o.reference_separator??', ')}"></div></div><div class="field-row"><label class="check-label"><input type="checkbox" id="templateRanges" ${checked(t.ref_ranges)}>Compact reference ranges</label><div class="field"><label>Range separator</label><input id="templateRangeSeparator" value="${esc(o.range_separator??'–')}"></div></div>
    <p class="fine">Header labels may use project or variant variables. Component-specific header expressions are blocked because a grouped BOM has one header row. Unicode is never silently replaced with question marks.</p></details>
    <div class="form-actions sticky-actions"><button data-act="shareAllDefinitions">Share all templates ↗</button><button class="primary" data-act="saveTemplate">Save template</button></div></div></section>
    <section class="stack export-output"><article class="panel"><div class="panel-title"><h2>Generate & inspect</h2><button class="small" data-act="buildSettings">Build settings</button></div><div class="panel-body"><p class="fine">${S.data.settings.boards} boards · ${S.data.settings.attrition}% allowance · ${esc(S.variant)}. Current form edits are saved to the workspace before preview/export.</p><div class="field"><label for="exportFormat">Export format</label><select id="exportFormat">${optionList(FORMAT_CHOICES,'xlsx')}</select></div><div class="row"><button data-act="previewExport">Preview</button><button class="primary" data-act="downloadExport">Export active variant ↗</button></div><label class="check-label spaced"><input id="draftExport" type="checkbox">Draft — allow failed checks; not for manufacturing</label><div class="notice">XML is a generic BOM interchange schema, not IPC-2581 or ODB++. ERP and assembler presets require your supplier’s field mapping and review.</div><div class="line"></div><h3>All-variant release</h3><p class="fine">CSV, Excel, HTML, JSON, text, XML, variant differences and checks. Includes a workspace snapshot with project data: review before sharing.</p><button class="secondary" data-act="downloadRelease">Download release ZIP ↗</button></div></article><article class="panel"><div class="panel-title"><h2>Export preview</h2></div><div class="panel-body" id="exportPreview"><p class="empty">Preview shows the selected column order and resolved values before you export.</p></div></article></section></div>`;
}
function collectTemplateV2(){
  return {name:$('#templateName').value.trim(),revision:$('#templateRevision').value,author:$('#templateAuthor').value,description:$('#templateDescription').value,
    columns:$$('#templateColumns .column-row').map(r=>({field:r.querySelector('[data-column-field]').value.trim(),label:r.querySelector('[data-column-label]').value.trim(),export:r.querySelector('[data-column-export]').checked})),
    group_by:$('#templateGroups').value.split(',').map(x=>x.trim()).filter(Boolean),population:$('#templatePopulation').value,include_excluded:$('#templateExcluded').checked,delimiter:$('#templateDelimiter').value==='tab'?'\t':$('#templateDelimiter').value,ref_ranges:$('#templateRanges').checked,sort_field:$('#templateSort').value.trim()||'Reference',
    options:{text_mode:$('#templateTextMode').value,encoding:$('#templateEncoding').value,line_ending:$('#templateLineEnd').value,quoting:$('#templateQuoting').value,ascii_policy:$('#templateAsciiPolicy').value,ascii_width:Number($('#templateAsciiWidth').value),reference_separator:$('#templateRefSeparator').value,range_separator:$('#templateRangeSeparator').value}};
}
// Preserve original helpers for the compact preview / download implementations.
const originalPreviewExport=previewExport,originalDownload=download;
async function previewExportV2(){await ensureTemplateSaved();await originalPreviewExport();toast('Preview uses the current template edits.');}
async function exportV2(releaseBundle=false){await ensureTemplateSaved();await originalDownload(releaseBundle?'release':'export',{format:$('#exportFormat').value,draft:$('#draftExport').checked});}
function viewRow(k,on){return `<div class="view-column" data-drag-row="view" draggable="true"><span class="drag-handle">⠿</span><label class="check-label"><input type="checkbox" name="column" value="${esc(k)}" ${checked(on)}><span>${esc(k)}</span></label><button type="button" data-act="viewUp" aria-label="Move ${esc(k)} up">↑</button><button type="button" data-act="viewDown" aria-label="Move ${esc(k)} down">↓</button></div>`;}
function populateViewColumns(columns){const fields=[...new Set([...columns,...S.data.rows.flatMap(r=>Object.keys(r.fields))])];$('#viewColumns').innerHTML=fields.map(k=>viewRow(k,columns.includes(k))).join('');}
function columnsDialogV2(){
  showDialog('Visible BOM columns',`<div class="notice">Arrange the on-screen workspace independently of export templates. Hidden fields remain in every component.</div><div class="field-row"><div class="field"><label>Saved layout</label><select id="viewPreset"><option value="">Current workspace</option>${Object.keys(S.data.view_presets||{}).map(n=>`<option>${esc(n)}</option>`).join('')}</select></div><div class="field"><label>Save layout as (optional)</label><input name="preset" id="viewPresetName" placeholder="Engineering review / purchasing"></div></div><div class="row"><button type="button" data-act="viewAll">Show all</button><button type="button" data-act="viewNone">Hide all</button><button type="button" data-act="shareDefinition" data-section="view_presets">Share saved layout ↗</button><button type="button" data-act="manageDefinition" data-section="view_presets" data-op="delete">Delete saved layout</button></div><div class="field spaced"><label>Find a field</label><input id="viewColumnSearch" type="search" placeholder="Filter field names"></div><div id="viewColumns" class="ordered-list"></div>${formActions('Apply columns')}`,async f=>{
    const columns=$$('#viewColumns input[name=column]:checked').map(e=>e.value);if(!columns.length)throw Error('Keep at least one visible column.');
    const preset=String(f.get('preset')||'').trim()||null;await api('view',{view:{columns},preset});await refresh();toast('Column order and visibility saved to the workspace.');
  });populateViewColumns(S.columns);
}
function fieldSchemaRow(f={name:'',aliases:[],default:'',required:false,visible:false,url:false}){
  return `<div class="field-schema-row" data-drag-row="schema" draggable="true"><div class="schema-top"><span class="drag-handle">⠿</span><input data-schema-name aria-label="Field name" placeholder="Field name or variable-bearing name" value="${esc(f.name)}"><button type="button" data-act="schemaUp" aria-label="Move field up">↑</button><button type="button" data-act="schemaDown" aria-label="Move field down">↓</button><button type="button" data-act="schemaRemove" aria-label="Remove field from template">×</button></div><div class="schema-values"><label>Aliases to normalize<input data-schema-aliases aria-label="Field aliases" placeholder="Mfr PN; Manufacturer Part Number" value="${esc((f.aliases||[]).join('; '))}"></label><label>Default value / expression<input data-schema-default aria-label="Field default value" placeholder="Empty, literal text or \${VARIABLE}" value="${esc(f.default||'')}"></label></div><div class="row schema-flags"><label class="check-label"><input data-schema-required type="checkbox" ${checked(f.required)}>Required in fitted BOM</label><label class="check-label"><input data-schema-visible type="checkbox" ${checked(f.visible)}>Visible on schematic</label><label class="check-label"><input data-schema-url type="checkbox" ${checked(f.url)}>URL field</label></div></div>`;
}
function renderFieldTemplates(){
  if(!S.data.field_profiles[S.fieldProfile])S.fieldProfile=Object.keys(S.data.field_profiles)[0]||'';
  const p=S.data.field_profiles[S.fieldProfile]||{name:'New field template',fields:[]};
  return `<div class="schema-layout"><section class="panel field-profile-form"><div class="panel-title"><h2>Field name standard</h2><span class="chip">Default + all variants</span></div><div class="panel-body"><div class="field"><label>Saved field template</label><select id="fieldProfileSelect">${Object.keys(S.data.field_profiles).map(n=>`<option ${n===S.fieldProfile?'selected':''}>${esc(n)}</option>`).join('')}</select></div>${catalogToolbar('field_profiles')}<div class="field-row"><div class="field"><label>Template name</label><input id="fieldProfileName" value="${esc(p.name)}"></div><div class="field"><label>Revision</label><input id="fieldProfileRevision" value="${esc(p.revision||'1')}"></div></div><div class="field"><label>Description</label><textarea id="fieldProfileDescription">${esc(p.description||'')}</textarea></div><div class="field"><label>Author</label><input id="fieldProfileAuthor" value="${esc(p.author||'')}"></div><div class="section-label">CUSTOM FIELDS — IN TEMPLATE ORDER</div><div id="fieldSchemaRows">${p.fields.map(fieldSchemaRow).join('')}</div><div class="row spread"><button data-act="addSchemaField">+ Field</button><button class="primary" data-act="saveFieldProfile">Save field template</button></div></div></section>
    <section class="stack"><article class="panel"><div class="panel-title"><h2>Enforce across this project</h2></div><div class="panel-body"><p>Normalize existing symbol fields on every supported sheet and assembly variant. Optionally register the same names in KiCad’s project field-name defaults.</p><div class="notice warning"><b>Enforcement can remove custom fields and lose variable expressions.</b> Exact mode, resetting defaults, or baking variables can overwrite design information. Review every proposed change and keep a backup.</div><button class="primary wide" data-act="enforceOptions">Enforce…</button><p class="fine">First preview, then type ENFORCE to stage. Native files are changed only through the separate Review & native sync workflow, with a backup and APPLY confirmation.</p>${S.data.field_schema_pending?`<div class="notice">${S.data.field_schema_pending} field-schema records are staged. <button class="linkbutton" data-view="review">Review native changes →</button></div>`:''}</div></article>
    <article class="panel"><div class="panel-title"><h2>Three independent controls</h2></div><div class="panel-body"><h3>Workspace visibility</h3><p class="fine">Choose columns in BOM workspace → Columns. No field values are removed.</p><h3>Export inclusion</h3><p class="fine">Select export checkboxes and headers in Exports & templates. The BOM schema stays unchanged.</p><h3>Native field schema</h3><p class="fine">Enforce adds, renames and optionally removes actual symbol properties. Schematic visibility applies only when explicitly selected.</p><div class="line"></div><h3>KiCad variables</h3><p class="fine">Raw \${NAME} expressions in field names and values are preserved by default, with resolved inspection and export. Unknown names, cycles, alias conflicts and ambiguous resolved names block enforcement.</p><p class="fine">An export column named \${SYMBOL_LIBRARY}:\${SYMBOL_NAME} is a virtual calculation, not a physical field to add to symbols. An exact name like \${MY_VAR} is a KiCad generated field: its value is linked to that same expression, and its displayed name is MY_VAR. Leave its template default blank or identical to the name expression. Compound names such as Code_\${TYPE} can have independent values. Resolved compound-name aliases are a WayriCAD display/export feature; raw native property keys are preserved.</p><p class="fine">Scope: this open project, not every project, installed symbol library, PCB or global Preferences file. Reopen KiCad and update the PCB from the schematic after native sync.</p></div></article></section></div>`;
}
function collectFieldProfile(){return {name:$('#fieldProfileName').value.trim(),revision:$('#fieldProfileRevision').value,description:$('#fieldProfileDescription').value,author:$('#fieldProfileAuthor').value,
  fields:$$('#fieldSchemaRows .field-schema-row').map(r=>({name:r.querySelector('[data-schema-name]').value.trim(),aliases:r.querySelector('[data-schema-aliases]').value.split(';').map(x=>x.trim()).filter(Boolean),default:r.querySelector('[data-schema-default]').value,required:r.querySelector('[data-schema-required]').checked,visible:r.querySelector('[data-schema-visible]').checked,url:r.querySelector('[data-schema-url]').checked}))};}
async function saveFieldProfile(refreshView=true){const p=collectFieldProfile();await api('field/profile',{profile:p});S.fieldProfile=p.name;S.data.field_profiles[p.name]=p;S.data.dirty=true;S.formDirty=false;header();if(refreshView){await refresh();toast('Field template saved. It has not been enforced.');}return p;}
function moveRow(el,selector,direction){const r=el.closest(selector),other=direction<0?r.previousElementSibling:r.nextElementSibling;if(other)direction<0?r.parentNode.insertBefore(r,other):r.parentNode.insertBefore(other,r);if(selector!=='.view-column')S.formDirty=true;}
async function prepareDefinition(section){if(section==='templates'&&S.view==='exports')await ensureTemplateSaved();if(section==='field_profiles'&&S.view==='fieldtemplates')await saveFieldProfile(false);}
async function newDefinition(el){
  const section=el.dataset.section;await prepareDefinition(section);
  showDialog('New '+(section==='templates'?'BOM template':'field name template'),`<div class="field"><label>Name</label><input name="name" required maxlength="128"></div>${formActions('Create template')}`,async f=>{
    const name=String(f.get('name')).trim();if(Object.keys(S.data[section]).some(k=>k.toLowerCase()===name.toLowerCase()))throw Error('Name already exists. Use Duplicate to copy a template.');
    if(section==='templates'){await api('template',{template:{name,columns:[{field:'Reference',label:'Reference'},{field:'MPN',label:'MPN'},{field:'Qty',label:'Quantity'}],group_by:[],population:'all',include_excluded:false,ref_ranges:false,delimiter:','}});S.template=name;}
    else{await api('field/profile',{profile:{name,fields:[{name:'MPN',aliases:[],default:'',visible:false,url:false,required:true}]}});S.fieldProfile=name;}
    await refresh();toast('New reusable template created.');
  });
}
async function manageDefinition(el){
  const section=el.dataset.section,operation=el.dataset.op;await prepareDefinition(section);const old=activeDefinition(section);if(!old)throw Error('Choose a saved template first.');
  if(operation==='delete'){if(!confirm('Delete template “'+old+'”? Component fields and native files are not deleted.'))return;await api('catalog/manage',{section,operation,old});if($('#dialog').open)$('#dialog').close();await refresh();return;}
  showDialog(operation==='rename'?'Rename template':'Duplicate template',`<p class="fine">Source: ${esc(old)}</p><div class="field"><label>New name</label><input name="name" value="${esc(old+(operation==='duplicate'?' copy':''))}" required maxlength="128"></div>${formActions(operation==='rename'?'Rename':'Duplicate')}`,async f=>{
    const name=String(f.get('name')).trim();await api('catalog/manage',{section,operation,old,new:name});if(section==='templates')S.template=name;else if(section==='field_profiles')S.fieldProfile=name;await refresh();toast('Template '+operation+' completed.');
  });
}
async function shareDefinition(el){const section=el.dataset.section;await prepareDefinition(section);const name=activeDefinition(section);if(!name)throw Error('Choose a saved layout/template first.');await originalDownload('catalog/export',{section,name});toast('Template JSON includes definitions and literal defaults only. Review defaults before sharing.');}
function importDefinitions(){
  S.templateImportText='';S.templateImportPreview=null;
  showDialog('Import shared templates',`<div class="notice">Imports BOM templates, field-name standards and column layouts. Definitions only: this never enforces fields or imports someone else’s project variables.</div><div class="field"><label>Template JSON file</label><input id="templateImportFile" type="file" accept=".json,application/json"></div><div class="field"><label>Or paste template JSON</label><textarea id="templateImportText" rows="5" placeholder="WayriCAD template bundle JSON"></textarea></div><div class="field"><label>When a name already exists</label><select id="templateImportPolicy">${optionList([['keep_both','Keep both (rename imported copy)'],['replace','Replace existing definition'],['skip','Skip existing definition']],'keep_both')}</select></div><button data-act="previewTemplateImport">Preview import</button><div id="templateImportPreview" class="spaced"></div><div class="dialog-error" id="templateImportError" role="alert"></div>`);
}
async function previewTemplateImport(){
  const file=$('#templateImportFile').files[0];if(file&&file.size>2097152)throw Error('Template files must be smaller than 2 MiB.');
  const raw=file?await file.text():$('#templateImportText').value,policy=$('#templateImportPolicy').value;
  const p=await api('catalog/import/preview',{text:raw,policy});S.templateImportText=raw;S.templateImportPolicy=policy;
  $('#templateImportPreview').innerHTML=`<div class="table-wrap"><table class="data-table"><thead><tr><th>Kind</th><th>Source</th><th>Result</th><th>Action</th></tr></thead><tbody>${p.items.map(i=>`<tr><td>${esc(i.section)}</td><td>${esc(i.source)}</td><td>${esc(i.target)}</td><td>${esc(i.action)}</td></tr>`).join('')}</tbody></table></div><p class="fine">${esc(p.warning)}</p><button class="primary" data-act="applyTemplateImport">Apply reviewed import</button>`;
}
async function applyTemplateImport(){
  if($('#templateImportPolicy').value!==S.templateImportPolicy)throw Error('Import policy changed. Preview again.');
  const file=$('#templateImportFile').files[0],current=file?await file.text():$('#templateImportText').value;if(current!==S.templateImportText)throw Error('Import contents changed. Preview again.');
  await api('catalog/import/apply',{text:S.templateImportText,policy:S.templateImportPolicy});$('#dialog').close();await refresh();toast('Definitions imported. No component fields were enforced.');
}
async function enforceOptions(){
  const p=await saveFieldProfile(false);S.enforceProfile=p;
  showDialog('Enforce “'+p.name+'”',`<div class="notice warning"><b>Potential loss of fields, values and variable expressions.</b> Exact mode removes extra custom fields across the default and all variants. Resetting or baking replaces raw expressions. Project variable definitions themselves are not deleted. Keep a backup.</div><div class="field"><label>Schema policy</label><select id="enforceMode">${optionList([['merge','Merge — keep extra fields (safer)'],['exact','Exact — remove non-template custom fields']],'merge')}</select></div><div class="field"><label>Existing values</label><select id="enforceValues">${optionList([['preserve','Preserve — add defaults only to missing fields'],['fill','Fill — also fill existing blank fields'],['reset','Reset — overwrite template fields with defaults']],'preserve')}</select></div><div class="field-row"><div class="field"><label>Variables in physical field names</label><select id="enforceNames">${optionList([['preserve','Preserve raw expressions'],['resolve','Bake resolved names (loses expressions)']],'preserve')}</select></div><div class="field"><label>Variables in template field values</label><select id="enforceValueVariables">${optionList([['preserve','Preserve raw expressions'],['bake','Bake resolved values (loses expressions)']],'preserve')}</select></div></div><label class="check-label"><input id="enforceVisibility" type="checkbox">Also apply template visibility to existing schematic fields</label><label class="check-label"><input id="enforceRegister" type="checkbox" checked>Register native project field-name defaults for future symbols</label><p class="fine">Mandatory fields, simulation metadata, references and native population/inclusion flags are protected. Differing nonempty aliases are a conflict, not a license to discard one.</p><div class="form-actions"><button data-act="closeDialog">Cancel</button><button class="primary" data-act="enforcePreview">Preview all changes →</button></div>`);
}
async function enforcePreview(){
  const options={mode:$('#enforceMode').value,values:$('#enforceValues').value,names:$('#enforceNames').value,value_variables:$('#enforceValueVariables').value,apply_visibility:$('#enforceVisibility').checked,register_native:$('#enforceRegister').checked};
  const p=await api('field/enforce/preview',{profile:S.enforceProfile,options});S.enforcePreview=p;
  const events=p.events.slice(0,400),issues=p.errors;
  showDialog('Review field enforcement',`<div class="notice warning">${esc(p.warning)}</div><div class="stats-strip"><span class="chip">${p.components} components</span><span class="chip">${p.variants} variants</span><span class="chip">${p.events.length} field actions</span><span class="chip">${p.variable_losses} expression-loss actions</span></div><p class="fine">${esc(Object.entries(p.counts).map(([k,n])=>k+': '+n).join(' · ')||'Field values already match. Native field order/defaults may still be staged.')}</p>${issues.length?`<div class="notice error"><b>${issues.length} conflicts — enforcement blocked.</b><ul>${issues.slice(0,40).map(e=>`<li>${esc(e.variant)} / ${esc(e.reference)}: ${esc(e.message)}</li>`).join('')}</ul></div>`:''}<div class="table-wrap enforce-table"><table class="data-table"><thead><tr><th>Variant / part</th><th>Action</th><th>Field</th><th>Before</th><th>After</th></tr></thead><tbody>${events.map(e=>`<tr class="${e.variable_loss?'loss-row':''}"><td>${esc(e.variant)}<br><b>${esc(e.reference)}</b></td><td>${esc(e.action)}${e.variable_loss?'<br><strong>Expression loss</strong>':''}</td><td>${esc(e.field)}${e.target?' → '+esc(e.target):''}</td><td><code>${esc(typeof e.before==='object'&&e.before!==null?JSON.stringify(e.before):e.before??'—')}</code></td><td><code>${esc(typeof e.after==='object'&&e.after!==null?JSON.stringify(e.after):e.after??'—')}</code></td></tr>`).join('')}</tbody></table></div><p class="fine">Showing ${events.length} of ${p.events.length} actions. <button type="button" class="linkbutton" data-act="saveEnforcePreview">Save full review JSON ↗</button> Visibility policy: ${options.apply_visibility?'apply template flags':'preserve existing schematic visibility'}.</p><details><summary>Native project field defaults</summary><pre class="codeblock">${esc(JSON.stringify(p.native_templates,null,2))}</pre><p class="fine">${options.register_native?'Will be staged for .kicad_pro native sync.':'Registration disabled; shown for reference only.'}</p></details>${!issues.length?`<div class="field spaced"><label>Type ENFORCE to stage the reviewed changes</label><input id="enforceConfirmation" name="confirmation" autocomplete="off" required></div><label class="check-label"><input id="enforceAcknowledge" name="acknowledge" type="checkbox">I understand fields, values and variable expressions may be lost. I have reviewed the proposed changes and kept a backup.</label>${formActions('Enforce in workspace')}`:'<div class="form-actions"><button type="button" data-act="closeDialog">Close and fix conflicts</button></div>'}`,!issues.length?async f=>{
    await api('field/enforce/apply',{fingerprint:p.fingerprint,confirmation:f.get('confirmation'),acknowledge_loss:!!f.get('acknowledge')});await refresh();toast('Field schema staged. Undo is available. Use Review & native sync for KiCad files.');
  }:null);
}
function saveLocalJson(payload,name){const blob=new Blob([JSON.stringify(payload,null,2)+'\n'],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
Object.assign(handlers,{
  columns:columnsDialogV2,addColumn:()=>{S.formDirty=true;$('#templateColumns').insertAdjacentHTML('beforeend',templateColumnV2());},saveTemplate:async()=>{await ensureTemplateSaved();await refresh();toast('BOM template saved.');},previewExport:previewExportV2,downloadExport:()=>exportV2(false),downloadRelease:()=>exportV2(true),
  useExportColumns:async()=>{await ensureTemplateSaved();const columns=[...new Set(S.data.templates[S.template].columns.filter(c=>c.export!==false&&!c.field.includes('${')).map(c=>c.field))];if(!columns.length)throw Error('No physical columns selected. Virtual columns are export-only.');await api('view',{view:{columns}});await refresh();toast('Workspace column layout updated. Export template unchanged.');},
  newDefinition,manageDefinition,shareDefinition,shareAllDefinitions:async()=>{await prepareDefinition(S.view==='fieldtemplates'?'field_profiles':'templates');await originalDownload('catalog/export',{});},importDefinitions,previewTemplateImport,applyTemplateImport,
  viewUp:e=>moveRow(e,'.view-column',-1),viewDown:e=>moveRow(e,'.view-column',1),viewAll:()=>$$('#viewColumns input').forEach(e=>e.checked=true),viewNone:()=>$$('#viewColumns input').forEach(e=>e.checked=false),
  addSchemaField:()=>{S.formDirty=true;$('#fieldSchemaRows').insertAdjacentHTML('beforeend',fieldSchemaRow());},schemaUp:e=>moveRow(e,'.field-schema-row',-1),schemaDown:e=>moveRow(e,'.field-schema-row',1),schemaRemove:e=>{S.formDirty=true;e.closest('.field-schema-row').remove();},saveFieldProfile:()=>saveFieldProfile(true),enforceOptions,enforcePreview,saveEnforcePreview:()=>saveLocalJson(S.enforcePreview,'WayriCAD_Field_Enforcement_Review.json')
});
document.addEventListener('change',async event=>{const e=event.target;try{
  if(e.id==='viewPreset'){const columns=S.data.view_presets[e.value]?.columns||S.columns;populateViewColumns(columns);$('#viewPresetName').value=e.value;}
  if(e.id==='fieldProfileSelect'){if(S.formDirty&&!confirm('Discard unsaved field-template edits?')){e.value=S.fieldProfile;return;}S.fieldProfile=e.value;render();return;}
  if(e.closest('.field-profile-form'))S.formDirty=true;
}catch(error){toast(error.message,true);}});
document.addEventListener('input',event=>{const e=event.target;if(e.closest('.field-profile-form'))S.formDirty=true;if(e.id==='viewColumnSearch')$$('#viewColumns .view-column').forEach(row=>row.hidden=!row.textContent.toLowerCase().includes(e.value.toLowerCase()));});
let draggedRow=null,draggedColumn=null;
document.addEventListener('dragstart',e=>{
  if(e.target.closest('input,textarea,select')){e.preventDefault();return;}
  draggedRow=e.target.closest('[data-drag-row]');draggedColumn=e.target.closest('[data-grid-column]');
  const target=draggedRow||draggedColumn;if(target){target.classList.add('dragging');e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',draggedColumn?.dataset.gridColumn||'column');}
});
document.addEventListener('dragover',e=>{const row=e.target.closest('[data-drag-row]'),column=e.target.closest('[data-grid-column]');if((draggedRow&&row?.parentNode===draggedRow.parentNode)||(draggedColumn&&column))e.preventDefault();});
document.addEventListener('drop',async e=>{const row=e.target.closest('[data-drag-row]'),column=e.target.closest('[data-grid-column]');try{
  if(draggedRow&&row&&row!==draggedRow&&row.parentNode===draggedRow.parentNode){e.preventDefault();const after=e.clientY>row.getBoundingClientRect().top+row.offsetHeight/2;row.parentNode.insertBefore(draggedRow,after?row.nextSibling:row);if(row.dataset.dragRow!=='view')S.formDirty=true;}
  if(draggedColumn&&column&&column!==draggedColumn){e.preventDefault();const columns=[...S.columns],from=columns.indexOf(draggedColumn.dataset.gridColumn),to=columns.indexOf(column.dataset.gridColumn);columns.splice(to,0,columns.splice(from,1)[0]);await api('view',{view:{columns}});await refresh();toast('Workspace column order updated.');}
}catch(error){toast(error.message,true);}finally{$$('.dragging').forEach(n=>n.classList.remove('dragging'));draggedRow=null;draggedColumn=null;}});
document.addEventListener('dragend',()=>{$$('.dragging').forEach(n=>n.classList.remove('dragging'));draggedRow=null;draggedColumn=null;});
// Initial refresh is performed by intelligence.js.
